// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

import "@spectrum-web-components/theme/sp-theme.js"
;

import "@spectrum-web-components/theme/spectrum-two/theme-light.js"
;

import "@spectrum-web-components/theme/spectrum-two/theme-lightest.js"
;

import "@spectrum-web-components/theme/spectrum-two/theme-darkest.js"
;

import "@spectrum-web-components/theme/express/theme-light.js"
;

import "@spectrum-web-components/theme/express/theme-dark.js"
;

import "@spectrum-web-components/theme/express/scale-medium.js"
;

import "@spectrum-web-components/theme/spectrum-two/theme-dark.js"
;

import "@spectrum-web-components/theme/spectrum-two/scale-medium.js"
;

import "@spectrum-web-components/action-button/sp-action-button.js"
;

import "@spectrum-web-components/button/sp-button.js"
;

import "@spectrum-web-components/switch/sp-switch.js"
;

import "@spectrum-web-components/picker/sp-picker.js"
;

import "@spectrum-web-components/menu/sp-menu-item.js"
;

import "@spectrum-web-components/textfield/sp-textfield.js"
;

import "@spectrum-web-components/field-label/sp-field-label.js"
;

function Spectrum$Theme(props) {
  let __scale = props.scale;
  let __scale_value = __scale !== undefined ? __scale : "medium";
  return React.createElement("sp-theme", {
    system: props.system,
    color: props.color,
    scale: __scale_value,
    className: props.className,
    children: props.children
  });
}

let Theme = {
  make: Spectrum$Theme
};

function Spectrum$ActionButton(props) {
  let __quiet = props.quiet;
  let __selected = props.selected;
  let label = props.label;
  let __selected_value = __selected !== undefined ? __selected : false;
  let __quiet_value = __quiet !== undefined ? __quiet : true;
  return React.createElement("sp-action-button", {
    quiet: __quiet_value,
    selected: __selected_value,
    size: props.size,
    disabled: props.disabled,
    title: label,
    "aria-label": label,
    "aria-pressed": Stdlib_Option.map(props.pressed, value => {
      if (value) {
        return "true";
      } else {
        return "false";
      }
    }),
    onClick: props.onClick,
    className: props.className,
    children: props.children
  });
}

let ActionButton = {
  make: Spectrum$ActionButton
};

function Spectrum$Button(props) {
  let __variant = props.variant;
  let __variant_value = __variant !== undefined ? __variant : "accent";
  return React.createElement("sp-button", {
    variant: __variant_value,
    treatment: props.treatment,
    size: props.size,
    disabled: props.disabled,
    onClick: props.onClick,
    className: props.className,
    children: props.children
  });
}

let Button = {
  make: Spectrum$Button
};

function Spectrum$Switch(props) {
  return React.createElement("sp-switch", {
    checked: props.checked,
    size: props.size,
    ariaLabel: props.ariaLabel,
    onChange: props.onChange,
    className: props.className,
    children: props.children
  });
}

let Switch = {
  make: Spectrum$Switch
};

function Spectrum$Picker(props) {
  let __quiet = props.quiet;
  let label = props.label;
  let __quiet_value = __quiet !== undefined ? __quiet : true;
  return React.createElement("sp-picker", {
    value: props.value,
    size: props.size,
    quiet: __quiet_value,
    label: label,
    "aria-label": label,
    onChange: props.onChange,
    className: props.className,
    children: props.children
  });
}

let Picker = {
  make: Spectrum$Picker
};

function Spectrum$MenuItem(props) {
  return React.createElement("sp-menu-item", {
    value: props.value,
    selected: props.selected,
    className: props.className,
    children: props.children
  });
}

let MenuItem = {
  make: Spectrum$MenuItem
};

function Spectrum$Textfield(props) {
  return React.createElement("sp-textfield", {
    id: props.id,
    value: props.value,
    placeholder: props.placeholder,
    size: props.size,
    quiet: props.quiet,
    onInput: props.onInput,
    className: props.className
  });
}

let Textfield = {
  make: Spectrum$Textfield
};

function Spectrum$FieldLabel(props) {
  return React.createElement("sp-field-label", {
    for_: props.for_,
    size: props.size,
    className: props.className,
    children: props.children
  });
}

let FieldLabel = {
  make: Spectrum$FieldLabel
};

export {
  Theme,
  ActionButton,
  Button,
  Switch,
  Picker,
  MenuItem,
  Textfield,
  FieldLabel,
}
/*  Not a pure module */
