// Generated by ReScript, PLEASE EDIT WITH CARE


let randomBytes = (function (length) {
  return Array.from(crypto.getRandomValues(new Uint8Array(length)));
});

let newSalt = (function () {
  const bytes = crypto.getRandomValues(new Uint8Array(16));
  let binary = "";
  for (const byte of bytes) binary += String.fromCharCode(byte);
  return btoa(binary).replaceAll("+", "-").replaceAll("/", "_").replace(/=+$/, "");
});

let generateIdentity = (async function () {
  const pair = await crypto.subtle.generateKey(
    { name: "ECDH", namedCurve: "P-256" }, true, ["deriveKey", "deriveBits"]
  );
  const pub = await crypto.subtle.exportKey("jwk", pair.publicKey);
  const priv = await crypto.subtle.exportKey("jwk", pair.privateKey);
  return { pub: JSON.stringify(pub), priv: JSON.stringify(priv) };
});

let wrapWithSecret = (async function (secret, salt, iterations, text) {
  const bytesOf = (encoded) => {
    const binary = atob(encoded.replaceAll("-", "+").replaceAll("_", "/"));
    const bytes = new Uint8Array(binary.length);
    for (let index = 0; index < binary.length; index += 1) bytes[index] = binary.charCodeAt(index);
    return bytes;
  };
  const material = await crypto.subtle.importKey(
    "raw", new TextEncoder().encode(secret), "PBKDF2", false, ["deriveKey"]
  );
  const key = await crypto.subtle.deriveKey(
    { name: "PBKDF2", salt: bytesOf(salt), iterations, hash: "SHA-256" },
    material,
    { name: "AES-GCM", length: 256 },
    false,
    ["encrypt"]
  );
  const iv = crypto.getRandomValues(new Uint8Array(12));
  const sealed = new Uint8Array(
    await crypto.subtle.encrypt({ name: "AES-GCM", iv }, key, new TextEncoder().encode(text))
  );
  const joined = new Uint8Array(iv.length + sealed.length);
  joined.set(iv);
  joined.set(sealed, iv.length);
  let binary = "";
  for (const byte of joined) binary += String.fromCharCode(byte);
  return btoa(binary).replaceAll("+", "-").replaceAll("/", "_").replace(/=+$/, "");
});

let unwrapWithSecret = (async function (secret, salt, iterations, payload) {
  try {
    const bytesOf = (encoded) => {
      const binary = atob(encoded.replaceAll("-", "+").replaceAll("_", "/"));
      const bytes = new Uint8Array(binary.length);
      for (let index = 0; index < binary.length; index += 1) bytes[index] = binary.charCodeAt(index);
      return bytes;
    };
    const material = await crypto.subtle.importKey(
      "raw", new TextEncoder().encode(secret), "PBKDF2", false, ["deriveKey"]
    );
    const key = await crypto.subtle.deriveKey(
      { name: "PBKDF2", salt: bytesOf(salt), iterations, hash: "SHA-256" },
      material,
      { name: "AES-GCM", length: 256 },
      false,
      ["decrypt"]
    );
    const joined = bytesOf(payload);
    const opened = await crypto.subtle.decrypt(
      { name: "AES-GCM", iv: joined.slice(0, 12) }, key, joined.slice(12)
    );
    return new TextDecoder().decode(opened);
  } catch (error) {
    return undefined;
  }
});

let iterations = 600000;

let recoverySalt = "cm4tcmVjb3Zlcnk";

export {
  iterations,
  recoverySalt,
  randomBytes,
  newSalt,
  generateIdentity,
  wrapWithSecret,
  unwrapWithSecret,
}
/* generateIdentity Not a pure module */
