// Generated by ReScript, PLEASE EDIT WITH CARE

import * as AiHistory from "../core/AiHistory.res.mjs";
import * as OpenAiClient from "./OpenAiClient.res.mjs";

let userMessage = (function (text) { return { role: "user", content: text }; });

let systemMessage = (function (text) { return { role: "system", content: text }; });

async function run(settings, system, history, question, tools, onText, onThinking, onCall, dispatch, signal) {
  let wire = AiHistory.compact(history).concat([userMessage(question)]);
  let failure = "";
  let finished = false;
  let steps = 0;
  let nudges = 0;
  let retries = 0;
  while (!finished && steps < 96) {
    steps = steps + 1 | 0;
    let reply = await OpenAiClient.complete(settings, [systemMessage(system)].concat(wire), tools, onText, onThinking, signal);
    if (reply.ok) {
      wire = wire.concat([reply.message]);
      let calls = reply.calls;
      if (calls.length === 0) {
        let text = reply.text.trim();
        let pastedDocument = /^appId:/m.test(reply.text);
        if ((text === "" || pastedDocument) && nudges === 0) {
          nudges = 1;
          wire = wire.concat([userMessage(text === "" ? "You ended your turn without saying anything and without calling a tool. If you have enough to write the app, write the complete document now and deliver it with reactive_create_app. If something is genuinely missing, ask one short question." : "You wrote the document into the chat instead of delivering it. A document in a message is not an app in the gallery — the user cannot open it. Call reactive_create_app now with that complete document, then tell the user in one sentence what you built.")]);
        } else {
          finished = true;
        }
      } else {
        for (let index = 0, index_finish = calls.length; index < index_finish; ++index) {
          let call = calls[index];
          if (call !== undefined) {
            onCall(call.name, call.arguments);
            let answer = await dispatch(call.name, call.arguments);
            wire = wire.concat([OpenAiClient.toolMessage(settings, call.id, call.name, answer)]);
          }
        }
      }
    } else if (reply.error.startsWith("HTTP 5") && retries === 0) {
      retries = 1;
    } else {
      failure = reply.error;
      finished = true;
    }
  };
  return {
    ok: failure === "" && finished,
    error: failure,
    stalled: failure === "" && !finished,
    history: wire
  };
}

let maxSteps = 96;

export {
  maxSteps,
  run,
}
/* OpenAiClient Not a pure module */
