// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Idb from "./Idb.res.mjs";
import * as AiSettings from "../core/AiSettings.res.mjs";
import * as Stdlib_JSON from "@rescript/runtime/lib/es6/Stdlib_JSON.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

let settingsKey = "ai.settings";

let historyKey = "ai.history";

function loadSettings() {
  return Idb.get(settingsKey).then(stored => {
    if (stored == null) {
      return AiSettings.blank;
    }
    let value;
    try {
      value = JSON.parse(stored);
    } catch (exn) {
      return AiSettings.blank;
    }
    let fields = Stdlib_JSON.Decode.object(value);
    if (fields === undefined) {
      return AiSettings.blank;
    }
    let read = (name, fallback) => Stdlib_Option.getOr(Stdlib_Option.flatMap(fields[name], Stdlib_JSON.Decode.string), fallback);
    return AiSettings.normalize({
      key: read("key", ""),
      model: read("model", AiSettings.defaultModel),
      baseUrl: read("baseUrl", AiSettings.hostedBaseUrl)
    });
  });
}

function saveSettings(settings) {
  let normalized = AiSettings.normalize(settings);
  return Idb.set(settingsKey, Stdlib_Option.getOr(JSON.stringify({
    key: normalized.key,
    model: normalized.model,
    baseUrl: normalized.baseUrl
  }), "{}"));
}

function loadHistory() {
  return Idb.get(historyKey).then(stored => {
    if (stored == null) {
      return;
    }
    let value;
    try {
      value = JSON.parse(stored);
    } catch (exn) {
      return;
    }
    return value;
  });
}

function saveHistory(value) {
  return Idb.set(historyKey, JSON.stringify(value));
}

function clearHistory() {
  return Idb.remove(historyKey);
}

export {
  loadSettings,
  saveSettings,
  loadHistory,
  saveHistory,
  clearHistory,
}
/* Idb Not a pure module */
