// Generated by ReScript, PLEASE EDIT WITH CARE


import * as Automerge from "@automerge/automerge/slim";
import wasmUrl from "@automerge/automerge/automerge.wasm?url";

let ready = null;
const docs = new Map();

const toB64 = (bytes) => {
  let binary = "";
  for (const byte of bytes) binary += String.fromCharCode(byte);
  return btoa(binary);
};
const fromB64 = (encoded) => {
  const binary = atob(encoded);
  const bytes = new Uint8Array(binary.length);
  for (let index = 0; index < binary.length; index += 1) bytes[index] = binary.charCodeAt(index);
  return bytes;
};
const headsOf = (doc) => Automerge.getHeads(doc).join(",");
;

let init = (function () {
  if (!ready) {
    ready = Automerge.initializeWasm(fetch(wasmUrl));
  }
  return ready;
});

let open_ = (function (app, saved) {
  if (saved !== undefined && saved !== "") {
    try {
      docs.set(app, Automerge.load(fromB64(saved)));
      return;
    } catch (error) {
      // A copy that will not load is dropped, not fatal: the log on the server
      // still holds the history, and the next pull rebuilds from it.
    }
  }
  docs.set(app, Automerge.init());
});

let close = (function (app) {
  docs.delete(app);
});

let save = (function (app) {
  const doc = docs.get(app);
  return doc ? toB64(Automerge.save(doc)) : "";
});

let applyLocal = (function (app, snapshot) {
  const before = docs.get(app);
  if (!before) return undefined;
  const wanted = JSON.parse(snapshot);
  const after = Automerge.change(before, (d) => {
    if (typeof wanted.source === "string") {
      if (d.source === undefined) {
        d.source = wanted.source;
      } else if (d.source !== wanted.source) {
        Automerge.updateText(d, ["source"], wanted.source);
      }
    }
    if (d.collections === undefined) d.collections = {};
    const target = wanted.collections || {};
    for (const path of Object.keys(d.collections)) {
      if (!(path in target)) delete d.collections[path];
    }
    for (const path of Object.keys(target)) {
      if (!d.collections[path]) d.collections[path] = {};
      const rows = target[path];
      const held = d.collections[path];
      for (const id of Object.keys(held)) {
        if (!(id in rows)) delete held[id];
      }
      for (const id of Object.keys(rows)) {
        if (!held[id]) held[id] = {};
        const fields = rows[id];
        const row = held[id];
        for (const name of Object.keys(row)) {
          if (!(name in fields)) delete row[name];
        }
        for (const name of Object.keys(fields)) {
          if (row[name] !== fields[name]) row[name] = fields[name];
        }
      }
    }
  });
  if (headsOf(after) === headsOf(before)) return undefined;
  docs.set(app, after);
  const change = Automerge.getLastLocalChange(after);
  return change ? toB64(change) : undefined;
});

let applyRemote = (function (app, changes) {
  const before = docs.get(app);
  if (!before) return false;
  const decoded = [];
  for (const encoded of changes) {
    try {
      decoded.push(fromB64(encoded));
    } catch (error) {
      // One undecodable blob must not stop the ones behind it.
    }
  }
  if (decoded.length === 0) return false;
  let after = before;
  try {
    [after] = Automerge.applyChanges(before, decoded);
  } catch (error) {
    return false;
  }
  const moved = headsOf(after) !== headsOf(before);
  docs.set(app, after);
  return moved;
});

let mergeSaved = (function (app, saved) {
  const before = docs.get(app);
  if (!before || saved === "") return false;
  let other;
  try {
    other = Automerge.load(fromB64(saved));
  } catch (error) {
    return false;
  }
  const after = Automerge.merge(before, other);
  const moved = headsOf(after) !== headsOf(before);
  docs.set(app, after);
  return moved;
});

let materialize = (function (app) {
  const doc = docs.get(app);
  if (!doc) return JSON.stringify({ source: "", collections: {} });
  const plain = JSON.parse(JSON.stringify(doc));
  return JSON.stringify({
    source: typeof plain.source === "string" ? plain.source : "",
    collections: plain.collections && typeof plain.collections === "object" ? plain.collections : {},
  });
});

export {
  init,
  open_,
  close,
  save,
  applyLocal,
  applyRemote,
  mergeSaved,
  materialize,
}
/*  Not a pure module */
