// Generated by ReScript, PLEASE EDIT WITH CARE


let track = (function (node, property) {
  const root = document.documentElement;
  const write = () => {
    root.style.setProperty(property, node.getBoundingClientRect().height + "px");
  };
  write();
  // Every browser this app supports has it; the guard is for a test environment
  // without a layout engine, where the fallback in the stylesheet is the answer.
  if (typeof ResizeObserver !== "function") return () => {};
  const observer = new ResizeObserver(write);
  observer.observe(node);
  return () => {
    observer.disconnect();
    root.style.removeProperty(property);
  };
});

export {
  track,
}
/* No side effect */
