// Generated by ReScript, PLEASE EDIT WITH CARE


let fetchDocument = (async function (id) {
  try {
    const response = await fetch("/catalog/app/" + encodeURIComponent(id) + ".md",
                                 { cache: "no-cache" });
    // 404 is the catalogue answering: it is there, and it does not have this.
    if (response.status === 404) return { text: undefined, missing: true };
    if (!response.ok) return { text: undefined, missing: false };
    const text = await response.text();
    // A site that answers every unknown address with its own HTML would otherwise
    // hand back a page and call it a document. A document opens with frontmatter.
    return text.startsWith("---")
      ? { text, missing: false }
      : { text: undefined, missing: true };
  } catch (error) {
    return { text: undefined, missing: false };
  }
});

let fetchIndex = (async function () {
  try {
    const response = await fetch(
      "/catalog/app/index.json",
      { cache: "no-cache" }
    );
    if (!response.ok) return [];
    const entries = await response.json();
    if (!Array.isArray(entries)) return [];
    return entries
      .filter((entry) => entry && typeof entry.id === "string" && entry.id !== "")
      // The fields are read from somebody else's file, so each is given a type
      // here rather than trusted: a version that arrives as a number would be
      // compared against a string and never match.
      .map((entry) => ({
        id: entry.id,
        title: typeof entry.title === "string" ? entry.title : "",
        description: typeof entry.description === "string" ? entry.description : "",
        version: typeof entry.version === "string" ? entry.version : "",
      }));
  } catch (error) {
    return [];
  }
});

let prefix = "/catalog";

export {
  prefix,
  fetchDocument,
  fetchIndex,
}
/* fetchDocument Not a pure module */
