// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Route from "../core/Route.res.mjs";

let copy = (function (text) {
  try {
    if (!navigator.clipboard || !navigator.clipboard.writeText) return Promise.resolve(false);
    return navigator.clipboard.writeText(text).then(() => true, () => false);
  } catch {
    return Promise.resolve(false);
  }
});

function absolute(route) {
  return location.origin + Route.toPath(route);
}

let origin = location.origin;

export {
  copy,
  absolute,
  origin,
}
/* origin Not a pure module */
