// Generated by ReScript, PLEASE EDIT WITH CARE

import * as DateValue from "../core/DateValue.res.mjs";

let timestamp = (function () { return new Date().toISOString(); });

let format = (function (value, locale) {
  try {
    const day = /^(\d{4})-(\d{2})-(\d{2})$/.exec(value.trim());
    if (day) {
      return new Intl.DateTimeFormat(locale, { dateStyle: "medium" })
        .format(new Date(Number(day[1]), Number(day[2]) - 1, Number(day[3])));
    }
    const moment = new Date(value);
    if (Number.isNaN(moment.getTime())) return value;
    return new Intl.DateTimeFormat(locale, { dateStyle: "medium", timeStyle: "short" })
      .format(moment);
  } catch (error) {
    // A locale the runtime has no data for is not a reason to lose the value.
    return value;
  }
});

function localize(value, locale) {
  if (DateValue.isDate(value)) {
    return format(value, locale);
  } else {
    return value;
  }
}

let monthLabel = (function (year, month, locale) {
  try {
    return new Intl.DateTimeFormat(locale, { month: "long", year: "numeric" })
      .format(new Date(year, month - 1, 1, 12));
  } catch (error) {
    return year + "-" + String(month).padStart(2, "0");
  }
});

let weekdayNames = (function (locale, startsMonday) {
  try {
    const format = new Intl.DateTimeFormat(locale, { weekday: "short" });
    // 2026-02-01 was a Sunday, so the seven days from it are one of each.
    const days = [];
    for (let index = 0; index < 7; index += 1) {
      days.push(format.format(new Date(2026, 1, 1 + index, 12)));
    }
    return startsMonday ? days.slice(1).concat(days.slice(0, 1)) : days;
  } catch (error) {
    return ["", "", "", "", "", "", ""];
  }
});

export {
  timestamp,
  localize,
  monthLabel,
  weekdayNames,
}
/* No side effect */
