// Generated by ReScript, PLEASE EDIT WITH CARE


let bind = (function (container) {
  container.querySelectorAll("[data-rn-columns]").forEach((element) => {
    const min = element.getAttribute("data-rn-columns");
    if (min) element.style.setProperty("--rn-col-min", min);
  });
});

export {
  bind,
}
/* No side effect */
