// Generated by ReScript, PLEASE EDIT WITH CARE


const selections = new WeakMap();
let lastLabels = { removeFilter: "✕" };

const dashOf = (node) => (node && node.closest ? node.closest("[data-rn-dashboard]") : null);

const fieldOf = (record, name) => {
  for (const field of record.fields) {
    if (field.name.toLowerCase() === name.toLowerCase()) return field.value;
  }
  return undefined;
};

const paintChip = (dash) => {
  const holder = dash.querySelector(":scope > .rn-dashboard-chip");
  if (!holder) return;
  holder.textContent = "";
  const selection = selections.get(dash);
  if (!selection) return;
  const chip = document.createElement("span");
  chip.className = "rn-chip";
  const text = document.createElement("span");
  text.textContent = selection.field + " = " + selection.value;
  const clear = document.createElement("button");
  clear.type = "button";
  clear.className = "rn-chip-clear";
  clear.setAttribute("aria-label", lastLabels.removeFilter);
  clear.setAttribute("title", lastLabels.removeFilter);
  clear.textContent = "✕";
  clear.addEventListener("click", () => {
    selections.delete(dash);
    paintChip(dash);
    window.dispatchEvent(new Event("rn:data"));
  });
  chip.appendChild(text);
  chip.appendChild(clear);
  holder.appendChild(chip);
};

globalThis.__rnDashboard = {
  // The selection governing this node, or null outside any dashboard.
  selectionFor(node) {
    const dash = dashOf(node);
    return dash ? selections.get(dash) || null : null;
  },

  // What a view inside a dashboard actually shows: the rows that match the
  // selection — or carry no such field at all.
  rowsFor(node, records) {
    const dash = dashOf(node);
    if (!dash) return records;
    const selection = selections.get(dash);
    if (!selection) return records;
    return records.filter((record) => {
      const value = fieldOf(record, selection.field);
      return value === undefined || String(value) === selection.value;
    });
  },

  // A chart's click: select, or clear when it is the same value again.
  toggle(node, field, value) {
    const dash = dashOf(node);
    if (!dash || !field) return;
    const current = selections.get(dash);
    if (current && current.field === field && current.value === value) selections.delete(dash);
    else selections.set(dash, { field, value });
    paintChip(dash);
    window.dispatchEvent(new Event("rn:data"));
  },
};
;

let install = (function (labels) {
  return function (container) {
    lastLabels = labels;
    container.querySelectorAll("[data-rn-dashboard]").forEach(paintChip);
  };
});

function bind(container, labels) {
  install(labels)(container);
}

export {
  bind,
}
/*  Not a pure module */
