// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Idb from "./Idb.res.mjs";
import * as AppId from "../core/AppId.res.mjs";
import * as AppDocument from "../core/AppDocument.res.mjs";
import * as DocumentKey from "../core/DocumentKey.res.mjs";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as CollectionKey from "../core/CollectionKey.res.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function load(id) {
  return Idb.get(DocumentKey.of_(id)).then(prim => {
    if (prim == null) {
      return;
    } else {
      return Primitive_option.some(prim);
    }
  });
}

function save(id, source) {
  return Idb.set(DocumentKey.of_(id), source);
}

function ids() {
  return Idb.keys().then(keys => Stdlib_Array.filterMap(keys, DocumentKey.idOf));
}

function list() {
  return ids().then(found => Promise.all(found.map(id => load(id).then(source => Stdlib_Option.map(source, text => AppDocument.summary(id, text)))))).then(summaries => AppDocument.order(Stdlib_Array.filterMap(summaries, summary => summary)));
}

function remove(id) {
  return Idb.keys().then(keys => {
    let mine = keys.filter(key => {
      if (key === DocumentKey.of_(id)) {
        return true;
      } else {
        return key.startsWith(CollectionKey.appPrefix(id));
      }
    });
    return Promise.all(mine.map(Idb.remove));
  }).then(param => {});
}

function rename(from, to_, source) {
  if (from === to_) {
    return Idb.set(DocumentKey.of_(to_), source);
  } else {
    return Idb.keys().then(keys => {
      let collections = Stdlib_Array.filterMap(keys, key => Stdlib_Option.map(CollectionKey.pathOf(from, key), path => [
        key,
        path
      ]));
      return Promise.all(collections.map(param => {
        let path = param[1];
        let key = param[0];
        return Idb.get(key).then(value => {
          if (value == null) {
            return Promise.resolve();
          } else {
            return Idb.set(CollectionKey.of_(to_, path), value).then(() => Idb.remove(key));
          }
        });
      }));
    }).then(param => Idb.remove(DocumentKey.of_(from))).then(() => Idb.set(DocumentKey.of_(to_), source));
  }
}

function duplicate(from) {
  return load(from).then(stored => {
    if (stored !== undefined) {
      return ids().then(taken => {
        let id = AppId.unique(from, taken);
        let source = AppDocument.withId(stored, id);
        return Idb.set(DocumentKey.of_(id), source).then(() => id);
      });
    } else {
      return Promise.resolve(undefined);
    }
  });
}

export {
  load,
  save,
  list,
  ids,
  remove,
  rename,
  duplicate,
}
/* Idb Not a pure module */
