// Generated by ReScript, PLEASE EDIT WITH CARE


import perspective from "@finos/perspective";
import perspectiveViewer from "@finos/perspective-viewer";
import "@finos/perspective-viewer-datagrid";
import "@finos/perspective-viewer-d3fc";
// The viewer is styleless without a theme, and the d3fc plugins read their
// palette from it: no theme, null styles, a crash instead of a chart.
import "@finos/perspective-viewer/dist/css/pro.css";
// Under a bundler the WASM halves are not found by themselves: each is named
// as an asset URL and handed to its init. Same-origin either way, so the CSP
// is untouched.
import serverWasm from "@finos/perspective/dist/wasm/perspective-server.wasm?url";
import clientWasm from "@finos/perspective/dist/wasm/perspective-js.wasm?url";
import viewerWasm from "@finos/perspective-viewer/dist/wasm/perspective-viewer.wasm?url";

let workerPromise = null;
const sharedWorker = () => {
  if (!workerPromise) {
    workerPromise = (async () => {
      perspective.init_server(fetch(serverWasm));
      perspective.init_client(fetch(clientWasm));
      await perspectiveViewer.init_client(fetch(viewerWasm));
      return perspective.worker();
    })();
  }
  return workerPromise;
};

globalThis.__rnPerspective = { sharedWorker };
;

let makeTable = (async function (rows) {
  const worker = await globalThis.__rnPerspective.sharedWorker();
  return worker.table(rows);
});

let replaceRows = (async function (table, rows) {
  await table.replace(rows);
});

let makeViewer = (async function (host, table, config) {
  const viewer = document.createElement("perspective-viewer");
  viewer.style.width = "100%";
  viewer.style.height = "100%";
  host.textContent = "";
  host.appendChild(viewer);
  await viewer.load(table);
  // restore() is all-or-nothing, and there is no second chance: a configuration
  // it refuses stays pending on the element, so even restoring the plugin alone
  // afterwards fails with the same complaint. Whatever is handed here has to be
  // one the table can honour — which is why the binder drops column names the
  // rows do not have before this is called.
  try { await viewer.restore(config); } catch {}
  return viewer;
});

let deleteViewer = (async function (viewer) {
  // delete() rejects if the element never finished loading — a teardown that
  // throws would leave the caller mid-swap, and there is nothing to recover.
  try { await viewer.delete(); } catch {}
  viewer.remove();
});

let saveConfig = (function (viewer) {
  return viewer.save();
});

export {
  makeTable,
  replaceRows,
  makeViewer,
  deleteViewer,
  saveConfig,
}
/*  Not a pure module */
