// Generated by ReScript, PLEASE EDIT WITH CARE

import * as FileStore from "./FileStore.res.mjs";

let install = (function (saveLocal) {
  const INLINE_CEILING = 300000;

  return function (container, app, labels) {
    container.querySelectorAll("[data-rn-file]").forEach((input) => {
      const holder = input.closest(".rn-file-field");
      const hidden = holder && holder.querySelector('input[type="hidden"].rn-field-input');
      const preview = holder && holder.querySelector(".rn-file-preview");
      const status = holder && holder.querySelector(".rn-od-status");
      if (!hidden) return;

      const accept = input.getAttribute("data-rn-file-accept");
      if (accept) input.accept = accept;
      const maxGiven = parseInt(input.getAttribute("data-rn-file-maxkb") || "", 10);
      const maxBytes = (Number.isNaN(maxGiven) ? 10240 : maxGiven) * 1024;

      const say = (text, error) => {
        if (!status) return;
        status.textContent = text;
        status.className = "rn-od-status " + (error ? "rn-error" : "rn-muted");
      };

      const paintPreview = (name, dataUrl) => {
        if (!preview) return;
        preview.textContent = "";
        if (dataUrl && dataUrl.startsWith("data:image/")) {
          const img = document.createElement("img");
          img.src = dataUrl;
          img.alt = name;
          img.className = "rn-file-image";
          preview.appendChild(img);
        } else if (name) {
          preview.textContent = name;
        }
      };

      input.addEventListener("change", () => {
        const file = input.files && input.files[0];
        if (!file) return;
        say("", false);
        if (file.size > maxBytes) {
          input.value = "";
          say(labels.tooBig.replace("{n}", String(Math.floor(maxBytes / 1024))), true);
          return;
        }
        const reader = new FileReader();
        reader.onload = async () => {
          const dataUrl = String(reader.result);
          let value;
          if (file.size <= INLINE_CEILING) {
            value = JSON.stringify({ name: file.name, data: dataUrl });
          } else {
            const id = crypto.randomUUID();
            await saveLocal(app, id, dataUrl);
            value = JSON.stringify({ name: file.name, local: id });
          }
          hidden.value = value;
          hidden.dispatchEvent(new Event("input", { bubbles: true }));
          paintPreview(file.name, dataUrl);
        };
        reader.onerror = () => say(labels.tooBig, true);
        reader.readAsDataURL(file);
      });
    });
  };
});

let binder = install(FileStore.save);

function bind(container, app, labels) {
  binder(container, app, labels);
}

export {
  bind,
}
/* binder Not a pure module */
