// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Idb from "./Idb.res.mjs";

function key(app, id) {
  return "filestore:" + app + ":" + id;
}

function save(app, id, dataUrl) {
  return Idb.set(key(app, id), dataUrl);
}

async function load(app, id) {
  let stored = await Idb.get(key(app, id));
  if ((stored == null) || !stored.startsWith("data:")) {
    return;
  } else {
    return stored;
  }
}

export {
  save,
  load,
}
/* Idb Not a pure module */
