// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Idb from "./Idb.res.mjs";
import * as Locale from "../core/Locale.res.mjs";

let storageKey = "locale";

function browserPreference() {
  return Locale.fromPreferred(navigator.languages);
}

async function load() {
  let stored = await Idb.get(storageKey);
  if (stored == null) {
    return;
  } else {
    return Locale.parse(stored);
  }
}

function save(locale) {
  Idb.set(storageKey, Locale.toTag(locale));
}

export {
  browserPreference,
  load,
  save,
}
/* Idb Not a pure module */
