// Generated by ReScript, PLEASE EDIT WITH CARE


let request = (async function (method, params) {
  try {
    const response = await fetch("/mcp", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        // Both, because the transport chooses its framing from this header and
        // refuses a request that accepts neither.
        Accept: "application/json, text/event-stream",
      },
      body: JSON.stringify({ jsonrpc: "2.0", id: 1, method, params: params || {} }),
    });
    if (!response.ok) return null;
    const body = await response.text();
    // Either framing: a bare JSON body, or SSE where the answer is the last data line.
    const payload = body.trimStart().startsWith("{")
      ? body
      : body
          .split("\n")
          .filter(line => line.startsWith("data:"))
          .map(line => line.slice(5).trim())
          .pop();
    if (!payload) return null;
    const message = JSON.parse(payload);
    return message && message.result !== undefined ? message.result : null;
  } catch (error) {
    return null;
  }
});

let noParams = {};

let toolsOf = (function (result) {
  if (!result || !Array.isArray(result.tools)) return [];
  return result.tools.map(tool => ({
    name: String(tool.name || ""),
    description: String(tool.description || ""),
    schema: tool.inputSchema || { type: "object", properties: {} },
  }));
});

function tools() {
  return request("tools/list", noParams).then(toolsOf);
}

let callParams = (function (name, argumentsJson) {
  try {
    return { name, arguments: argumentsJson ? JSON.parse(argumentsJson) : {} };
  } catch (error) {
    return undefined;
  }
});

let answerOf = (function (result) {
  if (!result)
    return {
      ok: false,
      text:
        "The ReactiveNET documentation server did not answer. It may not be running: " +
        "the user can start it with 'bun run mcp'. Do not guess the answer this tool would have given.",
    };
  const text = Array.isArray(result.content)
    ? result.content.filter(part => part && part.type === "text").map(part => part.text).join("\n")
    : "";
  return { ok: !result.isError, text: text || "(the tool answered with nothing)" };
});

function call(name, $$arguments) {
  let params = callParams(name, $$arguments);
  if (params !== undefined) {
    return request("tools/call", params).then(answerOf);
  } else {
    return Promise.resolve({
      ok: false,
      text: "The arguments were not valid JSON. Send them again as a JSON object."
    });
  }
}

let declarations = (function (tools) {
  return tools.map(tool => ({
    type: "function",
    function: {
      name: tool.name,
      description: tool.description,
      parameters: tool.schema,
    },
  }));
});

export {
  tools,
  call,
  declarations,
}
/* request Not a pure module */
