// Generated by ReScript, PLEASE EDIT WITH CARE


import { Marked } from "marked";

const messages = new Marked({
  gfm: true,
  breaks: true,
});
;

let toHtml = (function (source) {
  try {
    return messages.parse(source, { async: false });
  } catch (error) {
    // A message is not a document being typed: there is no author here to fix it, so
    // the fallback is the text as written rather than a rendering error nobody can
    // act on. Escaped, because it is about to be sanitised as HTML.
    return "<p>" + String(source)
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;") + "</p>";
  }
});

export {
  toHtml,
}
/*  Not a pure module */
