// Generated by ReScript, PLEASE EDIT WITH CARE

import * as AiSettings from "../core/AiSettings.res.mjs";

let controller = (function () { return new AbortController(); });

let signalOf = (function (controller) { return controller.signal; });

let abort = (function (controller) { controller.abort(); });

let send = (async function (url, key, model, messages, tools, onText, onThinking, signal) {
  const failure = message => ({ ok: false, error: message, text: "", calls: [], message: null });
  let response;
  try {
    const headers = { "Content-Type": "application/json" };
    // No key, no header: the local model authenticates nobody, and an empty bearer
    // token is a 401 waiting to happen at a provider that does.
    if (key) headers.Authorization = "Bearer " + key;
    response = await fetch(url, {
      method: "POST",
      headers,
      signal: signal || undefined,
      body: JSON.stringify({
        model,
        stream: true,
        messages,
        ...(tools.length ? { tools } : {}),
      }),
    });
  } catch (error) {
    if (error && error.name === "AbortError") return failure("");
    return failure(String((error && error.message) || error));
  }

  if (!response.ok || !response.body) {
    // The provider's own sentence, when it sent one: "model not found" and "incorrect
    // api key" are the two failures that actually happen, and both are actionable
    // only if they are repeated verbatim.
    let detail = "";
    try {
      const body = await response.text();
      const parsed = JSON.parse(body);
      detail = (parsed && parsed.error && (parsed.error.message || parsed.error)) || body;
    } catch (error) {
      detail = "";
    }
    return failure("HTTP " + response.status + (detail ? ": " + String(detail).slice(0, 400) : ""));
  }

  const reader = response.body.getReader();
  const decoder = new TextDecoder();
  let buffer = "";
  let text = "";
  const calls = [];

  const consume = payload => {
    if (payload === "[DONE]") return;
    let chunk;
    try {
      chunk = JSON.parse(payload);
    } catch (error) {
      return;
    }
    const choice = chunk.choices && chunk.choices[0];
    const delta = (choice && choice.delta) || {};
    if (delta.content) {
      text += delta.content;
      onText(delta.content);
    }
    // Two spellings of the same thing across providers, neither of them the answer.
    const thinking = delta.reasoning || delta.reasoning_content;
    if (thinking) onThinking(thinking);
    if (Array.isArray(delta.tool_calls)) {
      for (const fragment of delta.tool_calls) {
        const index = typeof fragment.index === "number" ? fragment.index : 0;
        if (!calls[index]) calls[index] = { id: "", name: "", arguments: "" };
        const slot = calls[index];
        if (fragment.id) slot.id = fragment.id;
        const fn = fragment.function || {};
        if (fn.name) slot.name += fn.name;
        if (fn.arguments) slot.arguments += fn.arguments;
      }
    }
  };

  try {
    for (;;) {
      const { done, value } = await reader.read();
      if (done) break;
      buffer += decoder.decode(value, { stream: true });
      // A chunk can end mid-line, so only whole lines are consumed and the tail
      // stays in the buffer for the next read.
      const lines = buffer.split("\n");
      buffer = lines.pop() || "";
      for (const line of lines) {
        const trimmed = line.trim();
        if (trimmed.startsWith("data:")) consume(trimmed.slice(5).trim());
      }
    }
  } catch (error) {
    // Stopping is not a failure: the person asked for it and already knows.
    if (error && error.name === "AbortError") return failure("");
    return failure(String((error && error.message) || error));
  }

  // The id is settled here, once, for both the calls handed to the caller and the
  // calls written into the message: a tool result is matched to its call by that id,
  // and a provider that streams none would otherwise get one spelling in the history
  // and another in the answer.
  const made = calls
    .filter(Boolean)
    .filter(call => call.name)
    .map((call, index) => ({ ...call, id: call.id || "call_" + index }));
  return {
    ok: true,
    error: "",
    text,
    calls: made,
    message: {
      role: "assistant",
      content: text,
      ...(made.length
        ? {
            tool_calls: made.map(call => ({
              id: call.id,
              type: "function",
              function: { name: call.name, arguments: call.arguments || "{}" },
            })),
          }
        : {}),
    },
  };
});

let sendNative = (async function (url, model, messages, tools, onText, onThinking, signal) {
  const failure = message => ({ ok: false, error: message, text: "", calls: [], message: null });
  let response;
  try {
    response = await fetch(url, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      signal: signal || undefined,
      body: JSON.stringify({
        model,
        stream: true,
        messages,
        ...(tools.length ? { tools } : {}),
      }),
    });
  } catch (error) {
    if (error && error.name === "AbortError") return failure("");
    return failure(String((error && error.message) || error));
  }

  if (!response.ok || !response.body) {
    let detail = "";
    try {
      const body = await response.text();
      const parsed = JSON.parse(body);
      detail = (parsed && parsed.error) || body;
    } catch (error) {
      detail = "";
    }
    return failure("HTTP " + response.status + (detail ? ": " + String(detail).slice(0, 400) : ""));
  }

  const reader = response.body.getReader();
  const decoder = new TextDecoder();
  let buffer = "";
  let text = "";
  const nativeCalls = [];

  const consume = payload => {
    let chunk;
    try {
      chunk = JSON.parse(payload);
    } catch (error) {
      return;
    }
    const message = chunk.message || {};
    if (message.content) {
      text += message.content;
      onText(message.content);
    }
    if (message.thinking) onThinking(message.thinking);
    if (Array.isArray(message.tool_calls)) nativeCalls.push(...message.tool_calls);
  };

  try {
    for (;;) {
      const { done, value } = await reader.read();
      if (done) break;
      buffer += decoder.decode(value, { stream: true });
      const lines = buffer.split("\n");
      buffer = lines.pop() || "";
      for (const line of lines) {
        const trimmed = line.trim();
        if (trimmed) consume(trimmed);
      }
    }
  } catch (error) {
    if (error && error.name === "AbortError") return failure("");
    return failure(String((error && error.message) || error));
  }
  if (buffer.trim()) consume(buffer.trim());

  const made = nativeCalls
    .filter(call => call && call.function && call.function.name)
    .map((call, index) => ({
      id: call.id || "call_" + index,
      name: call.function.name,
      arguments: JSON.stringify(call.function.arguments || {}),
    }));
  return {
    ok: true,
    error: "",
    text,
    calls: made,
    message: {
      role: "assistant",
      content: text,
      ...(nativeCalls.length ? { tool_calls: nativeCalls } : {}),
    },
  };
});

let toolMessageRaw = (function (native, id, name, text) {
  return native
    ? { role: "tool", tool_name: name, content: text }
    : { role: "tool", tool_call_id: id, content: text };
});

function toolMessage(settings, id, name, text) {
  return toolMessageRaw(AiSettings.isLocal(settings), id, name, text);
}

function complete(settings, messages, tools, onText, onThinking, signal) {
  let normalized = AiSettings.normalize(settings);
  if (AiSettings.isLocal(settings)) {
    return sendNative(AiSettings.nativeChatUrl(settings), normalized.model, messages, tools, onText, onThinking, signal);
  } else {
    return send(AiSettings.completionsUrl(settings), normalized.key, normalized.model, messages, tools, onText, onThinking, signal);
  }
}

export {
  controller,
  signalOf,
  abort,
  toolMessage,
  complete,
}
/* send Not a pure module */
