// Generated by ReScript, PLEASE EDIT WITH CARE

import * as RowView from "../core/RowView.res.mjs";
import * as ReactiveStore from "./ReactiveStore.res.mjs";
import * as CollectionStore from "./CollectionStore.res.mjs";

let install = (function (read, storeSet, storeGet, valueOf) {
  // The binders answer from IndexedDB, which reports to nobody: there is no event
  // meaning "every view has caught up with that key". So the wait is a wait — the
  // change is announced first, so the views that listen for it do go and read again,
  // and a frame is given to the ones that repaint synchronously.
  const settle = () => new Promise((resolve) => {
    window.dispatchEvent(new Event("rn:data"));
    setTimeout(() => requestAnimationFrame(() => resolve()), 160);
  });

  // A canvas is pixels, and cloneNode copies the element without them: a chart
  // photographed this way would print as a blank rectangle, which looks like the
  // chart is broken rather than like the copy is. So each one is replaced by the
  // picture it is currently showing.
  const freezeCanvases = (original, copy) => {
    const sources = original.querySelectorAll("canvas");
    const copies = copy.querySelectorAll("canvas");
    for (let i = 0; i < copies.length && i < sources.length; i++) {
      try {
        const picture = document.createElement("img");
        picture.src = sources[i].toDataURL("image/png");
        picture.className = "rn-print-canvas";
        picture.alt = "";
        copies[i].replaceWith(picture);
      } catch {
        // A tainted canvas refuses toDataURL. Nothing to photograph, and nothing
        // worth throwing away the whole print for.
      }
    }
  };

  const printing = (done) => {
    const off = () => {
      done();
      window.removeEventListener("afterprint", off);
    };
    window.addEventListener("afterprint", off);
    window.print();
  };

  return function (container, app, labels) {
    container.querySelectorAll("[data-rn-print]").forEach((button) => {
      // The default is words, so it is written here and not by the renderer, which is
      // installed once with no language. An author's own label is already in place.
      if (button.textContent.trim() === "") {
        button.textContent = button.hasAttribute("data-rn-print-repeat")
          ? labels.printEach
          : labels.print;
      }
      button.addEventListener("click", () => {
        const id = button.getAttribute("data-rn-print");
        const target = container.querySelector('[id="' + CSS.escape(id) + '"]');
        if (!target) return;

        const sheets = document.createElement("div");
        sheets.className = "rn-print-sheets";
        if (button.hasAttribute("data-rn-print-landscape")) {
          sheets.classList.add("rn-print-landscape");
        }
        const photograph = () => {
          const sheet = document.createElement("div");
          sheet.className = "rn-print-sheet";
          const copy = target.cloneNode(true);
          // Two ids for one section would be one too many, and the copy is the one
          // nothing may find: every binder addresses its work by id.
          copy.removeAttribute("id");
          copy.querySelectorAll("[id]").forEach((node) => node.removeAttribute("id"));
          freezeCanvases(target, copy);
          sheet.appendChild(copy);
          sheets.appendChild(sheet);
        };
        const paper = () => {
          document.body.appendChild(sheets);
          document.body.classList.add("rn-print-mode");
          printing(() => {
            document.body.classList.remove("rn-print-mode");
            sheets.remove();
            button.disabled = false;
          });
        };

        const path = button.getAttribute("data-rn-print-repeat");
        const key = button.getAttribute("data-rn-print-key") || "";
        if (!path || key === "" || !app) {
          photograph();
          paper();
          return;
        }

        // The id is what a reference stores, so it is what the key holds unless the
        // author names another field — and a form that filters by #key is reading the
        // same thing a ::input{type="ref"} would have written.
        const field = button.getAttribute("data-rn-print-field") || "";
        const held = storeGet(key);
        const before = held === null || held === undefined ? "" : String(held);
        button.disabled = true;

        read(app, path)
          .then(async (collection) => {
            for (const record of collection.records) {
              storeSet(key, field === "" ? record.id : valueOf(record, field));
              await settle();
              photograph();
            }
            // Back to where it was before anybody pressed anything: what is on screen
            // when the dialog closes has to be what was on screen when it opened.
            storeSet(key, before);
            await settle();
            paper();
          })
          .catch(() => {
            sheets.remove();
            button.disabled = false;
          });
      });
    });
  };
});

let binder = install(CollectionStore.read, ReactiveStore.set, ReactiveStore.get, RowView.valueOf);

function bind(container, app, labels) {
  binder(container, app, labels);
}

export {
  bind,
}
/* binder Not a pure module */
