// Generated by ReScript, PLEASE EDIT WITH CARE


let runWatched = (function (code, data, packages, writes, params, ceiling, onProgress, onPartial) {
  const state = globalThis.__rnPython || (globalThis.__rnPython = {
    worker: null,
    waiting: new Map(),
    next: 0,
    queue: Promise.resolve(),
  });

  // Every pending run dies with the worker, and each of them has a reader waiting for
  // an answer. Written once because it is needed on three roads out: the worker
  // failing, the ceiling, and the reader pressing Stop.
  const abandon = (message) => {
    for (const entry of state.waiting.values()) {
      // No rows: a run that failed or overran its ceiling has no answer, and writing
      // half of one over a collection would be worse than writing none. A *stop* is
      // the one case that keeps the partial, and it settles its own runs below.
      entry.settle({ rows: "", output: "", value: "", images: [], error: message });
    }
    state.waiting.clear();
  };

  const start = () => {
    if (state.worker) return state.worker;
    // The URL form, so the bundler emits the worker as its own file and the browser
    // fetches it from this origin — a blob worker would need the policy opened for
    // blob: scripts and would still have to fetch the runtime.
    const worker = new Worker(new URL("./python.worker.js", import.meta.url), { type: "module" });
    worker.onmessage = (event) => {
      const entry = state.waiting.get(event.data.id);
      if (!entry) return;
      // Progress and partial arrive DURING a run. They are the run talking, not the
      // run finishing, so they are handed on and nothing is settled — settling here
      // would end the run at its first print of a percentage.
      if (event.data.kind === "progress") {
        entry.onProgress(event.data.done || 0, event.data.total || 0, event.data.message || "");
        return;
      }
      if (event.data.kind === "partial") {
        entry.partial = event.data.rows || "";
        entry.onPartial(entry.partial);
        return;
      }
      state.waiting.delete(event.data.id);
      entry.settle({
        rows: event.data.rows || "",
        output: event.data.output || "",
        value: event.data.value || "",
        images: event.data.images || [],
        error: event.data.error || "",
      });
    };
    worker.onerror = (event) => {
      abandon(String(event.message || "the Python worker stopped"));
      state.worker = null;
    };
    state.worker = worker;
    return worker;
  };

  // The ceiling, then the worker is killed. Generous because a first run legitimately
  // spends a while fetching the runtime and packages — but an accidental infinite
  // loop never posts back, onerror does not fire for a busy loop, and without a
  // ceiling it wedged every future run in the session behind a promise that could not
  // settle, with a core pegged for as long as the tab lived.
  //
  // Two minutes is the ceiling of a run nobody asked for. A manual block raises it,
  // because a person asked for that one, is watching the bar, and can stop it.
  const send = () => new Promise((resolve) => {
    const id = (state.next += 1);
    const timer = setTimeout(() => {
      if (!state.waiting.has(id)) return;
      if (state.worker) state.worker.terminate();
      state.worker = null;
      abandon("The code ran past its time limit and was stopped.");
    }, ceiling);
    state.waiting.set(id, {
      settle: (outcome) => {
        clearTimeout(timer);
        resolve(outcome);
      },
      onProgress,
      onPartial,
      partial: "",
    });
    start().postMessage({ id, code, data: JSON.parse(data), packages, writes, params: JSON.parse(params) });
  });

  // Chained onto whatever is already running, and the chain never rejects: a failed
  // run answers with its error like any other outcome.
  const answer = state.queue.then(send, send);
  state.queue = answer.then(() => undefined, () => undefined);
  return answer;
});

let stop = (function () {
  const state = globalThis.__rnPython;
  if (!state) return;
  if (state.worker) state.worker.terminate();
  state.worker = null;
  // The empty message is what tells the settler this was a stop and not a failure:
  // a stop answers with the rows the run had already published, and no error.
  for (const entry of state.waiting.values()) {
    entry.settle({ rows: entry.partial, output: "", value: "", images: [], error: "" });
  }
  state.waiting.clear();
});

function run(code, data, packages, writes) {
  return runWatched(code, data, packages, writes, "{}", 120000, (param, param$1, param$2) => {}, param => {});
}

export {
  runWatched,
  stop,
  run,
}
/* No side effect */
