// Generated by ReScript, PLEASE EDIT WITH CARE

import * as SafeUrl from "../core/SafeUrl.res.mjs";

let collectAnchors = (function (container) { return Array.from(container.querySelectorAll("a[href]")); });

let readHref = (function (anchor) { return anchor.getAttribute("href") || ""; });

let allowHref = (function (anchor, href) {
  anchor.setAttribute("href", href);
  anchor.setAttribute("target", "_blank");
  anchor.setAttribute("rel", "noopener noreferrer");
});

let dropHref = (function (anchor, reason) {
  anchor.removeAttribute("href");
  anchor.setAttribute("title", reason);
  anchor.className = (anchor.className ? anchor.className + " " : "") + "rn-error";
});

function harden(container, removed) {
  collectAnchors(container).forEach(anchor => {
    let url = SafeUrl.parse(readHref(anchor));
    if (url.TAG === "Ok") {
      return allowHref(anchor, SafeUrl.toString(url._0));
    } else {
      return dropHref(anchor, removed);
    }
  });
}

let wrapWideTables = (function (container, label) {
  container.querySelectorAll("table").forEach((table) => {
    if (table.parentElement && table.parentElement.classList.contains("rn-scroll-x")) return;
    const wrapper = document.createElement("div");
    wrapper.className = "rn-scroll-x";
    wrapper.setAttribute("tabindex", "0");
    wrapper.setAttribute("role", "region");
    wrapper.setAttribute("aria-label", label);
    table.replaceWith(wrapper);
    wrapper.appendChild(table);
  });
});

export {
  harden,
  wrapWideTables,
}
/* SafeUrl Not a pure module */
