// Generated by ReScript, PLEASE EDIT WITH CARE


let register = (function () {
  if (!import.meta.env.PROD) return;
  if (!("serviceWorker" in navigator)) return;
  window.addEventListener("load", () => {
    navigator.serviceWorker.register("/sw.js", { scope: "/" }).catch(() => {});
  });
});

export {
  register,
}
/* No side effect */
