// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Idb from "./Idb.res.mjs";

let storageKey = "account";

let encode = (function (session) {
  return JSON.stringify({
    v: 1,
    token: session.token,
    userId: session.userId,
    username: session.username,
    pub: session.pub,
    priv: session.priv,
  });
});

let decode = (function (text) {
  let parsed;
  try {
    parsed = JSON.parse(text);
  } catch {
    return undefined;
  }
  if (!parsed || typeof parsed !== "object" || parsed.v !== 1) return undefined;
  for (const field of ["token", "userId", "username", "pub", "priv"]) {
    if (typeof parsed[field] !== "string" || parsed[field] === "") return undefined;
  }
  return {
    token: parsed.token,
    userId: parsed.userId,
    username: parsed.username,
    pub: parsed.pub,
    priv: parsed.priv,
  };
});

function save(session) {
  return Idb.set(storageKey, encode(session));
}

async function load() {
  let stored = await Idb.get(storageKey);
  if (stored == null) {
    return;
  } else {
    return decode(stored);
  }
}

function clear() {
  return Idb.remove(storageKey);
}

export {
  save,
  load,
  clear,
}
/* Idb Not a pure module */
