// Generated by ReScript, PLEASE EDIT WITH CARE


let encode = (async function (source) {
  const bytes = new TextEncoder().encode(source);
  const characters = (data) => {
    let binary = "";
    for (const byte of data) binary += String.fromCharCode(byte);
    return btoa(binary).replaceAll("+", "-").replaceAll("/", "_").replace(/=+$/, "");
  };
  if (typeof CompressionStream !== "function") return "u" + characters(bytes);
  try {
    const stream = new Blob([bytes]).stream().pipeThrough(new CompressionStream("gzip"));
    const packed = new Uint8Array(await new Response(stream).arrayBuffer());
    return "z" + characters(packed);
  } catch (error) {
    return "u" + characters(bytes);
  }
});

let decode = (async function (payload) {
  try {
    const how = payload.slice(0, 1);
    const body = payload.slice(1).replaceAll("-", "+").replaceAll("_", "/");
    const binary = atob(body);
    const bytes = new Uint8Array(binary.length);
    for (let index = 0; index < binary.length; index += 1) bytes[index] = binary.charCodeAt(index);
    if (how === "u") return new TextDecoder().decode(bytes);
    if (how !== "z") return undefined;
    if (typeof DecompressionStream !== "function") return undefined;
    const stream = new Blob([bytes]).stream().pipeThrough(new DecompressionStream("gzip"));
    return await new Response(stream).text();
  } catch (error) {
    return undefined;
  }
});

export {
  encode,
  decode,
}
/* encode Not a pure module */
