// Generated by ReScript, PLEASE EDIT WITH CARE


let available = (function () { return typeof navigator !== "undefined" && typeof navigator.share === "function"; });

let share = (function (title, text, url) {
  try {
    return navigator.share({ title, text, url }).then(() => true, () => false);
  } catch (error) {
    return Promise.resolve(false);
  }
});

function mailto(subject, body) {
  return "mailto:?subject=" + encodeURIComponent(subject) + "&body=" + encodeURIComponent(body);
}

export {
  available,
  share,
  mailto,
}
/* No side effect */
