// Generated by ReScript, PLEASE EDIT WITH CARE


let create = (async function (payload) {
  try {
    const response = await fetch("/pb/api/collections/shares/records", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ payload }),
    });
    if (!response.ok) return undefined;
    const record = await response.json();
    return typeof record.id === "string" && record.id !== "" ? record.id : undefined;
  } catch (error) {
    return undefined;
  }
});

let fetchPayload = (async function (id) {
  try {
    const response = await fetch(
      "/pb/api/collections/shares/records/" + encodeURIComponent(id)
    );
    if (!response.ok) return undefined;
    const record = await response.json();
    return typeof record.payload === "string" && record.payload !== ""
      ? record.payload
      : undefined;
  } catch (error) {
    return undefined;
  }
});

export {
  create,
  fetchPayload,
}
/* create Not a pure module */
