// Generated by ReScript, PLEASE EDIT WITH CARE


let wrapForMember = (async function (pub, secret) {
  const recipient = await crypto.subtle.importKey(
    "jwk", JSON.parse(pub), { name: "ECDH", namedCurve: "P-256" }, false, []
  );
  const ephemeral = await crypto.subtle.generateKey(
    { name: "ECDH", namedCurve: "P-256" }, false, ["deriveKey"]
  );
  const seal = await crypto.subtle.deriveKey(
    { name: "ECDH", public: recipient },
    ephemeral.privateKey,
    { name: "AES-GCM", length: 256 },
    false,
    ["encrypt"]
  );
  const iv = crypto.getRandomValues(new Uint8Array(12));
  const sealed = new Uint8Array(
    await crypto.subtle.encrypt({ name: "AES-GCM", iv }, seal, new TextEncoder().encode(secret))
  );
  const joined = new Uint8Array(iv.length + sealed.length);
  joined.set(iv);
  joined.set(sealed, iv.length);
  let binary = "";
  for (const byte of joined) binary += String.fromCharCode(byte);
  const ct = btoa(binary).replaceAll("+", "-").replaceAll("/", "_").replace(/=+$/, "");
  const epk = await crypto.subtle.exportKey("jwk", ephemeral.publicKey);
  return JSON.stringify({ epk, ct });
});

let unwrapAsMember = (async function (priv, payload) {
  try {
    const parsed = JSON.parse(payload);
    const ephemeral = await crypto.subtle.importKey(
      "jwk", parsed.epk, { name: "ECDH", namedCurve: "P-256" }, false, []
    );
    const own = await crypto.subtle.importKey(
      "jwk", JSON.parse(priv), { name: "ECDH", namedCurve: "P-256" }, false, ["deriveKey"]
    );
    const seal = await crypto.subtle.deriveKey(
      { name: "ECDH", public: ephemeral },
      own,
      { name: "AES-GCM", length: 256 },
      false,
      ["decrypt"]
    );
    const bytesOf = (encoded) => {
      const binary = atob(encoded.replaceAll("-", "+").replaceAll("_", "/"));
      const bytes = new Uint8Array(binary.length);
      for (let index = 0; index < binary.length; index += 1) bytes[index] = binary.charCodeAt(index);
      return bytes;
    };
    const joined = bytesOf(parsed.ct);
    const opened = await crypto.subtle.decrypt(
      { name: "AES-GCM", iv: joined.slice(0, 12) }, seal, joined.slice(12)
    );
    return new TextDecoder().decode(opened);
  } catch (error) {
    return undefined;
  }
});

export {
  wrapForMember,
  unwrapAsMember,
}
/* wrapForMember Not a pure module */
