// Generated by ReScript, PLEASE EDIT WITH CARE


let createSpace = (async function (token, owner) {
  try {
    const response = await fetch("/pb/api/collections/spaces/records", {
      method: "POST",
      headers: { "Content-Type": "application/json", Authorization: token },
      body: JSON.stringify({ owner, epoch: 1 }),
    });
    if (!response.ok) return undefined;
    const record = await response.json();
    return typeof record.id === "string" && record.id !== "" ? record.id : undefined;
  } catch (error) {
    return undefined;
  }
});

let getSpace = (async function (token, id) {
  try {
    const response = await fetch(
      "/pb/api/collections/spaces/records/" + encodeURIComponent(id),
      { headers: { Authorization: token } }
    );
    if (!response.ok) return undefined;
    const record = await response.json();
    return {
      id: String(record.id || ""),
      owner: String(record.owner || ""),
      epoch: Number(record.epoch || 1),
      snapshot: String(record.snapshot || ""),
      snapshotUntil: String(record.snapshotUntil || ""),
    };
  } catch (error) {
    return undefined;
  }
});

let updateSpace = (async function (token, id, body) {
  try {
    const response = await fetch(
      "/pb/api/collections/spaces/records/" + encodeURIComponent(id),
      {
        method: "PATCH",
        headers: { "Content-Type": "application/json", Authorization: token },
        body,
      }
    );
    return response.ok;
  } catch (error) {
    return false;
  }
});

let createMember = (async function (token, space, user, role, label, pub, keys, invite) {
  try {
    const body = { space, user, role, label, pub: JSON.parse(pub), keys: JSON.parse(keys) };
    if (invite !== "") body.invite = invite;
    const response = await fetch("/pb/api/collections/members/records", {
      method: "POST",
      headers: { "Content-Type": "application/json", Authorization: token },
      body: JSON.stringify(body),
    });
    return response.ok;
  } catch (error) {
    return false;
  }
});

let listMembers = (async function (token, space) {
  try {
    const filter = encodeURIComponent("space = '" + space + "'");
    const response = await fetch(
      "/pb/api/collections/members/records?perPage=200&filter=" + filter,
      { headers: { Authorization: token } }
    );
    if (!response.ok) return [];
    const answer = await response.json();
    return (answer.items || []).map((record) => ({
      id: String(record.id || ""),
      user: String(record.user || ""),
      role: String(record.role || ""),
      label: String(record.label || ""),
      pub: JSON.stringify(record.pub || null),
      keys: JSON.stringify(record.keys || null),
    }));
  } catch (error) {
    return [];
  }
});

let updateMemberKeys = (async function (token, id, keys) {
  try {
    const response = await fetch(
      "/pb/api/collections/members/records/" + encodeURIComponent(id),
      {
        method: "PATCH",
        headers: { "Content-Type": "application/json", Authorization: token },
        body: JSON.stringify({ keys: JSON.parse(keys) }),
      }
    );
    return response.ok;
  } catch (error) {
    return false;
  }
});

let deleteMember = (async function (token, id) {
  try {
    const response = await fetch(
      "/pb/api/collections/members/records/" + encodeURIComponent(id),
      { method: "DELETE", headers: { Authorization: token } }
    );
    return response.ok;
  } catch (error) {
    return false;
  }
});

let createInvite = (async function (token, space, role, sealedKey, epoch) {
  try {
    const response = await fetch("/pb/api/collections/invites/records", {
      method: "POST",
      headers: { "Content-Type": "application/json", Authorization: token },
      body: JSON.stringify({ space, role, sealedKey, epoch }),
    });
    if (!response.ok) return undefined;
    const record = await response.json();
    return typeof record.id === "string" && record.id !== "" ? record.id : undefined;
  } catch (error) {
    return undefined;
  }
});

let getInvite = (async function (token, id) {
  try {
    const response = await fetch(
      "/pb/api/collections/invites/records/" + encodeURIComponent(id),
      { headers: { Authorization: token } }
    );
    if (!response.ok) return undefined;
    const record = await response.json();
    return {
      id: String(record.id || ""),
      space: String(record.space || ""),
      role: String(record.role || ""),
      sealedKey: String(record.sealedKey || ""),
      epoch: Number(record.epoch || 1),
    };
  } catch (error) {
    return undefined;
  }
});

let createChange = (async function (token, space, author, epoch, payload) {
  try {
    const response = await fetch("/pb/api/collections/changes/records", {
      method: "POST",
      headers: { "Content-Type": "application/json", Authorization: token },
      body: JSON.stringify({ space, author, epoch, payload }),
    });
    return response.ok;
  } catch (error) {
    return false;
  }
});

let listChangesSince = (async function (token, space, since) {
  try {
    const collected = [];
    let page = 1;
    while (true) {
      const filter =
        since === ""
          ? "space = '" + space + "'"
          : "space = '" + space + "' && created > '" + since + "'";
      const response = await fetch(
        "/pb/api/collections/changes/records?sort=created,id&perPage=200&page=" +
          page + "&filter=" + encodeURIComponent(filter),
        { headers: { Authorization: token } }
      );
      if (!response.ok) return undefined;
      const answer = await response.json();
      const items = (answer.items || []).map((record) => ({
        id: String(record.id || ""),
        epoch: Number(record.epoch || 1),
        payload: String(record.payload || ""),
        created: String(record.created || ""),
      }));
      collected.push(...items);
      if (page >= (answer.totalPages || 1)) return collected;
      page += 1;
    }
  } catch (error) {
    return undefined;
  }
});

export {
  createSpace,
  getSpace,
  updateSpace,
  createMember,
  listMembers,
  updateMemberKeys,
  deleteMember,
  createInvite,
  getInvite,
  createChange,
  listChangesSince,
}
/* createSpace Not a pure module */
