// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Idb from "./Idb.res.mjs";

function linkKey(app) {
  return "space:" + app;
}

function docKey(app) {
  return "spacedoc:" + app;
}

function queueKey(app) {
  return "spacequeue:" + app;
}

let encodeLink = (function (link) {
  return JSON.stringify({
    v: 1,
    spaceId: link.spaceId,
    role: link.role,
    keys: link.keys,
    cursor: link.cursor,
    canonical: link.canonical,
  });
});

let decodeLink = (function (text) {
  let parsed;
  try {
    parsed = JSON.parse(text);
  } catch {
    return undefined;
  }
  if (!parsed || typeof parsed !== "object" || parsed.v !== 1) return undefined;
  if (typeof parsed.spaceId !== "string" || parsed.spaceId === "") return undefined;
  return {
    spaceId: parsed.spaceId,
    role: typeof parsed.role === "string" ? parsed.role : "reader",
    keys: typeof parsed.keys === "string" ? parsed.keys : "{}",
    cursor: typeof parsed.cursor === "string" ? parsed.cursor : "",
    canonical: typeof parsed.canonical === "string" ? parsed.canonical : "",
  };
});

let keyForEpoch = (function (link, epoch) {
  try {
    const keys = JSON.parse(link.keys);
    const found = keys[String(epoch)];
    return typeof found === "string" && found !== "" ? found : undefined;
  } catch {
    return undefined;
  }
});

let withEpochKey = (function (link, epoch, key) {
  let keys;
  try {
    keys = JSON.parse(link.keys);
  } catch {
    keys = {};
  }
  keys[String(epoch)] = key;
  return {
    spaceId: link.spaceId,
    role: link.role,
    keys: JSON.stringify(keys),
    cursor: link.cursor,
    canonical: link.canonical,
  };
});

function saveLink(app, link) {
  return Idb.set("space:" + app, encodeLink(link));
}

async function loadLink(app) {
  let stored = await Idb.get("space:" + app);
  if (stored == null) {
    return;
  } else {
    return decodeLink(stored);
  }
}

function saveDoc(app, encoded) {
  return Idb.set("spacedoc:" + app, encoded);
}

async function loadDoc(app) {
  let stored = await Idb.get("spacedoc:" + app);
  if ((stored == null) || stored === "") {
    return;
  } else {
    return stored;
  }
}

let encodeQueue = (function (entries) {
  return JSON.stringify(entries.map(([epoch, payload]) => ({ epoch, payload })));
});

let decodeQueue = (function (text) {
  try {
    const parsed = JSON.parse(text);
    if (!Array.isArray(parsed)) return [];
    return parsed
      .filter((entry) => entry && typeof entry.payload === "string")
      .map((entry) => [Number(entry.epoch || 1), entry.payload]);
  } catch {
    return [];
  }
});

async function loadQueue(app) {
  let stored = await Idb.get("spacequeue:" + app);
  if (stored == null) {
    if (stored === null) {
      return [];
    } else {
      return [];
    }
  } else {
    return decodeQueue(stored);
  }
}

function saveQueue(app, entries) {
  return Idb.set("spacequeue:" + app, encodeQueue(entries));
}

async function clear(app) {
  await Idb.remove("space:" + app);
  await Idb.remove("spacedoc:" + app);
  return await Idb.remove("spacequeue:" + app);
}

async function rename(from, to_) {
  let carry = async make => {
    let stored = await Idb.get(make(from));
    if (stored == null) {
      return;
    }
    await Idb.set(make(to_), stored);
    return await Idb.remove(make(from));
  };
  await carry(linkKey);
  await carry(docKey);
  return await carry(queueKey);
}

export {
  keyForEpoch,
  withEpochKey,
  saveLink,
  loadLink,
  saveDoc,
  loadDoc,
  loadQueue,
  saveQueue,
  clear,
  rename,
}
/* Idb Not a pure module */
