// Generated by ReScript, PLEASE EDIT WITH CARE


let ensureLoaded = (function () {
  if (globalThis.__rnSpectrumLoading) return;
  globalThis.__rnSpectrumLoading = import("@spectrum-web-components/bundle/elements.js").catch(
    (error) => console.warn("[spectrum] component bundle failed to load:", error)
  );
});

export {
  ensureLoaded,
}
/* No side effect */
