// Generated by ReScript, PLEASE EDIT WITH CARE

import * as AppId from "../core/AppId.res.mjs";
import * as AppFile from "../core/AppFile.res.mjs";
import * as SpaceLink from "../core/SpaceLink.res.mjs";
import * as SpaceStore from "./SpaceStore.res.mjs";
import * as AppDocument from "../core/AppDocument.res.mjs";
import * as ShareCrypto from "./ShareCrypto.res.mjs";
import * as SpaceCrypto from "./SpaceCrypto.res.mjs";
import * as SpaceServer from "./SpaceServer.res.mjs";
import * as Stdlib_Dict from "@rescript/runtime/lib/es6/Stdlib_Dict.js";
import * as DerivedPaths from "./DerivedPaths.res.mjs";
import * as AutomergeImpl from "./AutomergeImpl.res.mjs";
import * as DocumentStore from "./DocumentStore.res.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Stdlib_Promise from "@rescript/runtime/lib/es6/Stdlib_Promise.js";
import * as CollectionStore from "./CollectionStore.res.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

let active = {};

let announceData = (function () {
  globalThis.dispatchEvent(new Event("rn:data"));
});

let origin = (function () {
  return location.origin;
});

let buildSnapshot = (function (source, collections) {
  const held = {};
  for (const [path, collection] of collections) {
    const rows = {};
    for (const record of collection.records) {
      const fields = {};
      for (const field of record.fields) fields[field.name] = field.value;
      rows[record.id] = fields;
    }
    held[path] = rows;
  }
  return JSON.stringify({ source, collections: held });
});

let parseSnapshot = (function (text) {
  let parsed;
  try {
    parsed = JSON.parse(text);
  } catch {
    parsed = {};
  }
  const collections = [];
  for (const [path, rows] of Object.entries(parsed.collections || {})) {
    const records = [];
    for (const [id, fields] of Object.entries(rows || {})) {
      records.push({
        id,
        fields: Object.entries(fields || {}).map(([name, value]) => ({
          name,
          value: String(value),
        })),
      });
    }
    collections.push([path, { records }]);
  }
  return { source: typeof parsed.source === "string" ? parsed.source : "", collections };
});

let currentEpoch = (function (link) {
  let highest = 1;
  try {
    for (const epoch of Object.keys(JSON.parse(link.keys))) {
      const parsed = Number(epoch);
      if (parsed > highest) highest = parsed;
    }
  } catch {}
  return highest;
});

let singleKeyJson = (function (epoch, value) {
  const keys = {};
  keys[String(epoch)] = value;
  return JSON.stringify(keys);
});

let addKeyJson = (function (keys, epoch, value) {
  let parsed;
  try {
    parsed = JSON.parse(keys);
  } catch {
    parsed = {};
  }
  parsed[String(epoch)] = value;
  return JSON.stringify(parsed);
});

function toLocalSource(link, app, source) {
  if (link.canonical === "" || link.canonical === app) {
    return source;
  } else {
    return AppDocument.withId(source, app);
  }
}

function toCanonicalSource(link, app, source) {
  if (link.canonical === "" || link.canonical === app) {
    return source;
  } else {
    return AppDocument.withId(source, link.canonical);
  }
}

async function materializeToLocal(app, state) {
  let parsed = parseSnapshot(AutomergeImpl.materialize(app));
  state.applying = true;
  let held = await CollectionStore.paths(app);
  let carried = parsed.collections.map(param => param[0]);
  let derived = await DerivedPaths.list(app);
  await Promise.all(held.filter(path => {
    if (carried.includes(path)) {
      return false;
    } else {
      return !derived.includes(path);
    }
  }).map(path => CollectionStore.remove(app, path)));
  await CollectionStore.importAll(app, parsed.collections);
  if (parsed.source !== "") {
    let localSource = toLocalSource(state.link, app, parsed.source);
    let stored = await DocumentStore.load(app);
    let exit = 0;
    if (stored === undefined || stored !== localSource) {
      exit = 1;
    }
    if (exit === 1) {
      await DocumentStore.save(app, localSource);
      state.callbacks.onDocument(localSource);
    }
  }
  state.applying = false;
  return announceData();
}

async function pullOnce(app, state) {
  let token = state.session.token;
  let changes = await SpaceServer.listChangesSince(token, state.link.spaceId, state.link.cursor);
  if (changes === undefined) {
    return;
  }
  if (changes.length === 0) {
    return;
  }
  let opened = [];
  for (let index = 0, index_finish = changes.length; index < index_finish; ++index) {
    let change = changes[index];
    let key = SpaceStore.keyForEpoch(state.link, change.epoch);
    if (key !== undefined) {
      let decoded = await ShareCrypto.decrypt(key, change.payload);
      if (decoded !== undefined) {
        opened.push(decoded);
      }
    }
  }
  let moved = AutomergeImpl.applyRemote(app, opened);
  let last = changes.at(-1);
  if (last !== undefined) {
    let init = state.link;
    state.link = {
      spaceId: init.spaceId,
      role: init.role,
      keys: init.keys,
      cursor: last.created,
      canonical: init.canonical
    };
    await SpaceStore.saveLink(app, state.link);
  }
  if (moved) {
    await SpaceStore.saveDoc(app, AutomergeImpl.save(app));
    return await materializeToLocal(app, state);
  }
}

async function catchUp(app, state) {
  let token = state.session.token;
  let space = await SpaceServer.getSpace(token, state.link.spaceId);
  if (space === undefined) {
    return;
  }
  if (!(space.snapshotUntil !== "" && space.snapshotUntil > state.link.cursor)) {
    return;
  }
  let key = SpaceStore.keyForEpoch(state.link, space.epoch);
  if (key === undefined) {
    return;
  }
  let saved = await ShareCrypto.decrypt(key, space.snapshot);
  if (saved === undefined) {
    return;
  }
  AutomergeImpl.mergeSaved(app, saved);
  let init = state.link;
  state.link = {
    spaceId: init.spaceId,
    role: init.role,
    keys: init.keys,
    cursor: space.snapshotUntil,
    canonical: init.canonical
  };
  await SpaceStore.saveLink(app, state.link);
  await SpaceStore.saveDoc(app, AutomergeImpl.save(app));
  return await materializeToLocal(app, state);
}

async function flushQueue(app, state) {
  let pending = await SpaceStore.loadQueue(app);
  if (pending.length === 0) {
    return;
  }
  let remaining = [];
  for (let index = 0, index_finish = pending.length; index < index_finish; ++index) {
    let match = pending[index];
    let payload = match[1];
    let epoch = match[0];
    let sent = await SpaceServer.createChange(state.session.token, state.link.spaceId, state.session.userId, epoch, payload);
    if (!sent) {
      remaining.push([
        epoch,
        payload
      ]);
    }
  }
  return await SpaceStore.saveQueue(app, remaining);
}

async function pushLocal(app, state) {
  let text = await DocumentStore.load(app);
  let source = text !== undefined ? toCanonicalSource(state.link, app, text) : "";
  let derived = await DerivedPaths.list(app);
  let collections = (await CollectionStore.exportAll(app)).filter(param => !derived.includes(param[0]));
  let snapshot = buildSnapshot(source, collections);
  let change = AutomergeImpl.applyLocal(app, snapshot);
  if (change === undefined) {
    return;
  }
  await SpaceStore.saveDoc(app, AutomergeImpl.save(app));
  if (state.link.role === "reader") {
    return;
  }
  let epoch = currentEpoch(state.link);
  let key = SpaceStore.keyForEpoch(state.link, epoch);
  if (key === undefined) {
    return;
  }
  let sealed = await ShareCrypto.encrypt(key, change);
  let sent = await SpaceServer.createChange(state.session.token, state.link.spaceId, state.session.userId, epoch, sealed);
  if (sent) {
    return;
  }
  let pending = await SpaceStore.loadQueue(app);
  pending.push([
    epoch,
    sealed
  ]);
  return await SpaceStore.saveQueue(app, pending);
}

function cycle(app, state) {
  let task = async () => {
    await catchUp(app, state);
    await pullOnce(app, state);
    await flushQueue(app, state);
    return await pushLocal(app, state);
  };
  let next = state.chain.then(() => {
    if (state.stopped) {
      return Promise.resolve();
    } else {
      return Stdlib_Promise.$$catch(task(), param => Promise.resolve());
    }
  });
  state.chain = next;
  return next;
}

let subscribe = (function (token, onPing) {
  let source = null;
  let stopped = false;
  let retry = 1000;
  const connect = () => {
    if (stopped) return;
    try {
      source = new EventSource("/pb/api/realtime");
    } catch (error) {
      return;
    }
    source.addEventListener("PB_CONNECT", (event) => {
      let clientId = "";
      try {
        clientId = JSON.parse(event.data).clientId;
      } catch {
        clientId = event.lastEventId || "";
      }
      retry = 1000;
      fetch("/pb/api/realtime", {
        method: "POST",
        headers: { "Content-Type": "application/json", Authorization: token },
        body: JSON.stringify({ clientId, subscriptions: ["changes"] }),
      }).catch(() => {});
    });
    source.addEventListener("changes", () => onPing());
    source.onerror = () => {
      if (source) source.close();
      if (!stopped) {
        setTimeout(connect, retry);
        retry = Math.min(retry * 2, 30000);
      }
    };
  };
  connect();
  return () => {
    stopped = true;
    if (source) source.close();
  };
});

function localChanged(app) {
  let state = active[app];
  if (state !== undefined && !state.applying) {
    let timer = state.pokeTimer;
    if (timer !== undefined) {
      clearTimeout(Primitive_option.valFromOption(timer));
    }
    state.pokeTimer = Primitive_option.some(setTimeout(() => {
      state.pokeTimer = undefined;
      cycle(app, state);
    }, 500));
    return;
  }
}

globalThis.addEventListener("rn:collection-write", (event) => {
  const app = event && event.detail && event.detail.app;
  if (typeof app === "string" && app !== "") localChanged(app);
})
;

function stop(app) {
  let state = active[app];
  if (state === undefined) {
    return;
  }
  state.stopped = true;
  let close = state.unsubscribe;
  if (close !== undefined) {
    close();
  }
  let timer = state.pokeTimer;
  if (timer !== undefined) {
    clearTimeout(Primitive_option.valFromOption(timer));
  }
  AutomergeImpl.close(app);
  Stdlib_Dict.$$delete(active, app);
}

async function start(app, session, onDocument) {
  stop(app);
  let link = await SpaceStore.loadLink(app);
  if (link === undefined) {
    return;
  }
  await AutomergeImpl.init();
  let saved = await SpaceStore.loadDoc(app);
  AutomergeImpl.open_(app, saved);
  let state = {
    link: link,
    session: session,
    stopped: false,
    applying: false,
    chain: Promise.resolve(),
    unsubscribe: undefined,
    pokeTimer: undefined,
    callbacks: {
      onDocument: onDocument
    }
  };
  active[app] = state;
  state.unsubscribe = subscribe(session.token, () => {
    let held = active[app];
    if (held !== undefined && !held.stopped) {
      cycle(app, held);
      return;
    }
  });
  return await cycle(app, state);
}

function isActive(app) {
  return Stdlib_Option.isSome(active[app]);
}

async function roleOf(app) {
  let state = active[app];
  if (state !== undefined) {
    return state.link.role;
  } else {
    return Stdlib_Option.map(await SpaceStore.loadLink(app), link => link.role);
  }
}

async function create(app, session) {
  let token = session.token;
  let spaceId = await SpaceServer.createSpace(token, session.userId);
  if (spaceId === undefined) {
    return false;
  }
  let spaceKey = await ShareCrypto.generateKey();
  let wrapped = await SpaceCrypto.wrapForMember(session.pub, spaceKey);
  let joined = await SpaceServer.createMember(token, spaceId, session.userId, "owner", session.username, session.pub, singleKeyJson(1, wrapped), "");
  if (!joined) {
    return false;
  }
  let link_keys = singleKeyJson(1, spaceKey);
  let link = {
    spaceId: spaceId,
    role: "owner",
    keys: link_keys,
    cursor: "",
    canonical: app
  };
  await SpaceStore.saveLink(app, link);
  return true;
}

async function invite(app, session, role) {
  let link = await SpaceStore.loadLink(app);
  if (link === undefined) {
    return;
  }
  let epoch = currentEpoch(link);
  let spaceKey = SpaceStore.keyForEpoch(link, epoch);
  if (spaceKey === undefined) {
    return;
  }
  let inviteKey = await ShareCrypto.generateKey();
  let sealedKey = await ShareCrypto.encrypt(inviteKey, spaceKey);
  let id = await SpaceServer.createInvite(session.token, link.spaceId, role, sealedKey, epoch);
  if (id !== undefined) {
    return SpaceLink.of_(origin(), id, inviteKey);
  }
}

let joinScratch = "@join";

async function join(inviteId, key, session, taken, fallback) {
  let token = session.token;
  let found = await SpaceServer.getInvite(token, inviteId);
  if (found === undefined) {
    return;
  }
  let spaceKey = await ShareCrypto.decrypt(key, found.sealedKey);
  if (spaceKey === undefined) {
    return;
  }
  let wrapped = await SpaceCrypto.wrapForMember(session.pub, spaceKey);
  let member = await SpaceServer.createMember(token, found.space, session.userId, found.role, session.username, session.pub, singleKeyJson(found.epoch, wrapped), inviteId);
  if (!member) {
    return;
  }
  let space = await SpaceServer.getSpace(token, found.space);
  if (space === undefined) {
    return;
  }
  if (space.epoch !== found.epoch) {
    let rows = await SpaceServer.listMembers(token, found.space);
    let own = rows.find(row => row.user === session.userId);
    if (own !== undefined) {
      await SpaceServer.deleteMember(token, own.id);
    }
    return;
  }
  await AutomergeImpl.init();
  AutomergeImpl.open_(joinScratch, undefined);
  let cursor = "";
  if (space.snapshotUntil !== "" && space.snapshot !== "") {
    let saved = await ShareCrypto.decrypt(spaceKey, space.snapshot);
    if (saved !== undefined) {
      AutomergeImpl.mergeSaved(joinScratch, saved);
      cursor = space.snapshotUntil;
    }
  }
  let changes = await SpaceServer.listChangesSince(token, found.space, cursor);
  if (changes !== undefined) {
    let opened = [];
    for (let index = 0, index_finish = changes.length; index < index_finish; ++index) {
      let change = changes[index];
      if (change.epoch === found.epoch) {
        let decoded = await ShareCrypto.decrypt(spaceKey, change.payload);
        if (decoded !== undefined) {
          opened.push(decoded);
        }
      }
    }
    AutomergeImpl.applyRemote(joinScratch, opened);
    let last = changes.at(-1);
    if (last !== undefined) {
      cursor = last.created;
    }
  }
  let parsed = parseSnapshot(AutomergeImpl.materialize(joinScratch));
  let canonical = AppFile.idFor(parsed.source, [], fallback);
  let existing = await SpaceStore.loadLink(canonical);
  let sameSpace = existing !== undefined ? existing.spaceId === found.space : false;
  let localId = !taken.includes(canonical) || sameSpace ? canonical : AppId.unique(canonical, taken);
  let link_spaceId = found.space;
  let link_role = found.role;
  let link_keys = singleKeyJson(found.epoch, spaceKey);
  let link = {
    spaceId: link_spaceId,
    role: link_role,
    keys: link_keys,
    cursor: cursor,
    canonical: canonical
  };
  let localSource = canonical === localId ? parsed.source : AppDocument.withId(parsed.source, localId);
  await DocumentStore.save(localId, localSource);
  await CollectionStore.clear(localId);
  await CollectionStore.importAll(localId, parsed.collections);
  await SpaceStore.saveDoc(localId, AutomergeImpl.save(joinScratch));
  AutomergeImpl.close(joinScratch);
  await SpaceStore.saveLink(localId, link);
  return localId;
}

async function members(app, session) {
  let link = await SpaceStore.loadLink(app);
  if (link !== undefined) {
    return await SpaceServer.listMembers(session.token, link.spaceId);
  } else {
    return [];
  }
}

async function removeMember(app, session, memberId) {
  let link = await SpaceStore.loadLink(app);
  if (link === undefined) {
    return false;
  }
  let token = session.token;
  let removed = await SpaceServer.deleteMember(token, memberId);
  if (!removed) {
    return false;
  }
  let newEpoch = currentEpoch(link) + 1 | 0;
  let newKey = await ShareCrypto.generateKey();
  let remaining = await SpaceServer.listMembers(token, link.spaceId);
  for (let index = 0, index_finish = remaining.length; index < index_finish; ++index) {
    let row = remaining[index];
    let sealed = await SpaceCrypto.wrapForMember(row.pub, newKey);
    await SpaceServer.updateMemberKeys(token, row.id, addKeyJson(row.keys, newEpoch, sealed));
  }
  let updated = SpaceStore.withEpochKey(link, newEpoch, newKey);
  let state = active[app];
  let snapshot = state !== undefined ? (state.link = updated, AutomergeImpl.save(app)) : "";
  await SpaceStore.saveLink(app, updated);
  let sealedSnapshot = snapshot === "" ? "" : await ShareCrypto.encrypt(newKey, snapshot);
  let body = `{"epoch": ` + newEpoch.toString() + (
    sealedSnapshot === "" ? "}" : `, "snapshot": ` + Stdlib_Option.getOr(JSON.stringify(sealedSnapshot), "\"\"") + `, "snapshotUntil": ` + Stdlib_Option.getOr(JSON.stringify(updated.cursor), "\"\"") + `}`
  );
  await SpaceServer.updateSpace(token, link.spaceId, body);
  return true;
}

export {
  start,
  stop,
  localChanged,
  isActive,
  roleOf,
  create,
  invite,
  join,
  members,
  removeMember,
}
/*  Not a pure module */
