// Generated by ReScript, PLEASE EDIT WITH CARE


let editingBreakpoint = "(min-width: 48rem)";

function canEdit() {
  try {
    return matchMedia(editingBreakpoint).matches;
  } catch (exn) {
    return true;
  }
}

let subscribe = (function (onChange) {
  if (typeof matchMedia !== "function") return function () {};
  const query = matchMedia("(min-width: 48rem)");
  const handler = (event) => onChange(event.matches);
  query.addEventListener("change", handler);
  return function () { query.removeEventListener("change", handler); };
});

export {
  editingBreakpoint,
  canEdit,
  subscribe,
}
/* No side effect */
