// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Idb from "./Idb.res.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

let key = "welcome-seed";

function read() {
  return Idb.get(key).then(value => Stdlib_Option.getOr((value == null) ? undefined : Primitive_option.some(value), ""));
}

function record(digest) {
  return Idb.set(key, digest);
}

export {
  read,
  record,
}
/* Idb Not a pure module */
