// Generated by ReScript, PLEASE EDIT WITH CARE


const workflowRuns = new WeakMap();

globalThis.__rnWorkflow = {
  // The only question an engine asks on the common path, where there is no workflow
  // anywhere in the document: one closest() up a tree it is already standing in.
  defers(node) {
    return node && node.closest ? node.closest("[data-rn-workflow]") !== null : false;
  },

  // The engine's own run, kept against the node. The nodes are recreated by every
  // debounced render, so every render re-registers — which is exactly right: the
  // closure has to be the one that knows about the node on screen now. It resolves
  // "waiting" when it declined, and anything else when it ran.
  register(node, run) {
    if (node) workflowRuns.set(node, run);
  },

  runOf(node) {
    return (node && workflowRuns.get(node)) || null;
  },
};
;

function runOf(prim) {
  return __rnWorkflow.runOf(prim);
}

export {
  runOf,
}
/*  Not a pure module */
