// Generated by ReScript, PLEASE EDIT WITH CARE


import * as XLSX from "xlsx";
;

let toBytes = (function (grid) {
  const sheet = XLSX.utils.aoa_to_sheet(grid);
  const book = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(book, sheet, "rows");
  return new Uint8Array(XLSX.write(book, { type: "array", bookType: "xlsx" }));
});

let parse = (function (buffer) {
  try {
    const book = XLSX.read(buffer, { type: "array" });
    const first = book.SheetNames[0];
    if (!first) return [];
    return XLSX.utils
      .sheet_to_json(book.Sheets[first], { header: 1, raw: false, defval: "" })
      .map((row) => row.map((cell) => String(cell ?? "")));
  } catch {
    return [];
  }
});

export {
  toBytes,
  parse,
}
/*  Not a pure module */
