// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

function trim(s) {
  return s.trim();
}

function pulisciComune(testo) {
  let senzaCap = testo.replace(/^\s*\d{5}\s+/, "");
  return senzaCap.replace(/\s*\([A-Za-z]{2}\)\s*$/, "").replace(/\s+-\s*[A-Za-z]{2}\s*$/, "").trim();
}

function staccaCivico(testo) {
  let t = testo.trim();
  let m = /^(.*?)[\s,]+(\d+)\s*(?:\/\s*)?([A-Za-z])?\s*$/.exec(t);
  if (m == null) {
    return [
      t,
      "",
      ""
    ];
  }
  let parte = i => Stdlib_Option.getOr(Stdlib_Option.flatMap(m.slice(1).at(i), v => v), "").trim();
  let via = parte(0);
  if (via === "") {
    return [
      t,
      "",
      ""
    ];
  } else {
    return [
      via,
      parte(1),
      parte(2).toUpperCase()
    ];
  }
}

function soloCifre(s) {
  if (s !== "") {
    return s.split("").every(c => {
      if (c >= "0") {
        return c <= "9";
      } else {
        return false;
      }
    });
  } else {
    return false;
  }
}

function parse(testo) {
  let pezzi = testo.split(",").map(trim).filter(p => p !== "");
  let n = pezzi.length;
  if (n === 0 || n === 1) {
    return;
  }
  let comune = pulisciComune(pezzi[n - 1 | 0]);
  let match = staccaCivico(pezzi[0]);
  let civico = match[1];
  let via = match[0];
  let match$1;
  if (civico === "" && n >= 3) {
    let mezzo = pezzi[1];
    let m = /^(\d+)\s*(?:\/\s*)?([A-Za-z])?$/.exec(mezzo);
    if (m == null) {
      match$1 = [
        "",
        ""
      ];
    } else {
      let parte = i => Stdlib_Option.getOr(Stdlib_Option.flatMap(m.slice(1).at(i), v => v), "").trim();
      match$1 = [
        parte(0),
        parte(1).toUpperCase()
      ];
    }
  } else {
    match$1 = [
      civico,
      match[2]
    ];
  }
  if (via === "" || comune === "" || soloCifre(comune)) {
    return;
  } else {
    return {
      odonimo: via,
      civico: match$1[0],
      esponente: match$1[1],
      comune: comune
    };
  }
}

export {
  parse,
}
/* No side effect */
