// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Expr from "./Expr.res.mjs";
import * as Stamps from "./Stamps.res.mjs";
import * as Buntest from "bun:test";
import * as Aggregate from "./Aggregate.res.mjs";
import * as Collection from "./Collection.res.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

function row(id, fields) {
  return {
    id: id,
    fields: fields.map(param => ({
      name: param[0],
      value: param[1]
    }))
  };
}

let marks = {
  records: [
    row("1", [
      [
        "name",
        "Ada"
      ],
      [
        "mark",
        "30"
      ]
    ]),
    row("2", [
      [
        "name",
        "Bo"
      ],
      [
        "mark",
        "24"
      ]
    ]),
    row("3", [
      [
        "name",
        "Cy"
      ],
      [
        "mark",
        ""
      ]
    ]),
    row("4", [
      [
        "name",
        "Ada"
      ],
      [
        "mark",
        "27"
      ]
    ])
  ]
};

function compute(name, fieldOpt, decimals) {
  let field = fieldOpt !== undefined ? fieldOpt : "mark";
  return Stdlib_Option.getOr(Stdlib_Option.flatMap(Aggregate.parse(name), kind => Aggregate.compute(kind, marks, field, decimals)), "—");
}

Buntest.describe("Aggregate", () => {
  Buntest.test("counts rows, not values", () => {
    Buntest.expect(compute("count", undefined, undefined)).toBe("4");
  });
  Buntest.test("skips values that do not read as numbers", () => {
    Buntest.expect(compute("sum", undefined, undefined)).toBe("81");
    Buntest.expect(compute("avg", undefined, undefined)).toBe("27");
  });
  Buntest.test("a date is not counted as the year it starts with", () => {
    let dated = {
      records: [
        row("1", [[
            "due",
            "2026-08-12"
          ]]),
        row("2", [[
            "due",
            "2026-08-13"
          ]])
      ]
    };
    Buntest.expect(Stdlib_Option.getOr(Aggregate.compute("Sum", dated, "due", undefined), "—")).toBe("0");
    Buntest.expect(Stdlib_Option.getOr(Aggregate.compute("Average", dated, "due", undefined), "—")).toBe("—");
  });
  Buntest.test("reports the extremes", () => {
    Buntest.expect(compute("min", undefined, undefined)).toBe("24");
    Buntest.expect(compute("max", undefined, undefined)).toBe("30");
  });
  Buntest.test("median of an even count is the midpoint", () => {
    Buntest.expect(compute("median", undefined, undefined)).toBe("27");
  });
  Buntest.test("deviation needs two values", () => {
    Buntest.expect(compute("stddev", undefined, undefined)).toBe("3");
    let single = {
      records: [row("1", [[
            "mark",
            "5"
          ]])]
    };
    Buntest.expect(Stdlib_Option.getOr(Aggregate.compute("Deviation", single, "mark", undefined), "—")).toBe("—");
  });
  Buntest.test("mode works on text, first seen wins a tie", () => {
    Buntest.expect(compute("mode", "name", undefined)).toBe("Ada");
  });
  Buntest.test("an empty collection has no average to report", () => {
    Buntest.expect(Stdlib_Option.getOr(Aggregate.compute("Average", Collection.empty, "mark", undefined), "—")).toBe("—");
  });
  Buntest.test("formats without the zeros division leaves behind", () => {
    Buntest.expect(Aggregate.format(27.0, undefined)).toBe("27");
    Buntest.expect(Aggregate.format(27.5, undefined)).toBe("27.5");
    Buntest.expect(Aggregate.format(1.0 / 3.0, undefined)).toBe("0.3333");
    Buntest.expect(Aggregate.format(1.0 / 3.0, 2)).toBe("0.33");
  });
  Buntest.test("only the aggregation names parse", () => {
    Buntest.expect(Stdlib_Option.isSome(Aggregate.parse("sum"))).toBe(true);
    Buntest.expect(Stdlib_Option.isSome(Aggregate.parse("slider"))).toBe(false);
  });
});

Buntest.describe("Expr.evaluate", () => {
  let store = key => {
    switch (key) {
      case "price" :
        return "10";
      case "qty" :
        return "3";
      case "text" :
        return "abc";
      default:
        return;
    }
  };
  Buntest.test("applies the precedence everyone expects", () => {
    Buntest.expect(Expr.evaluate("2 + 3 * 4", store)).toEqual(14.0);
    Buntest.expect(Expr.evaluate("(2 + 3) * 4", store)).toEqual(20.0);
  });
  Buntest.test("resolves reactive keys", () => {
    Buntest.expect(Expr.evaluate("#price * #qty", store)).toEqual(30.0);
    Buntest.expect(Expr.evaluate("#price * #qty * 1.22", store)).toEqual(36.6);
  });
  Buntest.test("a missing or non-numeric key counts as zero", () => {
    Buntest.expect(Expr.evaluate("#unknown + 5", store)).toEqual(5.0);
    Buntest.expect(Expr.evaluate("#text + 5", store)).toEqual(5.0);
    Buntest.expect(Expr.evaluate("#due + 5", key => {
      if (key === "due") {
        return "2026-08-12";
      }
    })).toEqual(5.0);
  });
  Buntest.test("negation works, including on a key", () => {
    Buntest.expect(Expr.evaluate("-#price + 4", store)).toEqual(-6.0);
  });
  Buntest.test("a typo does not evaluate half the expression", () => {
    Buntest.expect(Expr.evaluate("1.2.3", store)).toEqual(undefined);
    Buntest.expect(Expr.evaluate("2 +", store)).toEqual(undefined);
    Buntest.expect(Expr.evaluate("2 3", store)).toEqual(undefined);
    Buntest.expect(Expr.evaluate("(2 + 3", store)).toEqual(undefined);
    Buntest.expect(Expr.evaluate("2 $ 3", store)).toEqual(undefined);
    Buntest.expect(Expr.evaluate("#", store)).toEqual(undefined);
  });
  Buntest.test("division by zero has no answer rather than an infinite one", () => {
    Buntest.expect(Expr.evaluate("5 / 0", store)).toEqual(undefined);
    Buntest.expect(Expr.evaluate("5 / #unknown", store)).toEqual(undefined);
  });
  Buntest.test("lists the keys a view must subscribe to", () => {
    Buntest.expect(Expr.references("#price * #qty * 1.22").join(",")).toBe("price,qty");
  });
});

Buntest.describe("Stamps", () => {
  Buntest.test("a new row carries both stamps, equal", () => {
    let fields = Stamps.apply([{
        name: "name",
        value: "Ada"
      }], "2026-08-10T09:00:00Z", undefined);
    let record = {
      id: "1",
      fields: fields
    };
    Buntest.expect(Collection.field(record, Stamps.created)).toEqual("2026-08-10T09:00:00Z");
    Buntest.expect(Collection.field(record, Stamps.updated)).toEqual("2026-08-10T09:00:00Z");
  });
  Buntest.test("an edit moves the modification time and keeps the creation time", () => {
    let fields = Stamps.apply([{
        name: "name",
        value: "Ada"
      }], "2026-08-11T10:00:00Z", "2026-08-10T09:00:00Z");
    let record = {
      id: "1",
      fields: fields
    };
    Buntest.expect(Collection.field(record, Stamps.created)).toEqual("2026-08-10T09:00:00Z");
    Buntest.expect(Collection.field(record, Stamps.updated)).toEqual("2026-08-11T10:00:00Z");
  });
  Buntest.test("an authored stamp field is replaced, not duplicated", () => {
    let fields = Stamps.apply([
      {
        name: "createdAt",
        value: "yesterday"
      },
      {
        name: "name",
        value: "Ada"
      }
    ], "2026-08-10T09:00:00Z", undefined);
    let named = fields.filter(field => field.name === Stamps.created);
    Buntest.expect(named.length).toBe(1);
    let stamp = named[0];
    Buntest.expect(stamp.value).toBe("2026-08-10T09:00:00Z");
  });
});

export {
  row,
  marks,
  compute,
}
/* marks Not a pure module */
