// Generated by ReScript, PLEASE EDIT WITH CARE


let metrics = [
  "count",
  "sum",
  "avg",
  "min",
  "max"
];

let operators = [
  "eq",
  "ne",
  "gt",
  "lt",
  "gte",
  "lte",
  "contains",
  "empty",
  "not-empty"
];

function rnFold(s) {
  return String(s === null || s === undefined ? "" : s)
    .normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase();
}
function rnPasses(test, row) {
  const raw = row[test.field];
  const held = raw === null || raw === undefined ? "" : String(raw);
  const wanted = String(test.value || "");
  if (test.op === "empty") return held.trim() === "";
  if (test.op === "not-empty") return held.trim() !== "";
  if (test.op === "contains") return rnFold(held).includes(rnFold(wanted));
  const a = Number(held.trim().replace(",", "."));
  const b = Number(wanted.trim().replace(",", "."));
  const numeric = held.trim() !== "" && wanted.trim() !== "" && Number.isFinite(a) && Number.isFinite(b);
  const x = numeric ? a : rnFold(held);
  const y = numeric ? b : rnFold(wanted);
  if (test.op === "eq") return x === y;
  if (test.op === "ne") return x !== y;
  if (test.op === "gt") return x > y;
  if (test.op === "lt") return x < y;
  if (test.op === "gte") return x >= y;
  if (test.op === "lte") return x <= y;
  return true;
}
;

let json = (function (text) {
  const source = String(text || "");
  const direct = (s) => { try { return JSON.parse(s); } catch (e) { return undefined; } };
  const whole = direct(source.trim());
  if (whole !== undefined && typeof whole === "object" && whole !== null) return whole;

  // A fenced block first — it is what the model was asked for. The fence is built
  // from its character code because a backtick inside a raw block would end it.
  const fence = String.fromCharCode(96).repeat(3);
  const parts = source.split(fence);
  if (parts.length >= 3) {
    let inner = parts[1];
    const newline = inner.indexOf("\n");
    if (newline !== -1 && inner.slice(0, newline).trim().length <= 8) inner = inner.slice(newline + 1);
    const value = direct(inner.trim());
    if (value !== undefined) return value;
  }

  // Then the first balanced { } or [ ] anywhere in the prose.
  for (const pair of [["{", "}"], ["[", "]"]]) {
    const open = pair[0], close = pair[1];
    const start = source.indexOf(open);
    if (start === -1) continue;
    let depth = 0, quoted = false, escaped = false;
    for (let i = start; i < source.length; i++) {
      const c = source[i];
      if (escaped) { escaped = false; continue; }
      if (c === "\\") { escaped = true; continue; }
      if (c === '"') { quoted = !quoted; continue; }
      if (quoted) continue;
      if (c === open) depth++;
      else if (c === close) {
        depth--;
        if (depth === 0) {
          const value = direct(source.slice(start, i + 1));
          if (value !== undefined) return value;
          break;
        }
      }
    }
  }
  return undefined;
});

let fields = (function (given) {
  return String(given || "")
    .split(",")
    .map((entry) => entry.trim())
    .filter(Boolean)
    .map((entry) => {
      const colon = entry.indexOf(":");
      if (colon === -1) return { name: entry, kind: "text" };
      const kind = entry.slice(colon + 1).trim().toLowerCase();
      return {
        name: entry.slice(0, colon).trim(),
        kind: ["number", "date", "boolean", "text"].includes(kind) ? kind : "text",
      };
    })
    .filter((f) => f.name !== "");
});

let list = (function (given) {
  return String(given || "").split(",").map((s) => s.trim()).filter(Boolean);
});

let clamp = (function (given, values) {
  const flatten = (s) => rnFold(s).replace(/[^a-z0-9]+/g, " ").trim();
  const answer = flatten(given);
  if (answer === "") return undefined;
  for (const value of values) if (String(value) === String(given)) return value;
  for (const value of values) if (flatten(value) === answer) return value;
  // The value said somewhere inside a sentence — "casa, perché è una spesa
  // domestica" — but only when exactly ONE of them is in there. An answer naming
  // two has chosen neither, and picking the first would be inventing the very
  // classification this function exists to refuse.
  const words = (" " + answer + " ");
  const named = values.filter((value) => {
    const folded = flatten(value);
    return folded !== "" && words.includes(" " + folded + " ");
  });
  return named.length === 1 ? named[0] : undefined;
});

let record = (function (value, declared) {
  if (value === null || typeof value !== "object" || Array.isArray(value)) return [];
  const out = [];
  for (const field of declared) {
    const given = value[field.name];
    if (given === null || given === undefined || typeof given === "object") continue;
    let text = String(given).trim();
    if (text === "") continue;
    if (field.kind === "number") {
      const number = Number(text.replace(",", "."));
      if (!Number.isFinite(number)) continue;
      text = String(number);
    } else if (field.kind === "boolean") {
      const low = text.toLowerCase();
      const yes = ["true", "yes", "si", "sì", "1", "on"].includes(low);
      const no = ["false", "no", "0", "off"].includes(low);
      if (!yes && !no) continue;
      text = yes ? "true" : "false";
    } else if (field.kind === "date") {
      // Only what a date field of this app would store.
      const match = text.match(/^\d{4}-\d{2}-\d{2}/);
      if (!match) continue;
      text = match[0];
    }
    out.push({ name: field.name, value: text });
  }
  return out;
});

let plan = (function (value, allowed) {
  if (value === null || typeof value !== "object" || Array.isArray(value)) {
    return { TAG: "Error", _0: "not an object" };
  }
  const ops = ["eq", "ne", "gt", "lt", "gte", "lte", "contains", "empty", "not-empty"];
  const known = (name) => allowed.includes(String(name));
  const filters = [];
  for (const entry of Array.isArray(value.filters) ? value.filters : []) {
    if (entry === null || typeof entry !== "object") continue;
    const field = String(entry.field || "");
    if (!known(field)) return { TAG: "Error", _0: "unknown field: " + field };
    filters.push({
      field,
      op: ops.includes(String(entry.op)) ? String(entry.op) : "eq",
      value: entry.value === null || entry.value === undefined ? "" : String(entry.value),
    });
  }
  const groupBy = value.groupBy === null || value.groupBy === undefined ? "" : String(value.groupBy);
  if (groupBy !== "" && !known(groupBy)) return { TAG: "Error", _0: "unknown field: " + groupBy };
  const metric = ["count", "sum", "avg", "min", "max"].includes(String(value.metric))
    ? String(value.metric) : "count";
  const metricField = value.field === null || value.field === undefined ? "" : String(value.field);
  if (metric !== "count" && !known(metricField)) return { TAG: "Error", _0: "unknown field: " + metricField };
  const asked = Number(value.limit);
  return {
    TAG: "Ok",
    _0: {
      filters,
      groupBy,
      metric,
      metricField: metric === "count" ? "" : metricField,
      sort: String(value.sort) === "asc" ? "asc" : "desc",
      limit: Number.isFinite(asked) ? Math.max(1, Math.min(200, Math.trunc(asked))) : 20,
    },
  };
});

let passes = (function (test, row) { return rnPasses(test, row); });

let run = (function (plan, rows) {
  const kept = rows.filter((row) => plan.filters.every((test) => rnPasses(test, row)));
  const numbersOf = (list) => list
    .map((row) => {
      const held = row[plan.metricField];
      const text = held === null || held === undefined ? "" : String(held).trim().replace(",", ".");
      return text === "" ? NaN : Number(text);
    })
    .filter((n) => Number.isFinite(n));
  const round = (n) => String(Math.round(n * 100) / 100);
  const measure = (list) => {
    if (plan.metric === "count") return String(list.length);
    const numbers = numbersOf(list);
    if (numbers.length === 0) return "—";
    if (plan.metric === "sum") return round(numbers.reduce((a, b) => a + b, 0));
    if (plan.metric === "avg") return round(numbers.reduce((a, b) => a + b, 0) / numbers.length);
    if (plan.metric === "min") return round(Math.min.apply(null, numbers));
    return round(Math.max.apply(null, numbers));
  };

  if (plan.groupBy === "") return { scalar: measure(kept), rows: [] };

  const groups = new Map();
  for (const row of kept) {
    const held = row[plan.groupBy];
    const label = held === null || held === undefined || String(held).trim() === "" ? "—" : String(held);
    if (!groups.has(label)) groups.set(label, []);
    groups.get(label).push(row);
  }
  const lines = [...groups.entries()].map((entry) => ({ label: entry[0], value: measure(entry[1]) }));
  lines.sort((a, b) => {
    const x = Number(a.value), y = Number(b.value);
    const numeric = Number.isFinite(x) && Number.isFinite(y);
    const order = numeric ? x - y : String(a.label).localeCompare(String(b.label));
    return plan.sort === "asc" ? order : -order;
  });
  return { scalar: "", rows: lines.slice(0, plan.limit) };
});

let rule = (function (value, allowed) {
  if (value === null || typeof value !== "object" || Array.isArray(value)) {
    return { TAG: "Error", _0: "not an object" };
  }
  const ops = ["eq", "ne", "gt", "lt", "gte", "lte", "contains", "empty", "not-empty"];
  const field = String(value.field || "");
  const setField = String(value.setField || "");
  if (!allowed.includes(field)) return { TAG: "Error", _0: "unknown field: " + field };
  if (!allowed.includes(setField)) return { TAG: "Error", _0: "unknown field: " + setField };
  const setValue = value.setValue === null || value.setValue === undefined ? "" : String(value.setValue);
  if (setValue === "") return { TAG: "Error", _0: "the rule writes nothing" };
  return {
    TAG: "Ok",
    _0: {
      field,
      op: ops.includes(String(value.op)) ? String(value.op) : "eq",
      value: value.value === null || value.value === undefined ? "" : String(value.value),
      setField,
      setValue,
    },
  };
});

let applies = (function (rule, rows) {
  return rows.filter((row) => {
    const held = row[rule.setField];
    if ((held === null || held === undefined ? "" : String(held)) === rule.setValue) return false;
    return rnPasses({ field: rule.field, op: rule.op, value: rule.value }, row);
  });
});

let sample = (function (rows, many) { return JSON.stringify(rows.slice(0, many)); });

let planPrompt = (function (question, fields, rows) {
  return [
    "You turn a question about a table into a query plan. You never write code and never invent data.",
    "The table's fields are exactly: " + fields.join(", ") + ".",
    "A few rows, so you can see what the values look like: " + rows,
    "",
    "Answer with this JSON object:",
    '{"filters":[{"field":"<one of the fields>","op":"eq|ne|gt|lt|gte|lte|contains|empty|not-empty","value":"<text>"}],',
    ' "groupBy":"<one of the fields, or empty for a single number>",',
    ' "metric":"count|sum|avg|min|max", "field":"<the numeric field the metric works on, empty for count>",',
    ' "sort":"asc|desc", "limit":<a number>}',
    "",
    "Every field name must be one of the fields listed above; do not invent one.",
    "The question is: " + question,
    "Answer with JSON and nothing else.",
  ].join("\n");
});

let rulePrompt = (function (when_, do_, fields, rows) {
  return [
    "You compile a rule about a table into JSON. The rule then runs without you, so it must be exact.",
    "The table's fields are exactly: " + fields.join(", ") + ".",
    "A few rows: " + rows,
    "",
    "Answer with this JSON object:",
    '{"field":"<the field the condition looks at>","op":"eq|ne|gt|lt|gte|lte|contains|empty|not-empty","value":"<text>",',
    ' "setField":"<the field to write>","setValue":"<the value to write>"}',
    "",
    "Every field name must be one of the fields listed above.",
    "The condition is: " + when_,
    "The action is: " + do_,
    "Answer with JSON and nothing else.",
  ].join("\n");
});

let recordPrompt = (function (instruction, fields, text) {
  const shape = fields.map((f) => '"' + f.name + '": "' +
    (f.kind === "number" ? "a number"
      : f.kind === "date" ? "YYYY-MM-DD"
      : f.kind === "boolean" ? "true or false" : "text") + '"');
  return [
    instruction,
    "Answer with a JSON object with exactly these keys: {" + shape.join(", ") + "}.",
    "Leave a key out when the text does not say what it is. Do not invent values.",
    "Answer with JSON and nothing else.",
    "",
    text,
  ].join("\n");
});

let classifyPrompt = (function (instruction, values, text) {
  return [
    instruction,
    "Answer with exactly one of these words, and nothing else: " + values.join(", ") + ".",
    "",
    text,
  ].join("\n");
});

let summaryPrompt = (function (instruction, rows, many) {
  return [
    "You describe a table for the person who owns it. Be short, concrete and honest:",
    "give numbers where the data has them, and say nothing the data does not support.",
    "The table has " + many + " rows. Here are up to a hundred of them: " + rows,
    "",
    instruction,
  ].join("\n");
});

let chatSystem = (function (persona, rows) {
  return [
    persona === "" ? "You answer questions about the data below." : persona,
    "You may only use the data below. If it does not answer the question, say so plainly.",
    "Do not invent rows, totals or names.",
    "",
    "The data: " + rows,
  ].join("\n");
});

export {
  metrics,
  operators,
  json,
  fields,
  list,
  clamp,
  record,
  plan,
  passes,
  run,
  rule,
  applies,
  sample,
  planPrompt,
  rulePrompt,
  recordPrompt,
  classifyPrompt,
  summaryPrompt,
  chatSystem,
}
/*  Not a pure module */
