// Generated by ReScript, PLEASE EDIT WITH CARE


let compact = (function (history) {
  const CEILING = 700, KEPT = 300, MAX = 60;
  const elide = text =>
    typeof text === "string" && text.length > CEILING
      ? text.slice(0, KEPT) +
        "\n… [" + (text.length - KEPT) + " chars of an earlier turn elided — call the tool again if you need the rest]"
      : text;

  const messages = history.map(message => {
    if (!message || typeof message !== "object") return message;
    if (message.role === "tool") return { ...message, content: elide(message.content) };
    if (message.role === "assistant" && Array.isArray(message.tool_calls)) {
      return {
        ...message,
        tool_calls: message.tool_calls.map(call => {
          if (!call || !call.function) return call;
          const fn = call.function;
          // OpenAI carries arguments as a JSON string; Ollama's native shape as an
          // object whose long fields (a delivery's markdown) are the real weight.
          if (typeof fn.arguments === "string")
            return { ...call, function: { ...fn, arguments: elide(fn.arguments) } };
          if (fn.arguments && typeof fn.arguments === "object" && !Array.isArray(fn.arguments)) {
            const slimmed = {};
            for (const key of Object.keys(fn.arguments)) slimmed[key] = elide(fn.arguments[key]);
            return { ...call, function: { ...fn, arguments: slimmed } };
          }
          return call;
        }),
      };
    }
    return message;
  });

  if (messages.length <= MAX) return messages;
  // Drop from the front, but only ever land on a user message: any prefix removed
  // up to one leaves a history that starts a fresh exchange with every
  // call/result pairing intact.
  let start = messages.length - MAX;
  while (start < messages.length && !(messages[start] && messages[start].role === "user")) start++;
  return messages.slice(start);
});

let ceiling = 700;

let kept = 300;

let maxMessages = 60;

export {
  ceiling,
  kept,
  maxMessages,
  compact,
}
/* No side effect */
