// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Buntest from "bun:test";
import * as AiHistory from "./AiHistory.res.mjs";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";

let toolMsg = (function (content) { return { role: "tool", tool_call_id: "c1", content }; });

let userMsg = (function (text) { return { role: "user", content: text }; });

let assistantWithCall = (function (markdown) {
  return {
    role: "assistant",
    content: "",
    tool_calls: [{ id: "c1", function: { name: "reactive_create_app", arguments: JSON.stringify({ markdown }) } }],
  };
});

let assistantWithNativeCall = (function (markdown) {
  return {
    role: "assistant",
    content: "",
    tool_calls: [{ id: "c1", function: { name: "reactive_create_app", arguments: { markdown } } }],
  };
});

let contentOf = (function (m) { return m.content; });

let argumentsOf = (function (m) {
  const a = m.tool_calls[0].function.arguments;
  return typeof a === "string" ? a : JSON.stringify(a);
});

let roleOf = (function (m) { return m.role; });

let long = "x".repeat(3000);

Buntest.describe("AiHistory.compact", () => {
  Buntest.test("a long tool answer is elided with a note saying how to get it back", () => {
    let compacted = AiHistory.compact([toolMsg(long)]);
    let content = contentOf(compacted[0]);
    Buntest.expect(content.length < 500).toBe(true);
    Buntest.expect(content.includes("elided")).toBe(true);
  });
  Buntest.test("a short tool answer is left exactly as it was", () => {
    let compacted = AiHistory.compact([toolMsg("ok — the document is valid.")]);
    Buntest.expect(contentOf(compacted[0])).toBe("ok — the document is valid.");
  });
  Buntest.test("long tool-call arguments are elided, string and object shape alike", () => {
    let openai = AiHistory.compact([assistantWithCall(long)]);
    Buntest.expect(argumentsOf(openai[0]).length < 600).toBe(true);
    let native = AiHistory.compact([assistantWithNativeCall(long)]);
    Buntest.expect(argumentsOf(native[0]).length < 600).toBe(true);
  });
  Buntest.test("compacting twice is the same as compacting once", () => {
    let once = AiHistory.compact([
      toolMsg(long),
      assistantWithCall(long)
    ]);
    Buntest.expect(AiHistory.compact(once)).toEqual(once);
  });
  Buntest.test("an over-long conversation is cut from the front, at a user message", () => {
    let exchange = i => [
      userMsg("question " + i.toString()),
      assistantWithCall("doc"),
      toolMsg("answer")
    ];
    let history = Stdlib_Array.fromInitializer(30, exchange).flat();
    let compacted = AiHistory.compact(history);
    Buntest.expect(compacted.length <= AiHistory.maxMessages).toBe(true);
    Buntest.expect(roleOf(compacted[0])).toBe("user");
  });
  Buntest.test("a short conversation keeps its length", () => {
    let history = [
      userMsg("ciao"),
      toolMsg("ok")
    ];
    Buntest.expect(AiHistory.compact(history).length).toBe(2);
  });
});

export {
  toolMsg,
  userMsg,
  assistantWithCall,
  assistantWithNativeCall,
  contentOf,
  argumentsOf,
  roleOf,
  long,
}
/* long Not a pure module */
