// Generated by ReScript, PLEASE EDIT WITH CARE


let chunks = (function (text, size) {
  const source = String(text || "").replace(/\s+/g, " ").trim();
  if (source === "") return [];
  const width = Math.max(120, size || 600);
  if (source.length <= width) return [source];
  const overlap = Math.floor(width / 5);
  const out = [];
  let at = 0;
  while (at < source.length) {
    let end = Math.min(source.length, at + width);
    if (end < source.length) {
      // Back up to the last sentence end, then to the last space: a passage cut
      // mid-word is a passage that reads as a mistake in every citation.
      const window = source.slice(at, end);
      const stop = Math.max(window.lastIndexOf(". "), window.lastIndexOf("? "), window.lastIndexOf("! "));
      const space = window.lastIndexOf(" ");
      const cut = stop > width / 2 ? stop + 1 : space > width / 2 ? space : -1;
      if (cut > 0) end = at + cut;
    }
    const piece = source.slice(at, end).trim();
    if (piece !== "") out.push(piece);
    if (end >= source.length) break;
    at = Math.max(end - overlap, at + 1);
  }
  return out;
});

let normalise = (function (vector) {
  let sum = 0;
  for (const n of vector) sum += n * n;
  const length = Math.sqrt(sum);
  if (!Number.isFinite(length) || length === 0) return vector.map(() => 0);
  return vector.map((n) => n / length);
});

let cosine = (function (a, b) {
  if (a.length !== b.length) return 0;
  let sum = 0;
  for (let i = 0; i < a.length; i++) sum += a[i] * b[i];
  return sum;
});

let rank = (function (question, items, many, floor) {
  const hits = [];
  for (const item of items) {
    const score = cosineOf(question, item.vector);
    if (score >= floor) hits.push({ item, score });
  }
  hits.sort((a, b) => b.score - a.score);
  // One passage per source: five chunks of the same file are one answer, and they
  // would push every other document off a list of five.
  const seen = new Set();
  const kept = [];
  for (const hit of hits) {
    const source = hit.item.key.split("#")[0];
    if (seen.has(source)) continue;
    seen.add(source);
    kept.push(hit);
    if (kept.length >= many) break;
  }
  return kept;
});

const cosineOf = cosine;
;

let context = (function (hits) {
  return hits.map((hit) => "[" + hit.item.label + "] " + hit.item.text).join("\n\n");
});

export {
  chunks,
  normalise,
  cosine,
  rank,
  context,
}
/*  Not a pure module */
