// Generated by ReScript, PLEASE EDIT WITH CARE

import * as AppId from "./AppId.res.mjs";
import * as AppFile from "./AppFile.res.mjs";
import * as OdQuery from "./OdQuery.res.mjs";
import * as AppDocument from "./AppDocument.res.mjs";
import * as Frontmatter from "./Frontmatter.res.mjs";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as DirectiveScan from "./DirectiveScan.res.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as DirectiveAttributes from "./DirectiveAttributes.res.mjs";

function unfence(markdown) {
  let text = markdown.trim();
  if (!text.startsWith("```")) {
    return text;
  }
  let first = text.indexOf("\n");
  if (first === -1) {
    return text;
  }
  let opening = text.slice(0, first).trim();
  let isLanguageOnly = opening.length <= 12 && !opening.includes(" ");
  let body = text.slice(first + 1 | 0, text.length);
  if (!(isLanguageOnly && body.trimEnd().endsWith("```"))) {
    return text;
  }
  let trimmed = body.trimEnd();
  return trimmed.slice(0, trimmed.length - 3 | 0).trimEnd();
}

let refuseEmpty = "The document is empty. Write the whole app, frontmatter included, and call this tool again.";

function validates(report) {
  return report.trim().toLowerCase().startsWith("ok");
}

function connects(report) {
  return report.includes("No orphans");
}

function odQueries(document) {
  return Stdlib_Array.filterMap(DirectiveScan.scan(document), occurrence => {
    if (occurrence.name === "od-query") {
      return Stdlib_Option.flatMap(DirectiveAttributes.find(DirectiveAttributes.parse(occurrence.attributes), "sql"), sql => {
        if (OdQuery.references(sql).length === 0) {
          return sql;
        }
      });
    }
  });
}

function queryFails(answer) {
  if (answer.includes("THIS IS A BROKEN QUERY")) {
    return true;
  } else {
    return answer.includes("The query was refused");
  }
}

function titleOf(source, id) {
  let title = Stdlib_Option.flatMap(Frontmatter.parse(source).meta, meta => Frontmatter.get(meta, "title"));
  if (title !== undefined && title.trim() !== "") {
    return title.trim();
  } else {
    return id;
  }
}

function create(markdown, taken, fallback) {
  let source = unfence(markdown);
  if (source.trim() === "") {
    return {
      TAG: "Refused",
      _0: refuseEmpty
    };
  }
  let id = AppFile.idFor(source, taken, fallback);
  let stored = AppDocument.withId(source, id);
  return {
    TAG: "Deliver",
    id: id,
    source: stored,
    title: titleOf(stored, id),
    renamed: AppFile.isCopy(source, id)
  };
}

function replace(markdown, id) {
  let source = unfence(markdown);
  if (source.trim() === "") {
    return {
      TAG: "Refused",
      _0: refuseEmpty
    };
  }
  if (!AppId.isValid(id)) {
    return {
      TAG: "Refused",
      _0: "No app is open, so there is nothing to edit. Ask the user to open one, or create a new app instead."
    };
  }
  let stored = AppDocument.withId(source, id);
  return {
    TAG: "Deliver",
    id: id,
    source: stored,
    title: titleOf(stored, id),
    renamed: false
  };
}

export {
  unfence,
  validates,
  connects,
  odQueries,
  queryFails,
  create,
  replace,
}
/* DirectiveScan Not a pure module */
