// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Buntest from "bun:test";
import * as AiSettings from "./AiSettings.res.mjs";

Buntest.describe("AiSettings.normalize", () => {
  Buntest.test("an empty model or endpoint falls back to the default", () => {
    let normalized = AiSettings.normalize({
      key: " sk-abc ",
      model: "  ",
      baseUrl: ""
    });
    Buntest.expect(normalized.key).toBe("sk-abc");
    Buntest.expect(normalized.model).toBe(AiSettings.defaultModel);
    Buntest.expect(normalized.baseUrl).toBe(AiSettings.hostedBaseUrl);
  });
  Buntest.test("trailing slashes come off the endpoint", () => {
    let normalized = AiSettings.normalize({
      key: "k",
      model: "gpt-4.1",
      baseUrl: "https://example.test/v1//"
    });
    Buntest.expect(normalized.baseUrl).toBe("https://example.test/v1");
  });
});

Buntest.describe("AiSettings.check", () => {
  Buntest.test("a remote provider without a key cannot be called", () => {
    Buntest.expect(AiSettings.check({
      key: "   ",
      model: AiSettings.blank.model,
      baseUrl: AiSettings.blank.baseUrl
    })).toEqual("NoKey");
  });
  Buntest.test("http elsewhere is refused here rather than by the policy", () => {
    Buntest.expect(AiSettings.check({
      key: "k",
      model: "m",
      baseUrl: "http://192.168.1.4:11434/v1"
    })).toEqual("NotHttps");
  });
  Buntest.test("a model on this machine needs no key: there is no secret to ask for", () => {
    Buntest.expect(AiSettings.isReady(AiSettings.onOllama)).toBe(true);
    Buntest.expect(AiSettings.isLocal(AiSettings.onOllama)).toBe(true);
    Buntest.expect(AiSettings.isLocal({
      key: AiSettings.blank.key,
      model: AiSettings.blank.model,
      baseUrl: "http://127.0.0.1:1234/v1"
    })).toBe(true);
    Buntest.expect(AiSettings.isLocal({
      key: AiSettings.blank.key,
      model: AiSettings.blank.model,
      baseUrl: "http://[::1]:8080/v1"
    })).toBe(false);
    Buntest.expect(AiSettings.isLocal({
      key: AiSettings.blank.key,
      model: AiSettings.blank.model,
      baseUrl: "http://localhost.example.com/v1"
    })).toBe(false);
  });
  Buntest.test("a key and an https endpoint are ready", () => {
    Buntest.expect(AiSettings.isReady({
      key: "sk-abc",
      model: AiSettings.blank.model,
      baseUrl: AiSettings.blank.baseUrl
    })).toBe(true);
    Buntest.expect(AiSettings.isLocal({
      key: "sk-abc",
      model: AiSettings.blank.model,
      baseUrl: AiSettings.blank.baseUrl
    })).toBe(false);
  });
});

Buntest.describe("AiSettings.completionsUrl", () => {
  Buntest.test("is the endpoint plus the chat completions path", () => {
    Buntest.expect(AiSettings.completionsUrl({
      key: "k",
      model: "m",
      baseUrl: "https://example.test/v1/"
    })).toBe("https://example.test/v1/chat/completions");
  });
  Buntest.test("the same concatenation builds the local one", () => {
    Buntest.expect(AiSettings.completionsUrl(AiSettings.onOllama)).toBe("http://localhost:11434/v1/chat/completions");
  });
  Buntest.test("the native chat endpoint drops the /v1 layer", () => {
    Buntest.expect(AiSettings.nativeChatUrl(AiSettings.onOllama)).toBe("http://localhost:11434/api/chat");
    Buntest.expect(AiSettings.nativeChatUrl({
      key: AiSettings.onOllama.key,
      model: AiSettings.onOllama.model,
      baseUrl: "http://127.0.0.1:11434"
    })).toBe("http://127.0.0.1:11434/api/chat");
  });
});

/*  Not a pure module */
