// Generated by ReScript, PLEASE EDIT WITH CARE


let defaultModel = "gpt-4.1";

let hostedBaseUrl = "https://api.openai.com/v1";

let localBaseUrl = "http://localhost:11434/v1";

let defaultLocalModel = "qwen3.5:4b";

let blank = {
  key: "",
  model: defaultModel,
  baseUrl: hostedBaseUrl
};

let onOllama = {
  key: "",
  model: defaultLocalModel,
  baseUrl: localBaseUrl
};

function trimSlashes(url) {
  return url.replace(/\/+$/, "");
}

function normalize(settings) {
  let model = settings.model.trim();
  let tmp = model === "" ? defaultModel : model;
  let url = trimSlashes(settings.baseUrl.trim());
  let tmp$1 = url === "" ? hostedBaseUrl : url;
  return {
    key: settings.key.trim(),
    model: tmp,
    baseUrl: tmp$1
  };
}

let loopback = /^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?(\/|$)/;

function isLocal(settings) {
  return loopback.test(normalize(settings).baseUrl);
}

function check(settings) {
  let normalized = normalize(settings);
  if (loopback.test(normalized.baseUrl)) {
    return;
  } else if (normalized.baseUrl.startsWith("https://")) {
    if (normalized.key === "") {
      return "NoKey";
    } else {
      return;
    }
  } else {
    return "NotHttps";
  }
}

function isReady(settings) {
  return check(settings) === undefined;
}

function completionsUrl(settings) {
  return normalize(settings).baseUrl + "/chat/completions";
}

function nativeChatUrl(settings) {
  return normalize(settings).baseUrl.replace(/\/v1$/, "") + "/api/chat";
}

let defaultEmbedModel = "qwen3-embedding:0.6b";

let hostedEmbedModel = "text-embedding-3-small";

function embedModel(settings) {
  if (normalize(settings).baseUrl.includes("api.openai.com")) {
    return hostedEmbedModel;
  } else {
    return defaultEmbedModel;
  }
}

function embeddingsUrl(settings) {
  if (isLocal(settings)) {
    return normalize(settings).baseUrl.replace(/\/v1$/, "") + "/api/embed";
  } else {
    return normalize(settings).baseUrl + "/embeddings";
  }
}

export {
  defaultModel,
  hostedBaseUrl,
  localBaseUrl,
  defaultLocalModel,
  blank,
  onOllama,
  normalize,
  isLocal,
  check,
  isReady,
  completionsUrl,
  nativeChatUrl,
  defaultEmbedModel,
  hostedEmbedModel,
  embedModel,
  embeddingsUrl,
}
/* No side effect */
