// Generated by ReScript, PLEASE EDIT WITH CARE


let listApps = "reactive_list_apps";

let readApp = "reactive_read_app";

let createApp = "reactive_create_app";

let editApp = "reactive_edit_app";

let local = [
  listApps,
  readApp,
  createApp,
  editApp
];

function isLocal(name) {
  return local.includes(name);
}

let declarations = ([
  {
    type: "function",
    function: {
      name: "reactive_list_apps",
      description:
        "The apps stored in this browser's gallery: id, title and description of each. " +
        "Call it before creating an app the user refers to as an existing one, and " +
        "before choosing an id.",
      parameters: { type: "object", properties: {}, additionalProperties: false },
    },
  },
  {
    type: "function",
    function: {
      name: "reactive_read_app",
      description:
        "The complete Markdown source of an app stored here, frontmatter included. " +
        "With no id it reads the app currently open. ALWAYS read an app before " +
        "proposing an edit to it: reactive_edit_app replaces the whole document, so " +
        "anything you did not carry across is deleted.",
      parameters: {
        type: "object",
        properties: {
          id: {
            type: "string",
            description: "The app's id. Omit for the app the user currently has open.",
          },
        },
        additionalProperties: false,
      },
    },
  },
  {
    type: "function",
    function: {
      name: "reactive_create_app",
      description:
        "Creates a NEW app in this browser's gallery from a complete Markdown document. " +
        "THIS IS THE STEP THAT GIVES THE USER THEIR APP — call it as soon as you have a " +
        "complete document; do not stop after researching, and do not ask permission " +
        "first. It validates the document itself and REFUSES anything that does not " +
        "pass, handing back the problems with line numbers, so you do not need to be " +
        "certain before calling it: when it refuses, fix what it reports and call it " +
        "again straight away. It never overwrites — a document whose appId is already " +
        "in use lands as a copy under a free id.",
      parameters: {
        type: "object",
        properties: {
          markdown: {
            type: "string",
            description:
              "The complete document, frontmatter included, unfenced. Not a fragment: " +
              "what you pass here is stored verbatim as the whole app.",
          },
        },
        required: ["markdown"],
        additionalProperties: false,
      },
    },
  },
  {
    type: "function",
    function: {
      name: "reactive_edit_app",
      description:
        "Proposes a rewrite of an app stored in this browser — the one the user has " +
        "open when id is omitted, or any app by its id (find ids with " +
        "reactive_list_apps). The rewrite is not applied: it is shown to the user with " +
        "a diff, and they apply or discard it — so say in your reply what you changed. " +
        "Pass the COMPLETE new document, not a patch: anything you leave out is " +
        "deleted, so ALWAYS reactive_read_app first and carry everything else across. " +
        "The appId is kept as it is: an edit never moves an app.",
      parameters: {
        type: "object",
        properties: {
          markdown: {
            type: "string",
            description: "The complete new document, frontmatter included, unfenced.",
          },
          id: {
            type: "string",
            description: "The app to rewrite. Omit for the app the user currently has open.",
          },
          note: {
            type: "string",
            description: "One line naming what changed, shown to the user beside the proposal.",
          },
        },
        required: ["markdown"],
        additionalProperties: false,
      },
    },
  },
]);

export {
  listApps,
  readApp,
  createApp,
  editApp,
  local,
  isLocal,
  declarations,
}
/* declarations Not a pure module */
