// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ApiRows from "./ApiRows.res.mjs";
import * as Buntest from "bun:test";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

function json(text) {
  return JSON.parse(text);
}

function names(fields) {
  return fields.map(field => field.name).join(",");
}

function value(fields, name) {
  return Stdlib_Option.map(fields.find(field => field.name === name), field => field.value);
}

Buntest.describe("ApiRows.picked", () => {
  Buntest.test("walks names and indices", () => {
    let found = ApiRows.picked(JSON.parse(`{"results":[{"series":[1,2]}]}`), "results.0.series");
    Buntest.expect(Stdlib_Option.map(found, __x => JSON.stringify(__x))).toEqual("[1,2]");
  });
  Buntest.test("a path off the document is nothing", () => {
    Buntest.expect(Stdlib_Option.isNone(ApiRows.picked(JSON.parse(`{"a":1}`), "b.c"))).toBe(true);
  });
  Buntest.test("an empty pick is the root", () => {
    Buntest.expect(Stdlib_Option.isNone(ApiRows.picked(JSON.parse(`{"a":1}`), ""))).toBe(false);
  });
});

Buntest.describe("ApiRows.rows", () => {
  Buntest.test("an array of objects is rows already", () => {
    let rows = Stdlib_Option.getExn(ApiRows.rows(JSON.parse(`[{"a":1,"b":"x"},{"a":2,"b":"y"}]`), false), undefined);
    Buntest.expect(rows.length).toBe(2);
    Buntest.expect(value(rows[0], "a")).toEqual("1");
    Buntest.expect(value(rows[1], "b")).toEqual("y");
  });
  Buntest.test("an object of arrays zips by index", () => {
    let rows = Stdlib_Option.getExn(ApiRows.rows(JSON.parse(`{"time":["h1","h2","h3"],"temp":[20,21]}`), false), undefined);
    Buntest.expect(rows.length).toBe(3);
    Buntest.expect(names(rows[0])).toBe("time,temp");
    Buntest.expect(value(rows[1], "temp")).toEqual("21");
    Buntest.expect(value(rows[2], "temp")).toEqual("");
  });
  Buntest.test("an object of scalars is one row, or pairs when asked", () => {
    let one = Stdlib_Option.getExn(ApiRows.rows(JSON.parse(`{"USD":1.08,"GBP":0.85}`), false), undefined);
    Buntest.expect(one.length).toBe(1);
    let pairs = Stdlib_Option.getExn(ApiRows.rows(JSON.parse(`{"USD":1.08,"GBP":0.85}`), true), undefined);
    Buntest.expect(pairs.length).toBe(2);
    Buntest.expect(value(pairs[0], "key")).toEqual("USD");
    Buntest.expect(value(pairs[0], "value")).toEqual("1.08");
  });
  Buntest.test("a bare scalar is no rows: the key form reads those", () => {
    Buntest.expect(Stdlib_Option.isNone(ApiRows.rows(JSON.parse(`42`), false))).toBe(true);
    Buntest.expect(ApiRows.scalar(JSON.parse(`42`))).toEqual("42");
    Buntest.expect(Stdlib_Option.isNone(ApiRows.scalar(JSON.parse(`{"a":1}`)))).toBe(true);
  });
  Buntest.test("nested structures flatten to their JSON", () => {
    let rows = Stdlib_Option.getExn(ApiRows.rows(JSON.parse(`[{"a":{"b":1}}]`), false), undefined);
    Buntest.expect(value(rows[0], "a")).toEqual(`{"b":1}`);
  });
});

export {
  json,
  names,
  value,
}
/*  Not a pure module */
