// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Locale from "./Locale.res.mjs";
import * as Starter from "./Starter.res.mjs";
import * as Buntest from "bun:test";
import * as AppDocument from "./AppDocument.res.mjs";
import * as DocumentKey from "./DocumentKey.res.mjs";
import * as Frontmatter from "./Frontmatter.res.mjs";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as CollectionKey from "./CollectionKey.res.mjs";
import * as DirectiveScan from "./DirectiveScan.res.mjs";
import * as SpectrumIcons from "../generated/SpectrumIcons.res.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as DirectiveAttributes from "./DirectiveAttributes.res.mjs";

let document = `---
appId: grade-book
title: Grade Book
description: Class grades.
version: "1.0"
date: "2026-06-27"
---

# Body
`;

Buntest.describe("AppDocument.summary", () => {
  Buntest.test("reads the card from the frontmatter", () => {
    let card = AppDocument.summary("grade-book", document);
    Buntest.expect(card.title).toBe("Grade Book");
    Buntest.expect(card.description).toBe("Class grades.");
    Buntest.expect(card.version).toBe("1.0");
  });
  Buntest.test("falls back to the id when there is no title", () => {
    let card = AppDocument.summary("untitled-one", "# Just a heading");
    Buntest.expect(card.title).toBe("untitled-one");
    Buntest.expect(card.description).toBe("");
  });
});

Buntest.describe("AppDocument.declaredId", () => {
  Buntest.test("reads the id the document claims", () => {
    Buntest.expect(AppDocument.declaredId(document)).toEqual("grade-book");
  });
  Buntest.test("refuses an id this app would not address", () => {
    Buntest.expect(AppDocument.declaredId("---\nappId: Not An Id\n---\n")).toEqual(undefined);
    Buntest.expect(AppDocument.declaredId("no frontmatter")).toEqual(undefined);
  });
});

Buntest.describe("AppDocument.withId", () => {
  Buntest.test("sets the id without disturbing the other fields", () => {
    let renamed = AppDocument.withId(document, "registro");
    Buntest.expect(AppDocument.declaredId(renamed)).toEqual("registro");
    let card = AppDocument.summary("registro", renamed);
    Buntest.expect(card.title).toBe("Grade Book");
    Buntest.expect(card.date).toBe("2026-06-27");
  });
  Buntest.test("adds a frontmatter block to a document without one", () => {
    let stamped = AppDocument.withId("# Bare", "bare-app");
    Buntest.expect(AppDocument.declaredId(stamped)).toEqual("bare-app");
    Buntest.expect(Frontmatter.parse(stamped).body.includes("# Bare")).toBe(true);
  });
});

Buntest.describe("AppDocument.blank", () => {
  Buntest.test("starts an app that already carries its own identity", () => {
    let fresh = AppDocument.blank("new-app", "New app", "2026-08-10", "En");
    Buntest.expect(AppDocument.declaredId(fresh)).toEqual("new-app");
    let card = AppDocument.summary("new-app", fresh);
    Buntest.expect(card.title).toBe("New app");
    Buntest.expect(card.date).toBe("2026-08-10");
  });
});

Buntest.describe("AppDocument.summary icon", () => {
  Buntest.test("takes the icon the document names", () => {
    Buntest.expect(AppDocument.summary("a", "---\nicon: calendar\n---\n\nText").icon).toBe("calendar");
  });
  Buntest.test("refuses a name Spectrum does not have", () => {
    Buntest.expect(AppDocument.summary("a", "---\nicon: unicorn\n---\n\nText").icon).toBe("");
    Buntest.expect(AppDocument.summary("a", "---\ntitle: No icon\n---\n\nText").icon).toBe("");
    Buntest.expect(AppDocument.summary("a", "Text with no frontmatter at all").icon).toBe("");
  });
  Buntest.test("the default is an icon Spectrum actually has", () => {
    Buntest.expect(SpectrumIcons.all.includes(AppDocument.defaultIcon)).toBe(true);
  });
});

Buntest.describe("AppDocument.summary chat", () => {
  Buntest.test("only the explicit yeses enable it", () => {
    Buntest.expect(AppDocument.summary("a", "---\nchat: true\n---\n\nText").chat).toBe(true);
    Buntest.expect(AppDocument.summary("a", "---\nchat: yes\n---\n\nText").chat).toBe(true);
    Buntest.expect(AppDocument.summary("a", "---\nchat: on\n---\n\nText").chat).toBe(true);
    Buntest.expect(AppDocument.summary("a", "---\nchat: \"1\"\n---\n\nText").chat).toBe(true);
    Buntest.expect(AppDocument.summary("a", "---\nchat: TRUE\n---\n\nText").chat).toBe(true);
  });
  Buntest.test("everything else is no", () => {
    Buntest.expect(AppDocument.summary("a", "---\nchat: false\n---\n\nText").chat).toBe(false);
    Buntest.expect(AppDocument.summary("a", "---\nchat: maybe\n---\n\nText").chat).toBe(false);
    Buntest.expect(AppDocument.summary("a", "---\ntitle: No chat\n---\n\nText").chat).toBe(false);
    Buntest.expect(AppDocument.summary("a", "Text with no frontmatter at all").chat).toBe(false);
  });
});

Buntest.describe("AppDocument.order", () => {
  Buntest.test("newest first, then by title", () => {
    let ordered = AppDocument.order([
      {
        id: "b",
        title: "Beta",
        description: "",
        author: "",
        date: "2026-01-01",
        version: "",
        icon: "",
        chat: false
      },
      {
        id: "c",
        title: "Alpha",
        description: "",
        author: "",
        date: "2026-05-01",
        version: "",
        icon: "",
        chat: false
      },
      {
        id: "a",
        title: "Zeta",
        description: "",
        author: "",
        date: "2026-05-01",
        version: "",
        icon: "",
        chat: false
      }
    ]).map(summary => summary.id);
    Buntest.expect(ordered.join(",")).toBe("c,a,b");
  });
});

Buntest.describe("DocumentKey", () => {
  Buntest.test("addresses a document without colliding with a collection", () => {
    Buntest.expect(DocumentKey.of_("grade-book")).toBe("doc/grade-book");
    Buntest.expect(DocumentKey.isDocument(CollectionKey.of_("grade-book", "voti"))).toBe(false);
    Buntest.expect(DocumentKey.isDocument(DocumentKey.of_("grade-book"))).toBe(true);
  });
  Buntest.test("reads back only keys carrying a valid id", () => {
    Buntest.expect(DocumentKey.idOf("doc/grade-book")).toEqual("grade-book");
    Buntest.expect(DocumentKey.idOf("doc/Not An Id")).toEqual(undefined);
    Buntest.expect(DocumentKey.idOf("preferences")).toEqual(undefined);
  });
});

Buntest.describe("Starter", () => {
  Buntest.test("the welcome app is written in the chosen language", () => {
    Locale.all.forEach(locale => {
      let text = Starter.of_(locale);
      let document = AppDocument.welcome(locale, "2026-08-10");
      Buntest.expect(document.includes(text.welcomeTitle)).toBe(true);
      Buntest.expect(document.includes(text.saveButton)).toBe(true);
      Buntest.expect(Stdlib_Option.isSome(Frontmatter.parse(document).meta)).toBe(true);
    });
  });
  Buntest.test("a new app is written in the chosen language", () => {
    Locale.all.forEach(locale => {
      let text = Starter.of_(locale);
      let document = AppDocument.blank("x", "X", "2026-08-10", locale);
      Buntest.expect(document.includes(text.addHeading)).toBe(true);
      Buntest.expect(document.includes(text.addButton)).toBe(true);
    });
  });
  Buntest.test("the document declares the language it was written in", () => {
    let document = AppDocument.welcome("It", "2026-08-10");
    let meta = Stdlib_Option.getOrThrow(Frontmatter.parse(document).meta, undefined);
    Buntest.expect(Frontmatter.get(meta, "lang")).toEqual("it");
  });
  Buntest.test("every icon the welcome app names exists", () => {
    let body = Frontmatter.parse(AppDocument.welcome("En", "2026-08-10")).body;
    let named = Stdlib_Array.filterMap(DirectiveScan.scan(body), occurrence => DirectiveAttributes.attribute(occurrence.attributes, "icon"));
    Buntest.expect(named.length).toBe(2);
    named.forEach(icon => {
      Buntest.expect(SpectrumIcons.all.includes(icon)).toBe(true);
    });
  });
  Buntest.test("every container in the welcome app is terminated", () => {
    Locale.all.forEach(locale => {
      let body = Frontmatter.parse(AppDocument.welcome(locale, "2026-08-10")).body;
      let containers = DirectiveScan.scan(body).filter(occurrence => occurrence.form === "Container");
      Buntest.expect(containers.length).toBe(2);
    });
  });
});

export {
  document,
}
/*  Not a pure module */
