// Generated by ReScript, PLEASE EDIT WITH CARE

import * as AppId from "./AppId.res.mjs";
import * as Locale from "./Locale.res.mjs";
import * as Starter from "./Starter.res.mjs";
import * as Frontmatter from "./Frontmatter.res.mjs";
import * as SpectrumIcons from "../generated/SpectrumIcons.res.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_string from "@rescript/runtime/lib/es6/Primitive_string.js";

function truthy(value) {
  let match = value.trim().toLowerCase();
  switch (match) {
    case "1" :
    case "on" :
    case "true" :
    case "yes" :
      return true;
    default:
      return false;
  }
}

let defaultIcon = "app";

function field(meta, key) {
  return Stdlib_Option.getOr(Stdlib_Option.flatMap(meta, fields => Frontmatter.get(fields, key)), "");
}

function summary(id, source) {
  let meta = Frontmatter.parse(source).meta;
  let title = field(meta, "title");
  let named = field(meta, "icon");
  return {
    id: id,
    title: title === "" ? id : title,
    description: field(meta, "description"),
    author: field(meta, "author"),
    date: field(meta, "date"),
    version: field(meta, "version"),
    icon: SpectrumIcons.all.includes(named) ? named : "",
    chat: truthy(field(meta, "chat"))
  };
}

function declaredId(source) {
  let meta = Frontmatter.parse(source).meta;
  if (meta === undefined) {
    return;
  }
  let declared = Frontmatter.get(meta, "appId");
  if (declared !== undefined && AppId.isValid(declared)) {
    return declared;
  }
}

function withId(source, id) {
  let parsed = Frontmatter.parse(source);
  let meta = Stdlib_Option.getOr(parsed.meta, Frontmatter.empty);
  return Frontmatter.serialize(Frontmatter.setField(meta, "appId", id), parsed.body);
}

function blank(id, title, date, locale) {
  let text = Starter.of_(locale);
  return Frontmatter.serialize(Frontmatter.setField(Frontmatter.setField(Frontmatter.setField(Frontmatter.setField(Frontmatter.setField(Frontmatter.setField(Frontmatter.setField(Frontmatter.empty, "appId", id), "title", title), "description", ""), "icon", defaultIcon), "lang", Locale.toTag(locale)), "version", "1.0"), "date", date), "# " + title + "\n\n" + text.starterIntro + "\n\n## " + text.addHeading + `

::form{path="items"}
::input{field="name" legend="` + text.nameField + `"}
::input{field="note" legend="` + text.noteField + `"}
::save{label="` + text.addButton + `"}
::/form

::if-empty{path="items"}
` + text.emptyItems + `
::/if-empty

::if-any{path="items"}
:count{path="items"} ` + text.savedItems + `

::list{path="items" deletable editform}
**{name}** — {note}
::/list
::/if-any
`);
}

let welcomeId = "welcome";

function welcome(locale, date) {
  let text = Starter.of_(locale);
  return Frontmatter.serialize(Frontmatter.setField(Frontmatter.setField(Frontmatter.setField(Frontmatter.setField(Frontmatter.setField(Frontmatter.setField(Frontmatter.setField(Frontmatter.empty, "appId", welcomeId), "title", text.welcomeTitle), "description", text.welcomeDescription), "icon", "hand"), "lang", Locale.toTag(locale)), "version", "1.0"), "date", date), `::page{title="` + text.reactiveHeading + `" icon="gauge3"}
# ` + text.welcomeTitle + `

` + text.intro + `

` + text.openHint + `

## ` + text.reactiveHeading + `

` + text.reactiveIntro + `

::slider[volume]{min="0" max="100" value="50" label-visibility="text"}

` + text.volumeNow + ` :value[v]{ref="#volume"}

::progress-bar{label="Volume" progress="#volume"}

` + text.refRule + `

## ` + text.componentsHeading + `

` + text.componentsIntro + `

::badge[Spectrum]{variant="accent"}

::accordion{density="compact"}
::accordion-item{label="` + text.nestingQuestion + `" open}
` + text.nestingAnswer + `
::/accordion-item
::/accordion
::/page

::page{title="` + text.dataHeading + `" icon="data"}
## ` + text.dataHeading + `

` + text.dataIntro + `

::form{path="notes"}
::input{field="title" legend="` + text.noteField + `" required}
::input{field="who" legend="` + text.whoField + `" help="` + text.whoHelp + `"}
::save{label="` + text.saveButton + `"}
::/form

::if-empty{path="notes"}
` + text.emptyNotes + `
::/if-empty

::if-any{path="notes"}
:count{path="notes"} ` + text.savedNotes + `

::list{path="notes" deletable editform}
**{title}** — {who} · {createdAt}
::/list

### ` + text.viewsHeading + `

` + text.boardIntro + `

::board{path="notes" group-by="who" min="11rem" editform}
**{title}**
::/board

### ` + text.chooseHeading + `

` + text.chooseIntro + `

::choose[chi]{path="notes" field="who" label="who" legend="` + text.chooseLegend + `"}

` + text.chooseAnswer + ` :value[chosen]{ref="#chi"}

::list{path="notes" filter="who=#chi"}
**{title}** · {createdAt}
::/list
::/if-any

## ` + text.markdownHeading + `

` + text.markdownIntro + `

| Feature | Status |
| --- | --- |
| KaTeX | yes |
| Mermaid | yes |

$$
\\int_{0}^{\\infty} e^{-x^2}\\,dx = \\frac{\\sqrt{\\pi}}{2}
$$
::/page
`);
}

function order(summaries) {
  return summaries.toSorted((a, b) => {
    if (a.date === b.date) {
      return Primitive_string.compare(a.title.toLowerCase(), b.title.toLowerCase());
    } else {
      return Primitive_string.compare(b.date, a.date);
    }
  });
}

export {
  defaultIcon,
  summary,
  declaredId,
  withId,
  welcomeId,
  welcome,
  blank,
  order,
}
/* No side effect */
