// Generated by ReScript, PLEASE EDIT WITH CARE

import * as AppId from "./AppId.res.mjs";
import * as AppFile from "./AppFile.res.mjs";
import * as Buntest from "bun:test";
import * as Frontmatter from "./Frontmatter.res.mjs";

function document(id, title, param) {
  let meta = id !== undefined ? Frontmatter.setField(Frontmatter.empty, "appId", id) : Frontmatter.empty;
  let fields = title !== undefined ? Frontmatter.setField(meta, "title", title) : meta;
  return Frontmatter.serialize(fields, "# Body\n");
}

Buntest.describe("AppFile.name", () => {
  Buntest.test("is the id, which is already safe for a filename", () => {
    Buntest.expect(AppFile.name("registro-voti")).toBe("registro-voti.md");
  });
});

Buntest.describe("AppFile.isDocument", () => {
  Buntest.test("accepts markdown, whatever the case", () => {
    Buntest.expect(AppFile.isDocument("app.md")).toBe(true);
    Buntest.expect(AppFile.isDocument("App.MARKDOWN")).toBe(true);
  });
  Buntest.test("refuses anything else", () => {
    Buntest.expect(AppFile.isDocument("app.json")).toBe(false);
    Buntest.expect(AppFile.isDocument("app")).toBe(false);
  });
});

Buntest.describe("AppFile.idFor", () => {
  Buntest.test("keeps the declared id when nothing else has it", () => {
    let source = document("shopping", undefined, undefined);
    Buntest.expect(AppFile.idFor(source, ["welcome"], "app")).toBe("shopping");
    Buntest.expect(AppFile.isCopy(source, "shopping")).toBe(false);
  });
  Buntest.test("becomes a copy rather than overwriting", () => {
    let source = document("shopping", undefined, undefined);
    let id = AppFile.idFor(source, ["shopping"], "app");
    Buntest.expect(id === "shopping").toBe(false);
    Buntest.expect(AppId.isValid(id)).toBe(true);
    Buntest.expect(AppFile.isCopy(source, id)).toBe(true);
  });
  Buntest.test("falls back to the title when the file declares no id", () => {
    let source = document(undefined, "Registro voti", undefined);
    Buntest.expect(AppFile.idFor(source, [], "app")).toBe("registro-voti");
  });
  Buntest.test("falls back to the given name when there is nothing to go on", () => {
    Buntest.expect(AppFile.idFor("# Just a heading\n", [], "untitled")).toBe("untitled");
  });
  Buntest.test("refuses an id that is not a valid one", () => {
    let source = document("../../etc", "Escape", undefined);
    let id = AppFile.idFor(source, [], "app");
    Buntest.expect(AppId.isValid(id)).toBe(true);
    Buntest.expect(id).toBe("escape");
  });
});

export {
  document,
}
/*  Not a pure module */
