// Generated by ReScript, PLEASE EDIT WITH CARE

import * as AppId from "./AppId.res.mjs";
import * as AppDocument from "./AppDocument.res.mjs";
import * as Frontmatter from "./Frontmatter.res.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

function name(id) {
  return id + ".md";
}

function isDocument(filename) {
  let lower = filename.toLowerCase();
  if (lower.endsWith(".md")) {
    return true;
  } else {
    return lower.endsWith(".markdown");
  }
}

function idFor(source, taken, fallback) {
  let declared = AppDocument.declaredId(source);
  if (declared !== undefined) {
    if (taken.includes(declared)) {
      return AppId.unique(declared, taken);
    } else {
      return declared;
    }
  }
  let title = Stdlib_Option.getOr(Stdlib_Option.flatMap(Frontmatter.parse(source).meta, meta => Frontmatter.get(meta, "title")), "");
  return AppId.unique(title === "" ? fallback : title, taken);
}

function isCopy(source, id) {
  let declared = AppDocument.declaredId(source);
  if (declared !== undefined) {
    return declared !== id;
  } else {
    return false;
  }
}

let accept = ".md,.markdown,text/markdown";

export {
  name,
  accept,
  isDocument,
  idFor,
  isCopy,
}
/* No side effect */
