// Generated by ReScript, PLEASE EDIT WITH CARE


function isAllowed(character) {
  if (character >= "a" && character <= "z" || character >= "0" && character <= "9") {
    return true;
  } else {
    return character === "-";
  }
}

function isValid(candidate) {
  if (candidate !== "" && candidate.length <= 64 && !candidate.startsWith("-") && !candidate.endsWith("-") && !candidate.includes("--")) {
    return candidate.split("").every(isAllowed);
  } else {
    return false;
  }
}

function slug(raw) {
  let lowered = raw.toLowerCase();
  let replaced = lowered.split("").map(character => {
    if (isAllowed(character)) {
      return character;
    } else {
      return "-";
    }
  }).join("");
  return replaced.split("-").filter(part => part !== "").join("-").slice(0, 64).split("-").filter(part => part !== "").join("-");
}

let fallback = "app";

function of_(raw) {
  let value = slug(raw);
  if (value === "") {
    return fallback;
  } else {
    return value;
  }
}

function unique(desired, taken) {
  let base = of_(desired);
  let _suffix = 1;
  while (true) {
    let suffix = _suffix;
    let candidate = suffix === 1 ? base : base + "-" + suffix.toString();
    if (!taken.includes(candidate)) {
      return candidate;
    }
    _suffix = suffix + 1 | 0;
    continue;
  };
}

let maxLength = 64;

export {
  maxLength,
  isValid,
  of_,
  unique,
  fallback,
}
/* No side effect */
