// Generated by ReScript, PLEASE EDIT WITH CARE

import * as AppId from "./AppId.res.mjs";
import * as Buntest from "bun:test";

Buntest.describe("AppId.of_", () => {
  Buntest.test("slugs a title", () => {
    Buntest.expect(AppId.of_("Grade Book")).toBe("grade-book");
    Buntest.expect(AppId.of_("Registro   voti 2026")).toBe("registro-voti-2026");
  });
  Buntest.test("never yields an id the validator would reject", () => {
    [
      "",
      "---",
      "!!!",
      "  ",
      "-leading",
      "trailing-",
      "a--b",
      "ÀÈÌ"
    ].forEach(raw => {
      Buntest.expect(AppId.isValid(AppId.of_(raw))).toBe(true);
    });
  });
  Buntest.test("falls back rather than returning nothing", () => {
    Buntest.expect(AppId.of_("???")).toBe("app");
  });
});

Buntest.describe("AppId.isValid", () => {
  Buntest.test("accepts what a link can carry", () => {
    Buntest.expect(AppId.isValid("grade-book")).toBe(true);
    Buntest.expect(AppId.isValid("a1")).toBe(true);
  });
  Buntest.test("refuses anything that could escape its namespace", () => {
    Buntest.expect(AppId.isValid("../other")).toBe(false);
    Buntest.expect(AppId.isValid("app/one")).toBe(false);
    Buntest.expect(AppId.isValid("Grade")).toBe(false);
    Buntest.expect(AppId.isValid("")).toBe(false);
    Buntest.expect(AppId.isValid("-x")).toBe(false);
    Buntest.expect(AppId.isValid("x-")).toBe(false);
    Buntest.expect(AppId.isValid("a--b")).toBe(false);
  });
  Buntest.test("refuses an id longer than the limit", () => {
    Buntest.expect(AppId.isValid("a".repeat(AppId.maxLength))).toBe(true);
    Buntest.expect(AppId.isValid("a".repeat(AppId.maxLength + 1 | 0))).toBe(false);
  });
});

Buntest.describe("AppId.unique", () => {
  Buntest.test("keeps the plain id when it is free", () => {
    Buntest.expect(AppId.unique("Grade Book", ["other"])).toBe("grade-book");
  });
  Buntest.test("counts up past every id already taken", () => {
    Buntest.expect(AppId.unique("Grade Book", ["grade-book"])).toBe("grade-book-2");
    Buntest.expect(AppId.unique("Grade Book", [
      "grade-book",
      "grade-book-2"
    ])).toBe("grade-book-3");
  });
});

/*  Not a pure module */
