// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Buntest from "bun:test";
import * as CatalogUpdate from "./CatalogUpdate.res.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

function app(id, titleOpt, versionOpt) {
  let title = titleOpt !== undefined ? titleOpt : "";
  let version = versionOpt !== undefined ? versionOpt : "";
  return {
    id: id,
    title: title === "" ? id : title,
    description: "",
    author: "",
    date: "",
    version: version,
    icon: "",
    chat: false
  };
}

function entry(id, titleOpt, versionOpt) {
  let title = titleOpt !== undefined ? titleOpt : "";
  let version = versionOpt !== undefined ? versionOpt : "";
  return {
    id: id,
    title: title === "" ? id : title,
    version: version
  };
}

Buntest.describe("CatalogUpdate.compare", () => {
  Buntest.test("orders the segments as numbers, not as text", () => {
    Buntest.expect(CatalogUpdate.compare("1.10", "1.9") > 0).toBe(true);
    Buntest.expect(CatalogUpdate.compare("2.0", "10.0") < 0).toBe(true);
  });
  Buntest.test("a missing segment is zero", () => {
    Buntest.expect(CatalogUpdate.compare("2", "2.0")).toBe(0);
    Buntest.expect(CatalogUpdate.compare("2.0.0", "2")).toBe(0);
    Buntest.expect(CatalogUpdate.compare("2.0.1", "2") > 0).toBe(true);
  });
  Buntest.test("segments that are not numbers compare as text", () => {
    Buntest.expect(CatalogUpdate.compare("1.0-beta", "1.0-alpha") > 0).toBe(true);
    Buntest.expect(CatalogUpdate.compare("1.0", "1.0")).toBe(0);
  });
  Buntest.test("surrounding space does not make two versions different", () => {
    Buntest.expect(CatalogUpdate.compare(" 3.1 ", "3.1")).toBe(0);
  });
});

Buntest.describe("CatalogUpdate.isNewer", () => {
  Buntest.test("only strictly newer counts", () => {
    Buntest.expect(CatalogUpdate.isNewer("1.0", "1.1")).toBe(true);
    Buntest.expect(CatalogUpdate.isNewer("1.1", "1.1")).toBe(false);
    Buntest.expect(CatalogUpdate.isNewer("2.0", "1.9")).toBe(false);
  });
  Buntest.test("an unwritten version on either side answers no", () => {
    Buntest.expect(CatalogUpdate.isNewer("", "1.0")).toBe(false);
    Buntest.expect(CatalogUpdate.isNewer("1.0", "")).toBe(false);
    Buntest.expect(CatalogUpdate.isNewer("", "")).toBe(false);
  });
});

Buntest.describe("CatalogUpdate.offers", () => {
  let installed = [
    app("orario-scolastico", "Orario", "2.0"),
    app("segreteria", undefined, "1.4"),
    app("mia-app", undefined, "1.0"),
    app("senza-versione", undefined, undefined)
  ];
  let published = [
    entry("orario-scolastico", "Orario Scolastico", "3.0"),
    entry("segreteria", undefined, "1.4"),
    entry("inclusione", undefined, "2.0"),
    entry("senza-versione", undefined, "1.0")
  ];
  let found = CatalogUpdate.offers(installed, published);
  Buntest.test("offers only what is here and published newer", () => {
    Buntest.expect(found.map(o => o.id).join(",")).toBe("orario-scolastico");
  });
  Buntest.test("carries both titles, because the app may have been renamed", () => {
    let offer = found[0];
    Buntest.expect(offer.installedTitle).toBe("Orario");
    Buntest.expect(offer.publishedTitle).toBe("Orario Scolastico");
    Buntest.expect(offer.installed + " → " + offer.published).toBe("2.0 → 3.0");
  });
  Buntest.test("an app the catalogue does not publish is left alone", () => {
    Buntest.expect(Stdlib_Option.isNone(CatalogUpdate.offerFor("mia-app", found))).toBe(true);
  });
  Buntest.test("everything current is an empty answer, not an error", () => {
    Buntest.expect(CatalogUpdate.offers(installed, []).length).toBe(0);
  });
  Buntest.test("the published title falls back to the installed one when it is empty", () => {
    let offer = CatalogUpdate.offers([app("x", "Mia", "1.0")], [{
          id: "x",
          title: "",
          version: "2.0"
        }])[0];
    Buntest.expect(offer.publishedTitle).toBe("Mia");
  });
});

export {
  app,
  entry,
}
/*  Not a pure module */
