// Generated by ReScript, PLEASE EDIT WITH CARE


let segment = "c";

let path = "/" + segment;

function documentPath(id) {
  return "/app/" + id + ".md";
}

function of_(origin, id) {
  return origin + path + "/" + id;
}

let indexPath = "/app/index.json";

export {
  segment,
  path,
  documentPath,
  indexPath,
  of_,
}
/* No side effect */
