// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Numeric from "./Numeric.res.mjs";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

function compare(left, right) {
  let left$1 = left.trim().split(".");
  let right$1 = right.trim().split(".");
  let _index = 0;
  while (true) {
    let index = _index;
    let a = left$1.length;
    let b = right$1.length;
    let count = a > b ? a : b;
    if (index >= count) {
      return 0;
    }
    let a$1 = Stdlib_Option.getOr(left$1.at(index), "0");
    let b$1 = Stdlib_Option.getOr(right$1.at(index), "0");
    let match = Numeric.parse(a$1);
    let match$1 = Numeric.parse(b$1);
    let verdict;
    let exit = 0;
    if (match !== undefined && match$1 !== undefined) {
      verdict = match === match$1 ? 0 : (
          match < match$1 ? -1 : 1
        );
    } else {
      exit = 1;
    }
    if (exit === 1) {
      verdict = a$1 === b$1 ? 0 : (
          a$1 < b$1 ? -1 : 1
        );
    }
    if (verdict !== 0) {
      return verdict;
    }
    _index = index + 1 | 0;
    continue;
  };
}

function isNewer(installed, published) {
  if (installed.trim() !== "" && published.trim() !== "") {
    return compare(published, installed) > 0;
  } else {
    return false;
  }
}

function offers(installed, published) {
  return Stdlib_Array.filterMap(installed, app => Stdlib_Option.flatMap(published.find(entry => entry.id === app.id), entry => {
    if (isNewer(app.version, entry.version)) {
      return {
        id: app.id,
        installedTitle: app.title,
        publishedTitle: entry.title === "" ? app.title : entry.title,
        installed: app.version,
        published: entry.version
      };
    }
  }));
}

function offerFor(id, offers) {
  return offers.find(offer => offer.id === id);
}

export {
  compare,
  isNewer,
  offers,
  offerFor,
}
/* Numeric Not a pure module */
