// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Contrast from "./Contrast.res.mjs";
import * as Buntest from "bun:test";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

function round(value) {
  return Math.round(value * 100.0) / 100.0;
}

function ratioOf(a, b) {
  return Stdlib_Option.getOr(Stdlib_Option.map(Contrast.between(a, b), round), -1.0);
}

Buntest.describe("Contrast.parseHex", () => {
  Buntest.test("reads a full hex colour with or without the hash", () => {
    Buntest.expect(Stdlib_Option.isSome(Contrast.parseHex("#ffffff"))).toBe(true);
    Buntest.expect(Stdlib_Option.isSome(Contrast.parseHex("ffffff"))).toBe(true);
  });
  Buntest.test("is case-insensitive", () => {
    Buntest.expect(ratioOf("#FFFFFF", "#000000")).toBe(21.0);
  });
  Buntest.test("rejects shorthand and malformed values", () => {
    Buntest.expect(Stdlib_Option.isNone(Contrast.parseHex("#fff"))).toBe(true);
    Buntest.expect(Stdlib_Option.isNone(Contrast.parseHex("#gggggg"))).toBe(true);
    Buntest.expect(Stdlib_Option.isNone(Contrast.parseHex(""))).toBe(true);
  });
});

Buntest.describe("Contrast.ratio", () => {
  Buntest.test("black on white is 21:1", () => {
    Buntest.expect(ratioOf("#000000", "#ffffff")).toBe(21.0);
  });
  Buntest.test("a colour against itself is 1:1", () => {
    Buntest.expect(ratioOf("#65c3c8", "#65c3c8")).toBe(1.0);
  });
  Buntest.test("is symmetric", () => {
    Buntest.expect(ratioOf("#2f8084", "#ffffff")).toBe(ratioOf("#ffffff", "#2f8084"));
  });
  Buntest.test("agrees with the known 4.5:1 grey", () => {
    Buntest.expect(ratioOf("#767676", "#ffffff") >= 4.5).toBe(true);
    Buntest.expect(ratioOf("#777777", "#ffffff") >= 4.5).toBe(false);
  });
});

Buntest.describe("Contrast.meets", () => {
  Buntest.test("accepts and rejects against the AA threshold", () => {
    Buntest.expect(Contrast.meets("#767676", "#ffffff", Contrast.normalText)).toBe(true);
    Buntest.expect(Contrast.meets("#999999", "#ffffff", Contrast.normalText)).toBe(false);
  });
  Buntest.test("an unparseable colour never passes", () => {
    Buntest.expect(Contrast.meets("nope", "#ffffff", 1.0)).toBe(false);
  });
});

export {
  round,
  ratioOf,
}
/*  Not a pure module */
