// Generated by ReScript, PLEASE EDIT WITH CARE


function digitValue(character) {
  let value = "0123456789abcdef".indexOf(character.toLowerCase());
  if (value !== -1) {
    return value;
  }
}

function channel(value, offset) {
  let match = digitValue(value.charAt(offset));
  let match$1 = digitValue(value.charAt(offset + 1 | 0));
  if (match !== undefined && match$1 !== undefined) {
    return (match << 4) + match$1 | 0;
  }
}

function parseHex(raw) {
  let value = raw.trim().startsWith("#") ? raw.trim().slice(1, raw.trim().length) : raw.trim();
  if (value.length !== 6) {
    return;
  }
  let match = channel(value, 0);
  let match$1 = channel(value, 2);
  let match$2 = channel(value, 4);
  if (match !== undefined && match$1 !== undefined && match$2 !== undefined) {
    return {
      red: match,
      green: match$1,
      blue: match$2
    };
  }
}

function linearise(value) {
  let channel = value / 255.0;
  if (channel <= 0.03928) {
    return channel / 12.92;
  } else {
    return Math.pow((channel + 0.055) / 1.055, 2.4);
  }
}

function relativeLuminance(colour) {
  return 0.2126 * linearise(colour.red) + 0.7152 * linearise(colour.green) + 0.0722 * linearise(colour.blue);
}

function ratio(a, b) {
  let first = relativeLuminance(a);
  let second = relativeLuminance(b);
  let lighter = Math.max(first, second);
  let darker = Math.min(first, second);
  return (lighter + 0.05) / (darker + 0.05);
}

function between(foreground, background) {
  let match = parseHex(foreground);
  let match$1 = parseHex(background);
  if (match !== undefined && match$1 !== undefined) {
    return ratio(match, match$1);
  }
}

function meets(foreground, background, threshold) {
  let measured = between(foreground, background);
  if (measured !== undefined) {
    return measured >= threshold;
  } else {
    return false;
  }
}

let normalText = 4.5;

let largeText = 3.0;

let nonText = 3.0;

export {
  normalText,
  largeText,
  nonText,
  parseHex,
  relativeLuminance,
  ratio,
  between,
  meets,
}
/* No side effect */
