// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Buntest from "bun:test";
import * as CssLength from "./CssLength.res.mjs";

Buntest.describe("CssLength.normalise", () => {
  Buntest.test("un numero nudo sono pixel", () => {
    Buntest.expect(CssLength.normalise("520")).toEqual("520px");
    Buntest.expect(CssLength.normalise("0")).toEqual("0px");
    Buntest.expect(CssLength.normalise("32.5")).toEqual("32.5px");
    Buntest.expect(CssLength.normalise("  300  ")).toEqual("300px");
  });
  Buntest.test("una lunghezza già scritta passa com'è", () => {
    Buntest.expect(CssLength.normalise("520px")).toEqual("520px");
    Buntest.expect(CssLength.normalise("18rem")).toEqual("18rem");
    Buntest.expect(CssLength.normalise("50vh")).toEqual("50vh");
    Buntest.expect(CssLength.normalise("100%")).toEqual("100%");
    Buntest.expect(CssLength.normalise("calc(100% - 2rem)")).toEqual("calc(100% - 2rem)");
  });
  Buntest.test("niente non è una lunghezza", () => {
    Buntest.expect(CssLength.normalise("")).toEqual(undefined);
    Buntest.expect(CssLength.normalise("   ")).toEqual(undefined);
  });
  Buntest.test("non giudica: quello che non è una lunghezza lo rifiuta il CSS", () => {
    Buntest.expect(CssLength.normalise("rosso")).toEqual("rosso");
    Buntest.expect(CssLength.normalise("18rem; background: url(x)")).toEqual("18rem; background: url(x)");
  });
  Buntest.test("un numero con l'unità attaccata non viene toccato due volte", () => {
    Buntest.expect(CssLength.normalise("1e3")).toEqual("1e3");
    Buntest.expect(CssLength.normalise("-40")).toEqual("-40");
  });
});

/*  Not a pure module */
