// Generated by ReScript, PLEASE EDIT WITH CARE


function normalise(value) {
  let trimmed = value.trim();
  if (trimmed === "") {
    return;
  } else if (/^\d+(\.\d+)?$/.test(trimmed)) {
    return trimmed + "px";
  } else {
    return trimmed;
  }
}

export {
  normalise,
}
/* No side effect */
