// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Collection from "./Collection.res.mjs";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

let separator = ",";

let newline = "\r\n";

function needsQuotes(value) {
  if (value.includes(separator) || value.includes("\"") || value.includes("\n")) {
    return true;
  } else {
    return value.includes("\r");
  }
}

function cell(value) {
  if (needsQuotes(value)) {
    return "\"" + value.replaceAll("\"", "\"\"") + "\"";
  } else {
    return value;
  }
}

function columns(records) {
  return Stdlib_Array.reduce(records, [], (found, record) => Stdlib_Array.reduce(record.fields, found, (found, field) => {
    if (found.includes(field.name)) {
      return found;
    } else {
      return found.concat([field.name]);
    }
  }));
}

function encode(collection) {
  let fields = columns(collection.records);
  let header = ["id"].concat(fields).map(cell).join(separator);
  let rows = collection.records.map(record => ["id"].concat(fields).map(name => {
    if (name === "id") {
      return cell(record.id);
    } else {
      return cell(Stdlib_Option.getOr(Collection.field(record, name), ""));
    }
  }).join(separator));
  return [header].concat(rows).join(newline) + newline;
}

function parse(text) {
  let rows = [];
  let row = [];
  let field = {
    contents: ""
  };
  let quoted = {
    contents: false
  };
  let started = {
    contents: false
  };
  let rowQuoted = {
    contents: false
  };
  let characters = text.split("");
  let closeField = () => {
    row.push(field.contents);
    field.contents = "";
    started.contents = true;
  };
  let closeRow = () => {
    closeField();
    if (row.length !== 1 || row[0].trim() !== "" || rowQuoted.contents) {
      rows.push(row.slice());
    }
    rowQuoted.contents = false;
    let length = row.length;
    row.splice(0, length);
    started.contents = false;
  };
  let walk = _index => {
    while (true) {
      let index = _index;
      let character = characters.at(index);
      if (character === undefined) {
        if (field.contents !== "" || started.contents || row.length !== 0) {
          return closeRow();
        } else {
          return;
        }
      }
      if (quoted.contents) {
        if (character === "\"") {
          let match = characters.at(index + 1 | 0);
          if (match === "\"") {
            field.contents = field.contents + "\"";
            _index = index + 2 | 0;
            continue;
          }
          quoted.contents = false;
          _index = index + 1 | 0;
          continue;
        }
        field.contents = field.contents + character;
        _index = index + 1 | 0;
        continue;
      }
      if (character === "\"" && field.contents === "") {
        quoted.contents = true;
        started.contents = true;
        rowQuoted.contents = true;
        _index = index + 1 | 0;
        continue;
      }
      if (character === separator) {
        closeField();
        _index = index + 1 | 0;
        continue;
      }
      if (character === "\r") {
        _index = index + 1 | 0;
        continue;
      }
      if (character === "\n") {
        closeRow();
        _index = index + 1 | 0;
        continue;
      }
      field.contents = field.contents + character;
      started.contents = true;
      _index = index + 1 | 0;
      continue;
    };
  };
  walk(0);
  return rows;
}

function decode(text, makeId) {
  let rows = parse(text);
  if (rows.length === 0) {
    return [];
  }
  let header = rows[0];
  let idColumn = header.indexOf("id");
  let taken = [];
  return rows.slice(1).map(row => {
    let value = index => Stdlib_Option.getOr(row.at(index), "");
    let id = idColumn === -1 ? "" : value(idColumn).trim();
    let id$1 = id === "" || taken.includes(id) ? makeId(taken) : id;
    taken.push(id$1);
    return {
      id: id$1,
      fields: header.map((name, index) => [
        name,
        value(index)
      ]).filter(param => {
        let name = param[0];
        if (name !== "id") {
          return name.trim() !== "";
        } else {
          return false;
        }
      }).map(param => ({
        name: param[0],
        value: param[1]
      }))
    };
  });
}

export {
  columns,
  encode,
  parse,
  decode,
}
/* No side effect */
