// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Csv from "./Csv.res.mjs";
import * as Buntest from "bun:test";
import * as Collection from "./Collection.res.mjs";

function row(id, fields) {
  return {
    id: id,
    fields: fields.map(param => ({
      name: param[0],
      value: param[1]
    }))
  };
}

let collection = {
  records: [
    row("r1", [
      [
        "what",
        "Bread"
      ],
      [
        "price",
        "2.50"
      ]
    ]),
    row("r2", [
      [
        "what",
        "Milk"
      ],
      [
        "price",
        "1.20"
      ],
      [
        "note",
        "half a litre"
      ]
    ])
  ]
};

let counter = {
  contents: 0
};

function makeId(taken) {
  counter.contents = counter.contents + 1 | 0;
  let candidate = "new-" + counter.contents.toString();
  if (taken.includes(candidate)) {
    return candidate + "-x";
  } else {
    return candidate;
  }
}

Buntest.describe("Csv.encode", () => {
  Buntest.test("the header is every field any row has, ids first", () => {
    Buntest.expect(Csv.columns(collection.records).join(",")).toBe("what,price,note");
    Buntest.expect(Csv.encode(collection).split("\r\n")[0]).toBe("id,what,price,note");
  });
  Buntest.test("a row with nothing in a column leaves it empty", () => {
    let line = Csv.encode(collection).split("\r\n")[1];
    Buntest.expect(line).toBe("r1,Bread,2.50,");
  });
  Buntest.test("quotes what would otherwise break the grid", () => {
    let awkward = {
      records: [row("r1", [
          [
            "what",
            "Bread, sliced"
          ],
          [
            "note",
            "he said \"hello\""
          ],
          [
            "more",
            "two\nlines"
          ]
        ])]
    };
    let line = Csv.encode(awkward).split("\r\n")[1];
    Buntest.expect(line).toBe("r1,\"Bread, sliced\",\"he said \"\"hello\"\"\",\"two\nlines\"");
  });
});

Buntest.describe("Csv.decode", () => {
  Buntest.test("round-trips a collection, ids and all", () => {
    let back = Csv.decode(Csv.encode(collection), makeId);
    Buntest.expect(back.map(r => r.id).join(",")).toBe("r1,r2");
    let first = back[0];
    Buntest.expect(Collection.field(first, "what")).toEqual("Bread");
    Buntest.expect(Collection.field(first, "price")).toEqual("2.50");
    Buntest.expect(Collection.field(first, "note")).toEqual("");
  });
  Buntest.test("a file with no id column gets fresh ids", () => {
    let rows = Csv.decode("what,price\r\nBread,2.50\r\nMilk,1.20\r\n", makeId);
    Buntest.expect(rows.length).toBe(2);
    Buntest.expect(rows.every(r => r.id.startsWith("new-"))).toBe(true);
    Buntest.expect(Collection.field(rows[1], "what")).toEqual("Milk");
  });
  Buntest.test("reads what an editor produces: LF endings and no final newline", () => {
    let rows = Csv.decode("what\nBread\nMilk", makeId);
    Buntest.expect(rows.length).toBe(2);
    Buntest.expect(Collection.field(rows[1], "what")).toEqual("Milk");
  });
  Buntest.test("a comma inside quotes is a comma, not a column", () => {
    let rows = Csv.decode("what,note\r\n\"Bread, sliced\",\"he said \"\"hi\"\"\"\r\n", makeId);
    let first = rows[0];
    Buntest.expect(Collection.field(first, "what")).toEqual("Bread, sliced");
    Buntest.expect(Collection.field(first, "note")).toEqual("he said \"hi\"");
  });
  Buntest.test("a line break inside quotes stays inside the value", () => {
    let rows = Csv.decode("what\r\n\"two\nlines\"\r\n", makeId);
    Buntest.expect(rows.length).toBe(1);
    Buntest.expect(Collection.field(rows[0], "what")).toEqual("two\nlines");
  });
  Buntest.test("a quoted empty cell is a row, a blank line is not", () => {
    let rows = Csv.decode("what\r\n\"\"\r\n\r\n", makeId);
    Buntest.expect(rows.length).toBe(1);
    Buntest.expect(Collection.field(rows[0], "what")).toEqual("");
  });
  Buntest.test("an empty file is no rows, not one empty row", () => {
    Buntest.expect(Csv.decode("", makeId).length).toBe(0);
    Buntest.expect(Csv.decode("what,price\r\n", makeId).length).toBe(0);
  });
  Buntest.test("two rows claiming the same id do not become one", () => {
    let rows = Csv.decode("id,what\r\nr1,Bread\r\nr1,Milk\r\n", makeId);
    let ids = rows.map(r => r.id);
    Buntest.expect(ids.length).toBe(2);
    Buntest.expect(ids[0] === ids[1]).toBe(false);
  });
});

export {
  row,
  collection,
  counter,
  makeId,
}
/* collection Not a pure module */
