// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Int from "@rescript/runtime/lib/es6/Stdlib_Int.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

function inRange(value, from, to_) {
  let number = Stdlib_Int.fromString(value, undefined);
  if (number !== undefined && number >= from) {
    return number <= to_;
  } else {
    return false;
  }
}

function plausible(value) {
  let month = value.slice(5, 7);
  let day = value.slice(8, 10);
  if (inRange(month, 1, 12)) {
    return inRange(day, 1, 31);
  } else {
    return false;
  }
}

function classify(value) {
  let trimmed = value.trim();
  if (plausible(trimmed)) {
    if (new RegExp("^\\d{4}-\\d{2}-\\d{2}$").test(trimmed)) {
      return "Day";
    } else if (new RegExp("^\\d{4}-\\d{2}-\\d{2}[T ]\\d{2}:\\d{2}(?::\\d{2}(?:\\.\\d{1,6})?)?(?:Z|[+-]\\d{2}:\\d{2})?$").test(trimmed)) {
      return "Moment";
    } else {
      return;
    }
  }
}

function isDate(value) {
  return Stdlib_Option.isSome(classify(value));
}

export {
  classify,
  isDate,
}
/* No side effect */
