// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

function of_(text) {
  let hash = 0;
  for (let index = 0, index_finish = text.length; index < index_finish; ++index) {
    let code = Stdlib_Option.getOr(text.codePointAt(index), 0);
    hash = ((hash * 101 | 0) + code | 0) % 16777213;
  }
  return hash.toString(16);
}

function matches(text, recorded) {
  if (recorded !== "") {
    return of_(text) === recorded;
  } else {
    return false;
  }
}

export {
  of_,
  matches,
}
/* No side effect */
