// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as MarkdownSnippets from "./MarkdownSnippets.res.mjs";

function holdsContent(component) {
  if (component.slots.length !== 0) {
    return !component.attributes.some(a => {
      if (a.name === "value") {
        return true;
      } else {
        return a.name === "checked";
      }
    });
  } else {
    return false;
  }
}

function openBrace(line) {
  let index = line.lastIndexOf("{");
  if (index !== -1 && line.lastIndexOf("}") <= index) {
    return index;
  }
}

function directiveNameBefore(line, index) {
  let result = new RegExp(":+([A-Za-z][A-Za-z0-9_-]*)(?:\\[[^\\]]*\\])?\\s*$").exec(line.slice(0, index));
  if (!(result == null)) {
    return Stdlib_Option.flatMap(result.slice(1).at(0), value => value);
  }
}

function analyse(line) {
  let index = openBrace(line);
  if (index !== undefined) {
    let directive = directiveNameBefore(line, index);
    if (directive !== undefined) {
      let fragment = line.slice(index + 1 | 0, line.length);
      let index$1 = fragment.lastIndexOf(" ");
      let current = index$1 !== -1 ? fragment.slice(index$1 + 1 | 0, fragment.length) : fragment;
      let index$2 = current.indexOf("=");
      if (index$2 === -1) {
        return {
          TAG: "Attribute",
          directive: directive,
          prefix: current
        };
      }
      let attribute = current.slice(0, index$2);
      let raw = current.slice(index$2 + 1 | 0, current.length);
      let prefix = raw.startsWith("\"") || raw.startsWith("'") ? raw.slice(1, raw.length) : raw;
      return {
        TAG: "Value",
        directive: directive,
        attribute: attribute,
        prefix: prefix
      };
    } else {
      return {
        TAG: "Prose",
        _0: ""
      };
    }
  }
  let result = new RegExp("(?<!:)(:{1,2})([A-Za-z][A-Za-z0-9_-]*)?$").exec(line);
  if (result == null) {
    let result$1 = new RegExp("([A-Za-z0-9]*)$").exec(line);
    if (result$1 == null) {
      return {
        TAG: "Prose",
        _0: ""
      };
    } else {
      return {
        TAG: "Prose",
        _0: Stdlib_Option.getOr(Stdlib_Option.flatMap(result$1.slice(1).at(0), v => v), "")
      };
    }
  }
  let captured = index => Stdlib_Option.getOr(Stdlib_Option.flatMap(result.slice(1).at(index), v => v), "");
  return {
    TAG: "Directive",
    prefix: captured(1),
    colons: captured(0).length
  };
}

function matchesPrefix(candidate, prefix) {
  if (prefix === "") {
    return true;
  } else {
    return candidate.toLowerCase().startsWith(prefix.toLowerCase());
  }
}

function directiveInsert(component, colonsOpt) {
  let colons = colonsOpt !== undefined ? colonsOpt : 2;
  let name = component.directive;
  if (colons <= 1) {
    return [
      ":" + name + "[]{}",
      name.length + 2 | 0
    ];
  } else if (holdsContent(component)) {
    return [
      "::" + name + "{}\n\n::/" + name,
      name.length + 3 | 0
    ];
  } else {
    return [
      "::" + name + "[]{}",
      name.length + 3 | 0
    ];
  }
}

function completions(context, registry) {
  switch (context.TAG) {
    case "Directive" :
      let colons = context.colons;
      let prefix = context.prefix;
      return registry.filter(component => matchesPrefix(component.directive, prefix)).map(component => {
        let match = directiveInsert(component, colons);
        return {
          label: component.directive,
          detail: component.description === "" ? component.tag + " — " + component.attributes.length.toString() + " attributes" : component.description,
          insert: match[0],
          caret: match[1],
          back: colons
        };
      });
    case "Attribute" :
      let prefix$1 = context.prefix;
      let directive = context.directive;
      let component = registry.find(component => component.directive === directive);
      if (component !== undefined) {
        return component.attributes.filter(attribute => matchesPrefix(attribute.name, prefix$1)).map(attribute => {
          let match = attribute.kind;
          let insert;
          insert = match === "Flag" ? attribute.name : attribute.name + "=\"\"";
          let tmp;
          if (attribute.description !== "") {
            tmp = attribute.description;
          } else {
            let match$1 = attribute.kind;
            switch (match$1) {
              case "Flag" :
                tmp = "flag";
                break;
              case "Number" :
                tmp = "number";
                break;
              case "Choice" :
                tmp = attribute.choices.join(" | ");
                break;
              case "Text" :
                tmp = "text";
                break;
            }
          }
          let match$2 = attribute.kind;
          let tmp$1;
          tmp$1 = match$2 === "Flag" ? insert.length : attribute.name.length + 2 | 0;
          return {
            label: attribute.name,
            detail: tmp,
            insert: insert,
            caret: tmp$1,
            back: 0
          };
        });
      } else {
        return [];
      }
    case "Value" :
      let prefix$2 = context.prefix;
      let attribute = context.attribute;
      let directive$1 = context.directive;
      let component$1 = registry.find(component => component.directive === directive$1);
      if (component$1 === undefined) {
        return [];
      }
      let found = component$1.attributes.find(candidate => candidate.name === attribute);
      if (found === undefined) {
        return [];
      }
      let match = found.kind;
      let values;
      values = match === "Flag" ? [
          "true",
          "false"
        ] : found.choices;
      return values.filter(value => matchesPrefix(value, prefix$2)).map(value => ({
        label: value,
        detail: attribute,
        insert: value,
        caret: value.length,
        back: 0
      }));
    case "Prose" :
      return MarkdownSnippets.matching(context._0).map(snippet => ({
        label: snippet.label,
        detail: snippet.detail,
        insert: snippet.insert,
        caret: snippet.caret,
        back: 0
      }));
  }
}

export {
  analyse,
  completions,
}
/* No side effect */
