// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Buntest from "bun:test";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as DirectiveScan from "./DirectiveScan.res.mjs";
import * as DirectiveTemplates from "./DirectiveTemplates.res.mjs";

function formName(form) {
  switch (form) {
    case "Inline" :
      return "inline";
    case "Leaf" :
      return "leaf";
    case "Container" :
      return "container";
  }
}

Buntest.describe("DirectiveTemplates", () => {
  Buntest.test("every template scans back to its own form and name", () => {
    let broken = DirectiveTemplates.all.filter(template => {
      let found = DirectiveScan.scan(template.snippet).at(0);
      if (found !== undefined && found.name === template.name) {
        return found.form !== template.form;
      } else {
        return true;
      }
    }).map(template => template.label).join(",");
    Buntest.expect(broken).toBe("");
  });
  Buntest.test("every template yields exactly one directive", () => {
    let wrong = DirectiveTemplates.all.filter(t => DirectiveScan.scan(t.snippet).length !== 1).length;
    Buntest.expect(wrong).toBe(0);
  });
  Buntest.test("labels are unique", () => {
    let labels = DirectiveTemplates.all.map(t => t.label);
    let unique = Stdlib_Array.reduce(labels, [], (acc, l) => {
      if (acc.includes(l)) {
        return acc;
      } else {
        return acc.concat([l]);
      }
    });
    Buntest.expect(unique.length).toBe(labels.length);
  });
  Buntest.test("covers all three directive forms", () => {
    Buntest.expect(DirectiveTemplates.all.map(t => formName(t.form)).join(",")).toBe("inline,leaf,container");
  });
});

Buntest.describe("DirectiveTemplates.append", () => {
  let slider = DirectiveTemplates.all[1];
  Buntest.test("separates the snippet from existing content", () => {
    Buntest.expect(DirectiveTemplates.append("# Title", slider)).toBe("# Title\n\n" + slider.snippet + "\n");
  });
  Buntest.test("does not open an empty document with blank lines", () => {
    Buntest.expect(DirectiveTemplates.append("", slider)).toBe(slider.snippet + "\n");
  });
  Buntest.test("the appended directive is findable", () => {
    let source = DirectiveTemplates.append("# Title", slider);
    Buntest.expect(DirectiveScan.scan(source).length).toBe(1);
  });
});

export {
  formName,
}
/*  Not a pure module */
