// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

let members = [
  [
    "Structure",
    [
      "page",
      "columns",
      "dashboard",
      "workflow"
    ]
  ],
  [
    "Data",
    [
      "form",
      "input",
      "choose",
      "save",
      "add-form",
      "geo",
      "od-query",
      "od-search",
      "od-datasets",
      "api-query",
      "geocode",
      "file",
      "sql",
      "ml-cluster",
      "ml-anomaly",
      "ml-predict",
      "ml-correlate",
      "ml-forecast"
    ]
  ],
  [
    "Ai",
    [
      "ai-summary",
      "ai-chat",
      "ai-agent",
      "ai-pipeline",
      "ai-query",
      "ai-rule",
      "ai-classify",
      "ai-extract",
      "ai-field",
      "ai-suggest",
      "ai-assist",
      "ai-translate",
      "ai-rewrite",
      "ai-vision",
      "ai-search"
    ]
  ],
  [
    "Views",
    [
      "list",
      "cards",
      "table",
      "column",
      "board",
      "timetable",
      "calendar",
      "if-any",
      "if-empty",
      "chart-bar",
      "chart-line",
      "chart-pie",
      "chart-scatter",
      "chart-area",
      "chart-doughnut",
      "chart-radar",
      "map",
      "explore"
    ]
  ],
  [
    "Values",
    [
      "value",
      "calc",
      "count",
      "sum",
      "avg",
      "min",
      "max",
      "median",
      "stddev",
      "mode",
      "python"
    ]
  ],
  [
    "Status",
    [
      "badge",
      "status-light",
      "progress-bar",
      "progress-circle",
      "meter",
      "toast",
      "alert-banner",
      "help-text",
      "coach-indicator",
      "illustrated-message",
      "asset",
      "divider",
      "truncated"
    ]
  ],
  [
    "Controls",
    [
      "print",
      "button",
      "action-button",
      "clear-button",
      "close-button",
      "infield-button",
      "picker-button",
      "checkbox",
      "radio",
      "radio-group",
      "switch",
      "slider",
      "slider-handle",
      "number-field",
      "textfield",
      "search",
      "combobox",
      "picker",
      "swatch",
      "swatch-group",
      "field-label",
      "field-group",
      "tag",
      "tags",
      "dropzone"
    ]
  ],
  [
    "Navigation",
    [
      "tabs",
      "tab",
      "tab-panel",
      "tabs-overflow",
      "sidenav",
      "sidenav-heading",
      "sidenav-item",
      "breadcrumbs",
      "breadcrumb-item",
      "top-nav",
      "top-nav-item",
      "menu",
      "menu-item",
      "menu-divider",
      "menu-group",
      "action-menu",
      "action-group",
      "action-bar",
      "button-group",
      "link"
    ]
  ],
  [
    "Layout",
    [
      "accordion",
      "accordion-item",
      "card",
      "split-view",
      "grid",
      "theme",
      "thumbnail",
      "avatar",
      "icon"
    ]
  ],
  [
    "Overlays",
    [
      "dialog",
      "dialog-base",
      "dialog-wrapper",
      "alert-dialog",
      "popover",
      "tray",
      "underlay",
      "overlay",
      "overlay-trigger",
      "tooltip",
      "tooltip-openable",
      "contextual-help",
      "coachmark"
    ]
  ],
  [
    "Colour",
    [
      "color-area",
      "color-field",
      "color-handle",
      "color-loupe",
      "color-slider",
      "color-wheel"
    ]
  ],
  [
    "TableParts",
    [
      "table-body",
      "table-head",
      "table-head-cell",
      "table-row",
      "table-cell",
      "table-checkbox-cell"
    ]
  ]
];

let all = members.map(param => param[0]);

function order(directive) {
  return members.findIndex(param => param[1].includes(directive));
}

function of_(directive) {
  return Stdlib_Option.map(members.find(param => param[1].includes(directive)), param => param[0]);
}

function label($$class) {
  switch ($$class) {
    case "Structure" :
      return "ClassStructure";
    case "Data" :
      return "ClassData";
    case "Ai" :
      return "ClassAi";
    case "Views" :
      return "ClassViews";
    case "Values" :
      return "ClassValues";
    case "Status" :
      return "ClassStatus";
    case "Controls" :
      return "ClassControls";
    case "Navigation" :
      return "ClassNavigation";
    case "Layout" :
      return "ClassLayout";
    case "Overlays" :
      return "ClassOverlays";
    case "Colour" :
      return "ClassColour";
    case "TableParts" :
      return "ClassTableParts";
  }
}

let inlineNames = [
  "value",
  "calc",
  "count",
  "sum",
  "avg",
  "min",
  "max",
  "median",
  "stddev",
  "mode"
];

function written(directive) {
  if (inlineNames.includes(directive)) {
    return ":" + directive;
  } else {
    return "::" + directive;
  }
}

function glyph($$class) {
  switch ($$class) {
    case "Structure" :
      return "M6 3h8l4 4v14H6z M14 3v4h4";
    case "Data" :
      return "M4 7c0-1.7 3.6-3 8-3s8 1.3 8 3-3.6 3-8 3-8-1.3-8-3z M4 7v10c0 1.7 3.6 3 8 3s8-1.3 8-3V7";
    case "Ai" :
      return "M12 3l1.9 4.6L18.5 9.5 13.9 11.4 12 16l-1.9-4.6L5.5 9.5l4.6-1.9z M18 15l.9 2.1L21 18l-2.1.9L18 21l-.9-2.1L15 18l2.1-.9z";
    case "Views" :
      return "M3 5h18v14H3z M3 10h18 M9 10v9";
    case "Values" :
      return "M17 5H7l6 7-6 7h10";
    case "Status" :
      return "M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18z M12 8v5 M12 16h.01";
    case "Controls" :
      return "M4 8h16 M4 16h16 M9 5v6 M15 13v6";
    case "Navigation" :
      return "M12 3v18 M5 6h11l3 3-3 3H5z";
    case "Layout" :
      return "M3 5h18v14H3z M10 5v14";
    case "Overlays" :
      return "M8 4h12v12H8z M4 8v12h12";
    case "Colour" :
      return "M12 3s6 6.5 6 10a6 6 0 0 1-12 0c0-3.5 6-10 6-10z";
    case "TableParts" :
      return "M3 5h18v14H3z M3 9h18 M9 9v10 M15 9v10";
  }
}

export {
  members,
  all,
  order,
  of_,
  label,
  written,
  glyph,
}
/* all Not a pure module */
