// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Buntest from "bun:test";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as DirectiveAttributes from "./DirectiveAttributes.res.mjs";

function render(source) {
  return DirectiveAttributes.parse(source).map(a => a.name + "=" + a.value).join(",");
}

Buntest.describe("DirectiveAttributes.parse", () => {
  Buntest.test("reads double-quoted values", () => {
    Buntest.expect(render(`ref="#volume"`)).toBe("ref=#volume");
  });
  Buntest.test("reads several attributes in order", () => {
    Buntest.expect(render(`min="0" max="100" value="50"`)).toBe("min=0,max=100,value=50");
  });
  Buntest.test("reads single-quoted values", () => {
    Buntest.expect(render(`legend='Volume level'`)).toBe("legend=Volume level");
  });
  Buntest.test("reads bare values without whitespace", () => {
    Buntest.expect(render("min=0 max=100")).toBe("min=0,max=100");
  });
  Buntest.test("treats a bare name as a flag", () => {
    Buntest.expect(render("required")).toBe("required=true");
  });
  Buntest.test("keeps spaces inside quoted values", () => {
    Buntest.expect(render(`legend="Volume  level"`)).toBe("legend=Volume  level");
  });
  Buntest.test("keeps an empty quoted value", () => {
    Buntest.expect(render(`legend=""`)).toBe("legend=");
  });
  Buntest.test("tolerates spaces around the equals sign", () => {
    Buntest.expect(render(`ref = "#volume"`)).toBe("ref=#volume");
  });
  Buntest.test("an empty attribute list yields nothing", () => {
    Buntest.expect(render("")).toBe("");
    Buntest.expect(render("   ")).toBe("");
  });
});

Buntest.describe("DirectiveAttributes.attribute", () => {
  Buntest.test("finds by name", () => {
    Buntest.expect(Stdlib_Option.getOr(DirectiveAttributes.attribute(`ref="#volume" min="0"`, "ref"), "none")).toBe("#volume");
  });
  Buntest.test("matches the name case-insensitively", () => {
    Buntest.expect(Stdlib_Option.getOr(DirectiveAttributes.attribute(`Ref="#volume"`, "ref"), "none")).toBe("#volume");
  });
  Buntest.test("answers None for an absent attribute", () => {
    Buntest.expect(Stdlib_Option.getOr(DirectiveAttributes.attribute(`min="0"`, "ref"), "none")).toBe("none");
  });
  Buntest.test("is repeatable", () => {
    let source = `ref="#volume"`;
    Buntest.expect(Stdlib_Option.getOr(DirectiveAttributes.attribute(source, "ref"), "none")).toBe("#volume");
    Buntest.expect(Stdlib_Option.getOr(DirectiveAttributes.attribute(source, "ref"), "none")).toBe("#volume");
    Buntest.expect(Stdlib_Option.getOr(DirectiveAttributes.attribute(source, "ref"), "none")).toBe("#volume");
  });
});

export {
  render,
}
/*  Not a pure module */
