// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";

let attributesPart = "(?:\\{((?:\\\"[^\\\"]*\\\"|'[^']*'|[^}])*)\\})?";

let inlinePattern = "(?<!:):(?!:)([A-Za-z][A-Za-z0-9_-]*)(?:\\[([^\\]]*)\\])?" + attributesPart;

let blockPattern = "^::(?!:)([A-Za-z][A-Za-z0-9_-]*)(?:\\[([^\\]]*)\\])?" + attributesPart + "[ \\t]*$";

function captured(result, index) {
  return Stdlib_Option.getOr(Stdlib_Option.flatMap(result.slice(1).at(index), value => value), "");
}

let fenceOpen = new RegExp("^ {0,3}(`{3,}|~{3,})(.*)$");

let fenceClose = new RegExp("^ {0,3}(`{3,}|~{3,})[ \\t]*$");

function fencedLines(lines) {
  let inside = lines.map(param => false);
  let marker = {
    contents: ""
  };
  lines.forEach((line, index) => {
    if (marker.contents === "") {
      let result = fenceOpen.exec(line);
      if (!(result == null) && (!captured(result, 0).startsWith("`") || !captured(result, 1).includes("`"))) {
        marker.contents = captured(result, 0);
        inside[index] = true;
        return;
      } else {
        return;
      }
    }
    inside[index] = true;
    let result$1 = fenceClose.exec(line);
    if (result$1 == null) {
      return;
    }
    let found = captured(result$1, 0);
    if (Primitive_object.equal(found[0], marker.contents[0]) && found.length >= marker.contents.length) {
      marker.contents = "";
      return;
    }
  });
  return inside;
}

function scanInline(line, offset) {
  let regex = new RegExp(inlinePattern, "g");
  let _accumulated = [];
  while (true) {
    let accumulated = _accumulated;
    let result = regex.exec(line);
    if (result == null) {
      return accumulated;
    }
    let matched = result[0];
    let start = result.index;
    _accumulated = accumulated.concat([{
        form: "Inline",
        name: captured(result, 0),
        label: captured(result, 1),
        attributes: captured(result, 2),
        start: offset + start | 0,
        stop: (offset + start | 0) + matched.length | 0
      }]);
    continue;
  };
}

function scan(source) {
  let lines = source.split("\n");
  let block = new RegExp(blockPattern);
  let blockClose = new RegExp("^::/([A-Za-z][A-Za-z0-9_-]*)[ \\t]*$");
  let fenced = fencedLines(lines);
  let inFence = index => Stdlib_Option.getOr(fenced.at(index), false);
  let findNamedClose = (name, _cursor, _cursorOffset, _depth) => {
    while (true) {
      let depth = _depth;
      let cursorOffset = _cursorOffset;
      let cursor = _cursor;
      let candidate = lines.at(cursor);
      if (candidate === undefined) {
        return;
      }
      let candidateNext = (cursorOffset + candidate.length | 0) + 1 | 0;
      if (inFence(cursor)) {
        _cursorOffset = candidateNext;
        _cursor = cursor + 1 | 0;
        continue;
      }
      let closing = blockClose.exec(candidate);
      let exit = 0;
      if (closing == null) {
        exit = 1;
      } else {
        if (captured(closing, 0) === name) {
          if (depth === 0) {
            return [
              cursor,
              cursorOffset + candidate.length | 0
            ];
          }
          _depth = depth - 1 | 0;
          _cursorOffset = candidateNext;
          _cursor = cursor + 1 | 0;
          continue;
        }
        exit = 1;
      }
      if (exit === 1) {
        let opening = block.exec(candidate);
        let exit$1 = 0;
        if (opening == null) {
          exit$1 = 2;
        } else {
          if (captured(opening, 0) === name) {
            _depth = depth + 1 | 0;
            _cursorOffset = candidateNext;
            _cursor = cursor + 1 | 0;
            continue;
          }
          exit$1 = 2;
        }
        if (exit$1 === 2) {
          _cursorOffset = candidateNext;
          _cursor = cursor + 1 | 0;
          continue;
        }
      }
    };
  };
  let _index = 0;
  let _offset = 0;
  let _skipUntil = 0;
  let _found = [];
  while (true) {
    let found = _found;
    let skipUntil = _skipUntil;
    let offset = _offset;
    let index = _index;
    let line = lines.at(index);
    if (line === undefined) {
      return found;
    }
    let lineLength = line.length;
    let next = (offset + lineLength | 0) + 1 | 0;
    if (index < skipUntil || inFence(index)) {
      _offset = next;
      _index = index + 1 | 0;
      continue;
    }
    let result = block.exec(line);
    if (result == null) {
      _found = found.concat(scanInline(line, offset));
      _offset = next;
      _index = index + 1 | 0;
      continue;
    }
    let name = captured(result, 0);
    let shared_label = captured(result, 1);
    let shared_attributes = captured(result, 2);
    let shared_stop = offset + lineLength | 0;
    let shared = {
      form: "Leaf",
      name: name,
      label: shared_label,
      attributes: shared_attributes,
      start: offset,
      stop: shared_stop
    };
    let match = findNamedClose(name, index + 1 | 0, next, 0);
    if (match !== undefined) {
      _found = found.concat([{
          form: "Container",
          name: name,
          label: shared_label,
          attributes: shared_attributes,
          start: offset,
          stop: match[1]
        }]);
      _skipUntil = match[0] + 1 | 0;
      _offset = next;
      _index = index + 1 | 0;
      continue;
    }
    _found = found.concat([shared]);
    _offset = next;
    _index = index + 1 | 0;
    continue;
  };
}

function render(form, name, label, attributes) {
  let labelPart = label === "" ? "" : "[" + label + "]";
  let attributePart = attributes.trim() === "" ? "" : "{" + attributes.trim() + "}";
  switch (form) {
    case "Inline" :
      return ":" + name + labelPart + attributePart;
    case "Leaf" :
    case "Container" :
      break;
  }
  return "::" + name + labelPart + attributePart;
}

function closing(name) {
  return "::/" + name;
}

function replace(source, occurrence, replacement) {
  return source.slice(0, occurrence.start) + replacement + source.slice(occurrence.stop, source.length);
}

function remove(source, occurrence) {
  let before = source.slice(0, occurrence.start);
  let after = source.slice(occurrence.stop, source.length);
  let match = occurrence.form;
  switch (match) {
    case "Inline" :
      return before + after;
    case "Leaf" :
    case "Container" :
      break;
  }
  return before + after.replace(new RegExp("^\\n"), "");
}

export {
  scan,
  render,
  closing,
  replace,
  remove,
}
/* fenceOpen Not a pure module */
