// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Buntest from "bun:test";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as SpectrumIcons from "../generated/SpectrumIcons.res.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as SpectrumRegistry from "../generated/SpectrumRegistry.res.mjs";
import * as DirectiveRegistry from "./DirectiveRegistry.res.mjs";

Buntest.describe("DirectiveRegistry", () => {
  let ours = DirectiveRegistry.reactive.map(c => c.directive);
  let shadowed = SpectrumRegistry.all.filter(c => ours.includes(c.directive));
  Buntest.test("carries every generated component, plus this app's own", () => {
    Buntest.expect(DirectiveRegistry.all.length).toBe((SpectrumRegistry.all.length + DirectiveRegistry.reactive.length | 0) - shadowed.length | 0);
    let missing = SpectrumRegistry.all.filter(component => Stdlib_Option.isNone(DirectiveRegistry.find(component.directive))).length;
    Buntest.expect(missing).toBe(0);
  });
  Buntest.test("exactly the expected names shadow a Spectrum component", () => {
    Buntest.expect(shadowed.map(c => c.directive).join(",")).toBe("table");
  });
  Buntest.test("the page icon is chosen from Spectrum's own set", () => {
    let page = Stdlib_Option.getOrThrow(DirectiveRegistry.find("page"), undefined);
    let icon = Stdlib_Option.getOrThrow(page.attributes.find(a => a.name === "icon"), undefined);
    Buntest.expect(icon.kind === "Choice").toBe(true);
    Buntest.expect(icon.choices.length).toBe(SpectrumIcons.all.length);
    Buntest.expect(icon.choices.includes("data")).toBe(true);
  });
  Buntest.test("the data directives are described where every consumer reads", () => {
    [
      "form",
      "input",
      "save",
      "list",
      "if-any",
      "if-empty",
      "count",
      "sum",
      "calc"
    ].forEach(name => {
      Buntest.expect(Stdlib_Option.isSome(DirectiveRegistry.find(name))).toBe(true);
    });
  });
  Buntest.test("directive names stay unique", () => {
    let names = DirectiveRegistry.all.map(c => c.directive);
    let unique = Stdlib_Array.reduce(names, [], (acc, n) => {
      if (acc.includes(n)) {
        return acc;
      } else {
        return acc.concat([n]);
      }
    });
    Buntest.expect(unique.length).toBe(names.length);
  });
  Buntest.test("the accordion is Spectrum's, not a hand-rolled details element", () => {
    let accordion = Stdlib_Option.getOrThrow(DirectiveRegistry.find("accordion"), undefined);
    Buntest.expect(accordion.tag).toBe("sp-accordion");
    let item = Stdlib_Option.getOrThrow(DirectiveRegistry.find("accordion-item"), undefined);
    Buntest.expect(item.tag).toBe("sp-accordion-item");
    let names = item.attributes.map(a => a.name);
    Buntest.expect(names.includes("label")).toBe(true);
    Buntest.expect(names.includes("open")).toBe(true);
  });
  Buntest.test("id is available on every component", () => {
    let without = DirectiveRegistry.all.filter(c => !c.attributes.some(a => a.name === "id")).map(c => c.directive).join(",");
    Buntest.expect(without).toBe("");
  });
  Buntest.test("a global attribute never displaces a component's own", () => {
    let slider = Stdlib_Option.getOrThrow(DirectiveRegistry.find("slider"), undefined);
    let ids = slider.attributes.filter(a => a.name === "id");
    Buntest.expect(ids.length).toBe(1);
  });
  Buntest.test("choose reads a collection and stores a field of the chosen row", () => {
    let choose = Stdlib_Option.getOrThrow(DirectiveRegistry.find("choose"), undefined);
    Buntest.expect(choose.tag).toBe("select");
    Buntest.expect(choose.package).toBe("reactivenet");
    let names = choose.attributes.map(a => a.name);
    Buntest.expect([
      "path",
      "field",
      "label"
    ].every(n => names.includes(n))).toBe(true);
  });
  Buntest.test("choose is not a form field: it has no field-of-a-form attributes", () => {
    let choose = Stdlib_Option.getOrThrow(DirectiveRegistry.find("choose"), undefined);
    let names = choose.attributes.map(a => a.name);
    Buntest.expect(names.includes("form")).toBe(false);
    Buntest.expect(names.includes("required")).toBe(false);
  });
  Buntest.test("a component is otherwise passed through unchanged", () => {
    let slider = Stdlib_Option.getOrThrow(DirectiveRegistry.find("slider"), undefined);
    Buntest.expect(slider.tag).toBe("sp-slider");
    Buntest.expect(slider.attributes.length > 15).toBe(true);
  });
});

/*  Not a pure module */
