// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Buntest from "bun:test";
import * as DirectiveScan from "./DirectiveScan.res.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as DirectiveAttributes from "./DirectiveAttributes.res.mjs";

let document = `# Title

::slider[volume]{min="0" max="100" value="50" legend="Volume"}

Current: :value[v]{ref="#volume"} now.

::accordion{id="a1" title="One" name="faq"}
Body of one.
::/accordion

Tail.`;

function summary(source) {
  return DirectiveScan.scan(source).map(o => {
    let match = o.form;
    let form;
    switch (match) {
      case "Inline" :
        form = "inline";
        break;
      case "Leaf" :
        form = "leaf";
        break;
      case "Container" :
        form = "container";
        break;
    }
    return form + ":" + o.name;
  }).join(",");
}

Buntest.describe("DirectiveScan and braces in a value", () => {
  Buntest.test("a quoted value may contain a closing brace", () => {
    let found = DirectiveScan.scan("::input{field=\"cap\" pattern=\"[0-9]{5}\" required}");
    Buntest.expect(found.length).toBe(1);
    let one = found[0];
    Buntest.expect(one.name).toBe("input");
    Buntest.expect(one.attributes).toBe("field=\"cap\" pattern=\"[0-9]{5}\" required");
  });
  Buntest.test("an unquoted brace still ends the list, so a directive stays one line", () => {
    let found = DirectiveScan.scan("::input{field=cap} }");
    Buntest.expect(found.length).toBe(0);
  });
  Buntest.test("the same holds inline", () => {
    let found = DirectiveScan.scan("Total :calc{expr=\"#a\" pattern=\"{2}\"} here");
    Buntest.expect(found.length).toBe(1);
    Buntest.expect(found[0].attributes).toBe("expr=\"#a\" pattern=\"{2}\"");
  });
});

Buntest.describe("DirectiveScan.scan", () => {
  Buntest.test("finds all three forms in document order", () => {
    Buntest.expect(summary(document)).toBe("leaf:slider,inline:value,container:accordion");
  });
  Buntest.test("captures label and attributes", () => {
    let first = DirectiveScan.scan(document)[0];
    Buntest.expect(first.label).toBe("volume");
    Buntest.expect(Stdlib_Option.getOr(DirectiveAttributes.attribute(first.attributes, "max"), "")).toBe("100");
  });
  Buntest.test("offsets delimit exactly the directive text", () => {
    let inline = DirectiveScan.scan(document)[1];
    Buntest.expect(document.slice(inline.start, inline.stop)).toBe(`:value[v]{ref="#volume"}`);
  });
  Buntest.test("a container spans through its close", () => {
    let container = DirectiveScan.scan(document)[2];
    let text = document.slice(container.start, container.stop);
    Buntest.expect(text.startsWith("::accordion")).toBe(true);
    Buntest.expect(text.endsWith("::/accordion")).toBe(true);
    Buntest.expect(text.includes("Body of one.")).toBe(true);
  });
  Buntest.test("does not rescan a container body as top level", () => {
    Buntest.expect(summary("::accordion{id=\"a\"}\n::slider[v]{}\n::/accordion")).toBe("container:accordion");
  });
  Buntest.test("ignores colons that are not directives", () => {
    Buntest.expect(summary("Meeting at 10:30, see https://example.com — ratio 3:4.")).toBe("");
  });
  Buntest.test("finds nothing in a plain document", () => {
    Buntest.expect(summary("# Just a heading\n\nSome text.")).toBe("");
  });
});

Buntest.describe("DirectiveScan blocks", () => {
  Buntest.test("a block nobody closes is a leaf", () => {
    Buntest.expect(summary("::slider[v]{min=\"0\"}")).toBe("leaf:slider");
  });
  Buntest.test("a block its own close ends is a container", () => {
    let source = "::form{path=\"items\"}\n::input{field=\"name\"}\n::/form";
    Buntest.expect(summary(source)).toBe("container:form");
    let form = DirectiveScan.scan(source)[0];
    Buntest.expect(source.slice(form.start, form.stop)).toBe(source);
  });
  Buntest.test("two containers written alike still nest", () => {
    let source = "::if-any{path=\"p\"}\n::list{path=\"p\"}\n{name}\n::/list\n::/if-any";
    Buntest.expect(summary(source)).toBe("container:if-any");
    let outer = DirectiveScan.scan(source)[0];
    Buntest.expect(source.slice(outer.start, outer.stop)).toBe(source);
  });
  Buntest.test("a close of the same name is counted by depth", () => {
    let source = "::form{path=\"a\"}\n::form{path=\"b\"}\nx\n::/form\ninside\n::/form\nafter";
    let outer = DirectiveScan.scan(source)[0];
    let text = source.slice(outer.start, outer.stop);
    Buntest.expect(text.includes("inside")).toBe(true);
    Buntest.expect(text.includes("after")).toBe(false);
  });
  Buntest.test("siblings of the same name each end at their own close", () => {
    Buntest.expect(summary("::page{title=\"A\"}\nOne.\n::/page\n\n::page{title=\"B\"}\nTwo.\n::/page")).toBe("container:page,container:page");
  });
  Buntest.test("a close with nothing open is not a directive", () => {
    Buntest.expect(summary("::/form")).toBe("");
  });
  Buntest.test("a colon fence is not a container", () => {
    Buntest.expect(summary("::::card{id=\"c\"}\nBody.\n::::")).toBe("");
    Buntest.expect(summary(":::accordion{}\nx\n:::")).toBe("");
  });
  Buntest.test("renders open and close as a pair", () => {
    let open_ = DirectiveScan.render("Container", "list", "", `path="items"`);
    Buntest.expect(open_ + "\nrow\n" + DirectiveScan.closing("list")).toBe("::list{path=\"items\"}\nrow\n::/list");
  });
  Buntest.test("a container and a leaf open identically", () => {
    let of_ = form => DirectiveScan.render(form, "card", "", "");
    Buntest.expect(of_("Container")).toBe(of_("Leaf"));
  });
});

Buntest.describe("DirectiveScan.replace and remove", () => {
  Buntest.test("re-rendering an untouched directive leaves the document identical", () => {
    let source = `::slider[volume]{min="0" max="100"}`;
    let found = DirectiveScan.scan(source)[0];
    let rendered = DirectiveScan.render(found.form, found.name, found.label, found.attributes);
    Buntest.expect(DirectiveScan.replace(source, found, rendered)).toBe(source);
  });
  Buntest.test("replaces only the directive, leaving the rest alone", () => {
    let source = "before\n\n::slider[volume]{min=\"0\"}\n\nafter";
    let found = DirectiveScan.scan(source)[0];
    let updated = DirectiveScan.replace(source, found, DirectiveScan.render("Leaf", "slider", "gain", `min="5"`));
    Buntest.expect(updated).toBe("before\n\n::slider[gain]{min=\"5\"}\n\nafter");
  });
  Buntest.test("removing a leaf takes its line with it", () => {
    let source = "before\n::slider[volume]{}\nafter";
    Buntest.expect(DirectiveScan.remove(source, DirectiveScan.scan(source)[0])).toBe("before\nafter");
  });
  Buntest.test("removing an inline directive keeps the surrounding sentence", () => {
    let source = "Volume is :value[v]{ref=\"#volume\"} today.";
    Buntest.expect(DirectiveScan.remove(source, DirectiveScan.scan(source)[0])).toBe("Volume is  today.");
  });
  Buntest.test("removing a container removes the body it wrapped", () => {
    let source = "a\n::accordion{id=\"x\"}\ninside\n::/accordion\nb";
    Buntest.expect(DirectiveScan.remove(source, DirectiveScan.scan(source)[0])).toBe("a\nb");
  });
});

Buntest.describe("DirectiveScan.scan and fenced code", () => {
  Buntest.test("a slice that looks like an inline directive stays code", () => {
    let source = "::python{writes=\"x\"}\n```python\ngiorni = disponibili[:tetto_giorni]\n```\n::/python";
    Buntest.expect(summary(source)).toBe("container:python");
  });
  Buntest.test("a block directive inside a fence is not a directive", () => {
    Buntest.expect(summary("prima\n```\n::slider[volume]{}\n:count{path=\"x\"}\n```\ndopo")).toBe("");
  });
  Buntest.test("a close inside a fence does not end the container", () => {
    Buntest.expect(summary("::form{path=\"p\"}\n```\n::/form\n```\n::input{field=\"a\"}\n::/form\ndopo")).toBe("container:form");
    Buntest.expect(summary("```\n::/form\n```\n::input{field=\"a\"}")).toBe("leaf:input");
  });
  Buntest.test("the fence has to be closed by the same character, at least as long", () => {
    Buntest.expect(summary("````\n```\n::slider[v]{}\n````\n::switch{}")).toBe("leaf:switch");
  });
  Buntest.test("backticks in running text do not open a fence", () => {
    Buntest.expect(summary("Scrivi `a` e `b`.\n\n::slider[volume]{}")).toBe("leaf:slider");
  });
  Buntest.test("a fence nobody closes swallows the rest, exactly as marked does", () => {
    Buntest.expect(summary("::switch{}\n```\n::slider[v]{}\ntesto\n:count{path=\"x\"}")).toBe("leaf:switch");
  });
  Buntest.test("a tilde fence works like a backtick one", () => {
    Buntest.expect(summary("~~~\n::slider[v]{}\n~~~\n::switch{}")).toBe("leaf:switch");
  });
  Buntest.test("what comes after a closed fence is scanned again", () => {
    Buntest.expect(summary("```\n::slider[v]{}\n```\n\nTesto :count{path=\"c\"} qui.\n\n::switch{}")).toBe("inline:count,leaf:switch");
  });
});

export {
  document,
  summary,
}
/*  Not a pure module */
