// Generated by ReScript, PLEASE EDIT WITH CARE


let all = [
  {
    label: "Reactive value",
    form: "Inline",
    name: "value",
    snippet: `:value[v]{ref="#key"}`
  },
  {
    label: "Slider",
    form: "Leaf",
    name: "slider",
    snippet: `::slider[key]{min="0" max="100" value="50" legend="Label"}`
  },
  {
    label: "Accordion",
    form: "Container",
    name: "accordion",
    snippet: `::accordion{density="compact"}
::accordion-item{label="First" open}
Content.
::/accordion-item
::accordion-item{label="Second"}
More content.
::/accordion-item
::/accordion`
  }
];

function append(source, template) {
  let trimmed = source.trimEnd();
  if (trimmed === "") {
    return template.snippet + "\n";
  } else {
    return trimmed + "\n\n" + template.snippet + "\n";
  }
}

export {
  all,
  append,
}
/* No side effect */
