// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

function parse(source) {
  let regex = new RegExp("([A-Za-z_][A-Za-z0-9_-]*)(?:\\s*=\\s*(?:\"([^\"]*)\"|'([^']*)'|([^\\s}]+)))?", "g");
  let _accumulated = [];
  while (true) {
    let accumulated = _accumulated;
    let result = regex.exec(source);
    if (result == null) {
      return accumulated;
    }
    let captured = index => Stdlib_Option.flatMap(result.slice(1).at(index), value => value);
    let name = captured(0);
    if (name === undefined) {
      return accumulated;
    }
    let value = Stdlib_Option.getOr(Stdlib_Option.orElse(Stdlib_Option.orElse(captured(1), captured(2)), captured(3)), "true");
    _accumulated = accumulated.concat([{
        name: name,
        value: value
      }]);
    continue;
  };
}

function find(attributes, name) {
  let needle = name.toLowerCase();
  return Stdlib_Option.map(attributes.find(attribute => attribute.name.toLowerCase() === needle), attribute => attribute.value);
}

function attribute(source, name) {
  return find(parse(source), name);
}

function serialize(attributes) {
  return attributes.map(attribute => attribute.name + "=\"" + attribute.value.replaceAll("\"", "'") + "\"").join(" ");
}

function set(attributes, name, value) {
  if (attributes.some(a => a.name.toLowerCase() === name.toLowerCase())) {
    return attributes.map(a => {
      if (a.name.toLowerCase() === name.toLowerCase()) {
        return {
          name: a.name,
          value: value
        };
      } else {
        return a;
      }
    });
  } else {
    return attributes.concat([{
        name: name,
        value: value
      }]);
  }
}

export {
  parse,
  find,
  attribute,
  serialize,
  set,
}
/* No side effect */
