// Generated by ReScript, PLEASE EDIT WITH CARE

import * as AppId from "./AppId.res.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

let prefix = "doc/";

function of_(id) {
  return prefix + id;
}

function idOf(key) {
  if (!key.startsWith(prefix)) {
    return;
  }
  let id = key.slice(prefix.length, key.length);
  if (AppId.isValid(id)) {
    return id;
  }
}

function isDocument(key) {
  return Stdlib_Option.isSome(idOf(key));
}

export {
  prefix,
  of_,
  idOf,
  isDocument,
}
/* No side effect */
