// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Draft from "./Draft.res.mjs";
import * as Buntest from "bun:test";

function field(fieldOpt, labelOpt, valueOpt, kindOpt, tickedOpt, requiredOpt, minOpt, maxOpt, patternOpt, patternMessageOpt, param) {
  let field$1 = fieldOpt !== undefined ? fieldOpt : "what";
  let label = labelOpt !== undefined ? labelOpt : "What";
  let value = valueOpt !== undefined ? valueOpt : "";
  let kind = kindOpt !== undefined ? kindOpt : "text";
  let ticked = tickedOpt !== undefined ? tickedOpt : false;
  let required = requiredOpt !== undefined ? requiredOpt : false;
  let min = minOpt !== undefined ? minOpt : "";
  let max = maxOpt !== undefined ? maxOpt : "";
  let pattern = patternOpt !== undefined ? patternOpt : "";
  let patternMessage = patternMessageOpt !== undefined ? patternMessageOpt : "";
  return {
    field: field$1,
    label: label,
    value: value,
    kind: kind,
    ticked: ticked,
    required: required,
    min: min,
    max: max,
    pattern: pattern,
    patternMessage: patternMessage
  };
}

function problems(controls) {
  return Draft.check(controls).map(c => c.problem);
}

Buntest.describe("Draft.blank", () => {
  Buntest.test("a draft with nothing in it is blank", () => {
    Buntest.expect(Draft.blank([
      field(undefined, undefined, "  ", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined),
      field("who", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)
    ])).toBe(true);
  });
  Buntest.test("an unticked box does not make a draft worth saving", () => {
    Buntest.expect(Draft.blank([
      field(undefined, undefined, undefined, "checkbox", undefined, undefined, undefined, undefined, undefined, undefined, undefined),
      field("who", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)
    ])).toBe(true);
    Buntest.expect(Draft.blank([field(undefined, undefined, undefined, "checkbox", true, undefined, undefined, undefined, undefined, undefined, undefined)])).toBe(false);
  });
  Buntest.test("anything typed makes it worth saving", () => {
    Buntest.expect(Draft.blank([field(undefined, undefined, "Bread", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)])).toBe(false);
  });
});

Buntest.describe("Draft.reading", () => {
  Buntest.test("a tick stores true or false, like everywhere else", () => {
    Buntest.expect(Draft.reading(field(undefined, undefined, undefined, "checkbox", true, undefined, undefined, undefined, undefined, undefined, undefined))).toBe("true");
    Buntest.expect(Draft.reading(field(undefined, undefined, undefined, "checkbox", undefined, undefined, undefined, undefined, undefined, undefined, undefined))).toBe("false");
  });
  Buntest.test("anything else stores what was typed", () => {
    Buntest.expect(Draft.reading(field(undefined, undefined, " Bread ", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined))).toBe(" Bread ");
  });
});

Buntest.describe("Draft.check", () => {
  Buntest.test("an empty optional field is not a mistake", () => {
    Buntest.expect(problems([field(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)])).toEqual([]);
  });
  Buntest.test("required means required, ticks included", () => {
    Buntest.expect(problems([field(undefined, undefined, undefined, undefined, undefined, true, undefined, undefined, undefined, undefined, undefined)])).toEqual(["Missing"]);
    Buntest.expect(problems([field(undefined, undefined, undefined, "checkbox", undefined, true, undefined, undefined, undefined, undefined, undefined)])).toEqual(["Missing"]);
    Buntest.expect(problems([field(undefined, undefined, undefined, "checkbox", true, true, undefined, undefined, undefined, undefined, undefined)])).toEqual([]);
  });
  Buntest.test("a number is a number all the way through", () => {
    Buntest.expect(problems([field(undefined, undefined, "12.5", "number", undefined, undefined, undefined, undefined, undefined, undefined, undefined)])).toEqual([]);
    Buntest.expect(problems([field(undefined, undefined, "12 euro", "number", undefined, undefined, undefined, undefined, undefined, undefined, undefined)])).toEqual(["NotANumber"]);
  });
  Buntest.test("min and max compare as numbers", () => {
    let bounded = value => problems([field(undefined, undefined, value, "number", undefined, undefined, "1", "10", undefined, undefined, undefined)]);
    Buntest.expect(bounded("0.5")).toEqual([{
        TAG: "Below",
        _0: "1"
      }]);
    Buntest.expect(bounded("11")).toEqual([{
        TAG: "Above",
        _0: "10"
      }]);
    Buntest.expect(bounded("1")).toEqual([]);
  });
  Buntest.test("a date is what a date input writes, and its bounds sort as text", () => {
    Buntest.expect(problems([field(undefined, undefined, "2026-08-12", "date", undefined, undefined, undefined, undefined, undefined, undefined, undefined)])).toEqual([]);
    Buntest.expect(problems([field(undefined, undefined, "12/08/2026", "date", undefined, undefined, undefined, undefined, undefined, undefined, undefined)])).toEqual(["NotADate"]);
    Buntest.expect(problems([field(undefined, undefined, "2026-08-12", "date", undefined, undefined, "2026-09-01", undefined, undefined, undefined, undefined)])).toEqual([{
        TAG: "Below",
        _0: "2026-09-01"
      }]);
  });
  Buntest.test("a time is HH:MM, with or without seconds", () => {
    Buntest.expect(problems([field(undefined, undefined, "09:30", "time", undefined, undefined, undefined, undefined, undefined, undefined, undefined)])).toEqual([]);
    Buntest.expect(problems([field(undefined, undefined, "09:30:15", "time", undefined, undefined, undefined, undefined, undefined, undefined, undefined)])).toEqual([]);
    Buntest.expect(problems([field(undefined, undefined, "25:00", "time", undefined, undefined, undefined, undefined, undefined, undefined, undefined)])).toEqual(["NotATime"]);
  });
  Buntest.test("an address needs an @ and a domain", () => {
    Buntest.expect(problems([field(undefined, undefined, "ada@example.org", "email", undefined, undefined, undefined, undefined, undefined, undefined, undefined)])).toEqual([]);
    Buntest.expect(problems([field(undefined, undefined, "ada@example", "email", undefined, undefined, undefined, undefined, undefined, undefined, undefined)])).toEqual(["NotAnEmail"]);
    Buntest.expect(problems([field(undefined, undefined, "ada example.org", "email", undefined, undefined, undefined, undefined, undefined, undefined, undefined)])).toEqual(["NotAnEmail"]);
  });
  Buntest.test("a url is one SafeUrl would accept", () => {
    Buntest.expect(problems([field(undefined, undefined, "https://example.org", "url", undefined, undefined, undefined, undefined, undefined, undefined, undefined)])).toEqual([]);
    Buntest.expect(problems([field(undefined, undefined, "javascript:alert(1)", "url", undefined, undefined, undefined, undefined, undefined, undefined, undefined)])).toEqual(["NotAUrl"]);
  });
  Buntest.test("the author's pattern must match the whole value", () => {
    let postcode = value => problems([field(undefined, undefined, value, undefined, undefined, undefined, undefined, undefined, "[0-9]{5}", "Five digits", undefined)]);
    Buntest.expect(postcode("20121")).toEqual([]);
    Buntest.expect(postcode("2012")).toEqual([{
        TAG: "NotMatching",
        _0: "Five digits"
      }]);
    Buntest.expect(postcode("20121 Milano")).toEqual([{
        TAG: "NotMatching",
        _0: "Five digits"
      }]);
  });
  Buntest.test("a pattern nobody can compile refuses nothing", () => {
    Buntest.expect(problems([field(undefined, undefined, "anything", undefined, undefined, undefined, undefined, undefined, "[unclosed", undefined, undefined)])).toEqual([]);
  });
  Buntest.test("the type is complained about before the author's rule", () => {
    Buntest.expect(problems([field(undefined, undefined, "twelve", "number", undefined, undefined, undefined, undefined, "[0-9]+", undefined, undefined)])).toEqual(["NotANumber"]);
  });
  Buntest.test("an empty field is never matched against a pattern", () => {
    Buntest.expect(problems([field(undefined, undefined, "", undefined, undefined, undefined, undefined, undefined, "[0-9]{5}", undefined, undefined)])).toEqual([]);
  });
  Buntest.test("a complaint names the field the way the reader sees it", () => {
    let complaints = Draft.check([field("cap", "Postcode", undefined, undefined, undefined, true, undefined, undefined, undefined, undefined, undefined)]);
    Buntest.expect(complaints.map(c => c.label).join(",")).toBe("Postcode");
    let unlabelled = Draft.check([field("cap", "", undefined, undefined, undefined, true, undefined, undefined, undefined, undefined, undefined)]);
    Buntest.expect(unlabelled.map(c => c.label).join(",")).toBe("cap");
  });
});

export {
  field,
  problems,
}
/*  Not a pure module */
