// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

let delimiter = "---";

function stripCarriageReturn(line) {
  if (line.endsWith("\r")) {
    return line.slice(0, line.length - 1 | 0);
  } else {
    return line;
  }
}

function unquote(value) {
  let length = value.length;
  if (length < 2) {
    return value;
  }
  let first = value.charAt(0);
  let last = value.charAt(length - 1 | 0);
  if (first === "\"" && first === last) {
    let value$1 = value.slice(1, length - 1 | 0);
    let out = {
      contents: ""
    };
    let walk = _index => {
      while (true) {
        let index = _index;
        let character = value$1.charAt(index);
        switch (character) {
          case "" :
            return;
          case "\\" :
            let match = value$1.charAt(index + 1 | 0);
            switch (match) {
              case "\"" :
                out.contents = out.contents + "\"";
                _index = index + 2 | 0;
                continue;
              case "\\" :
                out.contents = out.contents + "\\";
                _index = index + 2 | 0;
                continue;
              case "n" :
                out.contents = out.contents + "\n";
                _index = index + 2 | 0;
                continue;
              case "r" :
                out.contents = out.contents + "\r";
                _index = index + 2 | 0;
                continue;
              default:
                out.contents = out.contents + "\\";
                _index = index + 1 | 0;
                continue;
            }
          default:
            out.contents = out.contents + character;
            _index = index + 1 | 0;
            continue;
        }
      };
    };
    walk(0);
    return out.contents;
  } else if (first === "'" && first === last) {
    return value.slice(1, length - 1 | 0);
  } else {
    return value;
  }
}

function findClosing(lines, _index) {
  while (true) {
    let index = _index;
    let line = lines.at(index);
    if (line === undefined) {
      return;
    }
    if (stripCarriageReturn(line).trim() === delimiter) {
      return index;
    }
    _index = index + 1 | 0;
    continue;
  };
}

function parse(source) {
  let lines = source.split("\n");
  let first = lines.at(0);
  if (first === undefined) {
    return {
      meta: undefined,
      body: source
    };
  }
  if (stripCarriageReturn(first).trim() !== delimiter) {
    return {
      meta: undefined,
      body: source
    };
  }
  let closing = findClosing(lines, 1);
  if (closing === undefined) {
    return {
      meta: undefined,
      body: source
    };
  }
  let fields = Stdlib_Array.filterMap(lines.slice(1, closing).map(stripCarriageReturn), line => {
    let trimmed = line.trim();
    if (trimmed === "" || trimmed.startsWith("#")) {
      return;
    } else {
      let index = line.indexOf(":");
      if (index === -1 || index === 0) {
        return;
      }
      let key = line.slice(0, index).trim();
      let value = unquote(line.slice(index + 1 | 0, line.length).trim());
      if (key === "") {
        return;
      } else {
        return {
          key: key,
          value: value
        };
      }
    }
  });
  let body = lines.slice(closing + 1 | 0, lines.length).join("\n").replace(new RegExp("^\\s*\\n"), "");
  return {
    meta: {
      fields: fields
    },
    body: body
  };
}

function get(meta, name) {
  let needle = name.toLowerCase();
  return Stdlib_Option.map(meta.fields.find(field => field.key.toLowerCase() === needle), field => field.value);
}

let empty = {
  fields: []
};

function needsQuoting(value) {
  if (value === "" || value !== value.trim() || value.startsWith("#") || value.startsWith("\"") || value.startsWith("'") || value.includes("\n") || value.includes("\r") || value.includes(": ") || new RegExp("^-?[0-9]+(\\.[0-9]+)?$").test(value) || new RegExp("^[0-9]{4}-[0-9]{2}-[0-9]{2}").test(value)) {
    return true;
  } else {
    return new RegExp("^(true|false|null|yes|no|on|off)$", "i").test(value);
  }
}

function renderValue(value) {
  if (needsQuoting(value)) {
    return "\"" + value.replaceAll("\\", "\\\\").replaceAll("\"", "\\\"").replaceAll("\n", "\\n").replaceAll("\r", "\\r") + "\"";
  } else {
    return value;
  }
}

function setField(meta, key, value) {
  if (meta.fields.some(field => field.key.toLowerCase() === key.toLowerCase())) {
    return {
      fields: meta.fields.map(field => {
        if (field.key.toLowerCase() === key.toLowerCase()) {
          return {
            key: field.key,
            value: value
          };
        } else {
          return field;
        }
      })
    };
  } else {
    return {
      fields: meta.fields.concat([{
          key: key,
          value: value
        }])
    };
  }
}

function removeField(meta, key) {
  return {
    fields: meta.fields.filter(field => field.key.toLowerCase() !== key.toLowerCase())
  };
}

function serialize(meta, body) {
  if (meta.fields.length === 0) {
    return body;
  } else {
    return delimiter + "\n" + meta.fields.map(field => field.key + ": " + renderValue(field.value)).join("\n") + "\n" + delimiter + "\n\n" + body;
  }
}

export {
  parse,
  get,
  empty,
  setField,
  removeField,
  serialize,
}
/* No side effect */
