// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Buntest from "bun:test";
import * as Frontmatter from "./Frontmatter.res.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

let sample = `---
appId: grade-book
title: Grade Book
description: Class grades, with per-student and per-subject averages.
lang: en
version: "1.0"
author: Ada
date: "2026-06-27"
---

# Grades

Body text.`;

function field(source, name) {
  let meta = Frontmatter.parse(source).meta;
  if (meta !== undefined) {
    return Stdlib_Option.getOr(Frontmatter.get(meta, name), "(absent)");
  } else {
    return "(no frontmatter)";
  }
}

function keys(source) {
  let meta = Frontmatter.parse(source).meta;
  if (meta !== undefined) {
    return meta.fields.map(f => f.key).join(",");
  } else {
    return "(no frontmatter)";
  }
}

Buntest.describe("Frontmatter.parse", () => {
  Buntest.test("reads every field of the documented block", () => {
    Buntest.expect(keys(sample)).toBe("appId,title,description,lang,version,author,date");
  });
  Buntest.test("keeps values as written", () => {
    Buntest.expect(field(sample, "appId")).toBe("grade-book");
    Buntest.expect(field(sample, "title")).toBe("Grade Book");
    Buntest.expect(field(sample, "author")).toBe("Ada");
  });
  Buntest.test("removes matched surrounding quotes", () => {
    Buntest.expect(field(sample, "version")).toBe("1.0");
    Buntest.expect(field(sample, "date")).toBe("2026-06-27");
  });
  Buntest.test("looks up fields case-insensitively", () => {
    Buntest.expect(field(sample, "APPID")).toBe("grade-book");
  });
  Buntest.test("strips the block from the body", () => {
    Buntest.expect(Frontmatter.parse(sample).body).toBe("# Grades\n\nBody text.");
  });
  Buntest.test("keeps colons inside values", () => {
    Buntest.expect(field("---\nhome: https://example.com/a:b\n---\n", "home")).toBe("https://example.com/a:b");
  });
  Buntest.test("keeps an unmatched quote", () => {
    Buntest.expect(field("---\nauthor: it's Ada\n---\n", "author")).toBe("it's Ada");
  });
  Buntest.test("ignores blank lines and comments", () => {
    Buntest.expect(keys("---\n\n# a comment\ntitle: T\n\n---\n")).toBe("title");
  });
  Buntest.test("handles CRLF documents", () => {
    Buntest.expect(field("---\r\ntitle: T\r\n---\r\nbody", "title")).toBe("T");
  });
});

Buntest.describe("Frontmatter.parse — documents without usable frontmatter", () => {
  Buntest.test("a plain document is left alone", () => {
    let source = "# Title\n\nNo frontmatter here.";
    Buntest.expect(Frontmatter.parse(source).body).toBe(source);
    Buntest.expect(keys(source)).toBe("(no frontmatter)");
  });
  Buntest.test("an unterminated block is treated as body", () => {
    let source = "---\ntitle: T\n\n# Heading";
    Buntest.expect(Frontmatter.parse(source).body).toBe(source);
    Buntest.expect(keys(source)).toBe("(no frontmatter)");
  });
  Buntest.test("a --- that is not on the first line is not frontmatter", () => {
    let source = "# Title\n\n---\ntitle: T\n---\n";
    Buntest.expect(Frontmatter.parse(source).body).toBe(source);
  });
  Buntest.test("an empty block yields no fields but still strips", () => {
    Buntest.expect(keys("---\n---\nbody")).toBe("");
    Buntest.expect(Frontmatter.parse("---\n---\nbody").body).toBe("body");
  });
  Buntest.test("an empty document is left alone", () => {
    Buntest.expect(Frontmatter.parse("").body).toBe("");
  });
});

Buntest.describe("Frontmatter.serialize", () => {
  let roundTrip = source => {
    let parsed = Frontmatter.parse(source);
    let meta = parsed.meta;
    if (meta !== undefined) {
      return Frontmatter.serialize(meta, parsed.body);
    } else {
      return parsed.body;
    }
  };
  Buntest.test("round-trips the documented block unchanged", () => {
    Buntest.expect(roundTrip(sample)).toBe(sample);
  });
  Buntest.test("re-quotes values YAML would read as a number or date", () => {
    let meta = Frontmatter.setField(Frontmatter.empty, "version", "1.0");
    Buntest.expect(Frontmatter.serialize(meta, "body")).toBe("---\nversion: \"1.0\"\n---\n\nbody");
  });
  Buntest.test("leaves ordinary strings unquoted", () => {
    let meta = Frontmatter.setField(Frontmatter.empty, "title", "Grade Book");
    Buntest.expect(Frontmatter.serialize(meta, "body")).toBe("---\ntitle: Grade Book\n---\n\nbody");
  });
  Buntest.test("quotes booleans and empty values so they stay strings", () => {
    let meta = Frontmatter.setField(Frontmatter.setField(Frontmatter.empty, "draft", "true"), "note", " padded ");
    Buntest.expect(Frontmatter.serialize(meta, "b")).toBe("---\ndraft: \"true\"\nnote: \" padded \"\n---\n\nb");
  });
  Buntest.test("omits an empty block entirely", () => {
    Buntest.expect(Frontmatter.serialize(Frontmatter.empty, "# Just body")).toBe("# Just body");
  });
});

Buntest.describe("Frontmatter round trips its own escaping", () => {
  let cycle = value => {
    let written = Frontmatter.serialize(Frontmatter.setField(Frontmatter.empty, "description", value), "Body");
    return Stdlib_Option.flatMap(Frontmatter.parse(written).meta, meta => Frontmatter.get(meta, "description"));
  };
  Buntest.test("a value with quotes in it comes back unchanged", () => {
    Buntest.expect(cycle("a \"big\" release")).toEqual("a \"big\" release");
    let once = Stdlib_Option.getOr(cycle("a \"big\" release"), "");
    Buntest.expect(cycle(once)).toEqual(once);
  });
  Buntest.test("backslashes survive too", () => {
    Buntest.expect(cycle("C:\\Users\\ada")).toEqual("C:\\Users\\ada");
  });
  Buntest.test("a value with a newline neither truncates nor eats the body", () => {
    Buntest.expect(cycle("two\nlines")).toEqual("two\nlines");
    Buntest.expect(cycle("sneaky\n---\nnot a delimiter")).toEqual("sneaky\n---\nnot a delimiter");
  });
  Buntest.test("a value that merely looks quoted is not stripped", () => {
    Buntest.expect(cycle("\"already quoted\"")).toEqual("\"already quoted\"");
  });
});

Buntest.describe("Frontmatter.setField", () => {
  let meta = Stdlib_Option.getOr(Frontmatter.parse(sample).meta, Frontmatter.empty);
  Buntest.test("updates in place without reordering", () => {
    let updated = Frontmatter.setField(meta, "title", "Register");
    Buntest.expect(updated.fields.map(f => f.key).join(",")).toBe("appId,title,description,lang,version,author,date");
    Buntest.expect(Stdlib_Option.getOr(Frontmatter.get(updated, "title"), "")).toBe("Register");
  });
  Buntest.test("appends an unknown key", () => {
    let updated = Frontmatter.setField(meta, "reviewer", "Grace");
    Buntest.expect(updated.fields.length).toBe(meta.fields.length + 1 | 0);
    Buntest.expect(Stdlib_Option.getOr(Frontmatter.get(updated, "reviewer"), "")).toBe("Grace");
  });
  Buntest.test("matches existing keys case-insensitively rather than duplicating", () => {
    let updated = Frontmatter.setField(meta, "TITLE", "Register");
    Buntest.expect(updated.fields.length).toBe(meta.fields.length);
  });
  Buntest.test("removes a field", () => {
    let updated = Frontmatter.removeField(meta, "author");
    Buntest.expect(Stdlib_Option.isNone(Frontmatter.get(updated, "author"))).toBe(true);
    Buntest.expect(updated.fields.length).toBe(meta.fields.length - 1 | 0);
  });
});

export {
  sample,
  field,
  keys,
}
/*  Not a pure module */
