// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";

let diff = (function (before, after) {
  const a = before.split("\n");
  const b = after.split("\n");
  const n = a.length, m = b.length;
  // lcs[i][j] = length of the longest common subsequence of a[i..] and b[j..]
  const lcs = Array.from({ length: n + 1 }, () => new Int32Array(m + 1));
  for (let i = n - 1; i >= 0; i--) {
    for (let j = m - 1; j >= 0; j--) {
      lcs[i][j] = a[i] === b[j] ? lcs[i + 1][j + 1] + 1 : Math.max(lcs[i + 1][j], lcs[i][j + 1]);
    }
  }
  const out = [];
  let i = 0, j = 0;
  while (i < n && j < m) {
    if (a[i] === b[j]) {
      out.push({ sign: " ", text: a[i] });
      i++; j++;
    } else if (lcs[i + 1][j] >= lcs[i][j + 1]) {
      out.push({ sign: "-", text: a[i] });
      i++;
    } else {
      out.push({ sign: "+", text: b[j] });
      j++;
    }
  }
  while (i < n) out.push({ sign: "-", text: a[i++] });
  while (j < m) out.push({ sign: "+", text: b[j++] });
  return out;
});

function changesOnly(before, after) {
  return diff(before, after).filter(line => line.sign !== " ");
}

function count(changes) {
  return Stdlib_Array.reduce(changes, {
    added: 0,
    removed: 0
  }, (tally, line) => {
    let match = line.sign;
    switch (match) {
      case "+" :
        return {
          added: tally.added + 1 | 0,
          removed: tally.removed
        };
      case "-" :
        return {
          added: tally.added,
          removed: tally.removed + 1 | 0
        };
      default:
        return tally;
    }
  });
}

export {
  diff,
  changesOnly,
  count,
}
/* No side effect */
