// Generated by ReScript, PLEASE EDIT WITH CARE

import * as LineDiff from "./LineDiff.res.mjs";
import * as Buntest from "bun:test";

Buntest.describe("LineDiff", () => {
  Buntest.test("identical documents have no changes", () => {
    Buntest.expect(LineDiff.changesOnly("a\nb\nc", "a\nb\nc")).toEqual([]);
  });
  Buntest.test("an added line is a plus where it was added", () => {
    Buntest.expect(LineDiff.changesOnly("a\nc", "a\nb\nc")).toEqual([{
        sign: "+",
        text: "b"
      }]);
  });
  Buntest.test("a removed line is a minus", () => {
    Buntest.expect(LineDiff.changesOnly("a\nb\nc", "a\nc")).toEqual([{
        sign: "-",
        text: "b"
      }]);
  });
  Buntest.test("a changed line is a minus then a plus", () => {
    Buntest.expect(LineDiff.changesOnly("title: Vecchio\nbody", "title: Nuovo\nbody")).toEqual([
      {
        sign: "-",
        text: "title: Vecchio"
      },
      {
        sign: "+",
        text: "title: Nuovo"
      }
    ]);
  });
  Buntest.test("counts tally the two signs", () => {
    let counts = LineDiff.count(LineDiff.changesOnly("a\nb\nc", "a\nx\ny\nc"));
    Buntest.expect(counts.added).toBe(2);
    Buntest.expect(counts.removed).toBe(1);
  });
  Buntest.test("repeated lines stay aligned", () => {
    Buntest.expect(LineDiff.changesOnly("x\na\nx", "x\nb\nx")).toEqual([
      {
        sign: "-",
        text: "a"
      },
      {
        sign: "+",
        text: "b"
      }
    ]);
  });
  Buntest.test("an empty old document is all pluses", () => {
    Buntest.expect(LineDiff.count(LineDiff.changesOnly("", "a\nb")).added > 0).toBe(true);
  });
});

/*  Not a pure module */
