// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Locale from "./Locale.res.mjs";
import * as Buntest from "bun:test";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";

let name = Locale.toTag;

function parsed(tag) {
  return Stdlib_Option.getOr(Stdlib_Option.map(Locale.parse(tag), name), "none");
}

Buntest.describe("Locale.parse", () => {
  Buntest.test("accepts bare language tags", () => {
    Buntest.expect(parsed("fr")).toBe("fr");
    Buntest.expect(parsed("zh")).toBe("zh");
  });
  Buntest.test("ignores the region subtag", () => {
    Buntest.expect(parsed("en-GB")).toBe("en");
    Buntest.expect(parsed("pt-BR")).toBe("pt");
    Buntest.expect(parsed("de-AT")).toBe("de");
  });
  Buntest.test("ignores script and region together", () => {
    Buntest.expect(parsed("zh-Hans-CN")).toBe("zh");
  });
  Buntest.test("ignores case and surrounding whitespace", () => {
    Buntest.expect(parsed("  IT-it  ")).toBe("it");
  });
  Buntest.test("rejects unsupported languages", () => {
    Buntest.expect(parsed("ja")).toBe("none");
    Buntest.expect(parsed("")).toBe("none");
  });
});

Buntest.describe("Locale.fromPreferred", () => {
  Buntest.test("takes the first supported entry, not the first entry", () => {
    Buntest.expect(Locale.toTag(Locale.fromPreferred([
      "ja",
      "ko",
      "de-AT",
      "fr"
    ]))).toBe("de");
  });
  Buntest.test("falls back when nothing matches", () => {
    Buntest.expect(Locale.toTag(Locale.fromPreferred([
      "ja",
      "ko"
    ]))).toBe(Locale.toTag(Locale.fallback));
  });
  Buntest.test("falls back on an empty list", () => {
    Buntest.expect(Locale.toTag(Locale.fromPreferred([]))).toBe(Locale.toTag(Locale.fallback));
  });
});

Buntest.describe("Locale.all", () => {
  Buntest.test("every locale round-trips through its tag", () => {
    let broken = Locale.all.filter(locale => Primitive_object.notequal(Locale.parse(Locale.toTag(locale)), locale)).map(Locale.toTag).join(",");
    Buntest.expect(broken).toBe("");
  });
  Buntest.test("lists all seven supported languages", () => {
    Buntest.expect(Locale.all.length).toBe(7);
  });
  Buntest.test("has a native name for each", () => {
    let missing = Locale.all.filter(l => Locale.nativeName(l) === "").length;
    Buntest.expect(missing).toBe(0);
  });
});

export {
  name,
  parsed,
}
/*  Not a pure module */
