// Generated by ReScript, PLEASE EDIT WITH CARE


let all = [
  {
    label: "h1",
    detail: "Heading 1",
    insert: "# ",
    caret: 2
  },
  {
    label: "h2",
    detail: "Heading 2",
    insert: "## ",
    caret: 3
  },
  {
    label: "h3",
    detail: "Heading 3",
    insert: "### ",
    caret: 4
  },
  {
    label: "bold",
    detail: "Bold text",
    insert: "****",
    caret: 2
  },
  {
    label: "italic",
    detail: "Italic text",
    insert: "**",
    caret: 1
  },
  {
    label: "strike",
    detail: "Strikethrough (GFM)",
    insert: "~~~~",
    caret: 2
  },
  {
    label: "link",
    detail: "Link",
    insert: "[](https://)",
    caret: 1
  },
  {
    label: "image",
    detail: "Image",
    insert: "![](https://)",
    caret: 2
  },
  {
    label: "code",
    detail: "Fenced code block",
    insert: "```\n\n```",
    caret: 3
  },
  {
    label: "mermaid",
    detail: "Mermaid diagram",
    insert: "```mermaid\nflowchart LR\n  A --> B\n```",
    caret: 11
  },
  {
    label: "math",
    detail: "Inline math (KaTeX)",
    insert: "$$",
    caret: 1
  },
  {
    label: "mathblock",
    detail: "Display math (KaTeX)",
    insert: "$$\n\n$$",
    caret: 3
  },
  {
    label: "table",
    detail: "Table (GFM)",
    insert: "| A | B |\n| --- | --- |\n|  |  |",
    caret: 0
  },
  {
    label: "todo",
    detail: "Task list (GFM)",
    insert: "- [ ] ",
    caret: 6
  },
  {
    label: "quote",
    detail: "Blockquote",
    insert: "> ",
    caret: 2
  },
  {
    label: "hr",
    detail: "Horizontal rule",
    insert: "---\n",
    caret: 4
  }
];

function matching(prefix) {
  let needle = prefix.trim().toLowerCase();
  if (needle === "") {
    return all;
  } else {
    return all.filter(snippet => snippet.label.toLowerCase().startsWith(needle));
  }
}

export {
  all,
  matching,
}
/* No side effect */
