// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Buntest from "bun:test";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as MarkdownSnippets from "./MarkdownSnippets.res.mjs";

function labels(snippets) {
  return snippets.map(s => s.label).join(",");
}

Buntest.describe("MarkdownSnippets.matching", () => {
  Buntest.test("an empty prefix offers every snippet", () => {
    Buntest.expect(MarkdownSnippets.matching("").length).toBe(MarkdownSnippets.all.length);
  });
  Buntest.test("whitespace counts as empty", () => {
    Buntest.expect(MarkdownSnippets.matching("   ").length).toBe(MarkdownSnippets.all.length);
  });
  Buntest.test("matches on prefix", () => {
    Buntest.expect(labels(MarkdownSnippets.matching("h"))).toBe("h1,h2,h3,hr");
  });
  Buntest.test("ignores case", () => {
    Buntest.expect(labels(MarkdownSnippets.matching("MERM"))).toBe("mermaid");
  });
  Buntest.test("returns nothing when no snippet matches", () => {
    Buntest.expect(MarkdownSnippets.matching("zzz").length).toBe(0);
  });
  Buntest.test("matches a prefix, not a substring", () => {
    Buntest.expect(MarkdownSnippets.matching("ermaid").length).toBe(0);
  });
});

Buntest.describe("MarkdownSnippets.all", () => {
  Buntest.test("every caret lands inside its own snippet", () => {
    let offenders = MarkdownSnippets.all.filter(s => {
      if (s.caret < 0) {
        return true;
      } else {
        return s.caret > s.insert.length;
      }
    }).map(s => s.label).join(",");
    Buntest.expect(offenders).toBe("");
  });
  Buntest.test("labels are unique", () => {
    let labels = MarkdownSnippets.all.map(s => s.label);
    let unique = Stdlib_Array.reduce(labels, [], (acc, label) => {
      if (acc.includes(label)) {
        return acc;
      } else {
        return acc.concat([label]);
      }
    });
    Buntest.expect(unique.length).toBe(labels.length);
  });
});

export {
  labels,
}
/*  Not a pure module */
