// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Buntest from "bun:test";
import * as MonthGrid from "./MonthGrid.res.mjs";

Buntest.describe("MonthGrid arithmetic", () => {
  Buntest.test("knows its leap years, exceptions included", () => {
    Buntest.expect(MonthGrid.isLeap(2024)).toBe(true);
    Buntest.expect(MonthGrid.isLeap(2026)).toBe(false);
    Buntest.expect(MonthGrid.isLeap(1900)).toBe(false);
    Buntest.expect(MonthGrid.isLeap(2000)).toBe(true);
    Buntest.expect(MonthGrid.daysInMonth(2024, 2)).toBe(29);
    Buntest.expect(MonthGrid.daysInMonth(2026, 2)).toBe(28);
  });
  Buntest.test("names the weekday of a known day", () => {
    Buntest.expect(MonthGrid.weekday(2026, 8, 11)).toBe(2);
    Buntest.expect(MonthGrid.weekday(2000, 1, 1)).toBe(6);
  });
  Buntest.test("moves through the year, and over its edges", () => {
    Buntest.expect(MonthGrid.shift(2026, 8, 1)).toEqual([
      2026,
      9
    ]);
    Buntest.expect(MonthGrid.shift(2026, 12, 1)).toEqual([
      2027,
      1
    ]);
    Buntest.expect(MonthGrid.shift(2026, 1, -1)).toEqual([
      2025,
      12
    ]);
    Buntest.expect(MonthGrid.shift(2026, 3, -14)).toEqual([
      2025,
      1
    ]);
  });
});

Buntest.describe("MonthGrid.weeks", () => {
  let grid = MonthGrid.weeks(2026, 8, undefined);
  Buntest.test("is always six weeks of seven days", () => {
    Buntest.expect(grid.length).toBe(6);
    Buntest.expect(grid.every(week => week.length === 7)).toBe(true);
  });
  Buntest.test("starts the week on Monday and fills the edges from the months either side", () => {
    let first = grid[0];
    Buntest.expect(first[0].date).toBe("2026-07-27");
    Buntest.expect(first[0].inMonth).toBe(false);
    Buntest.expect(first[5].date).toBe("2026-08-01");
    Buntest.expect(first[5].inMonth).toBe(true);
  });
  Buntest.test("a Sunday-first week moves the whole grid by one", () => {
    let sunday = MonthGrid.weeks(2026, 8, false);
    Buntest.expect(sunday[0][0].date).toBe("2026-07-26");
  });
  Buntest.test("carries every day of the month exactly once", () => {
    let inMonth = grid.flat().filter(day => day.inMonth).map(day => day.date);
    Buntest.expect(inMonth.length).toBe(31);
    Buntest.expect(inMonth[0]).toBe("2026-08-01");
    Buntest.expect(inMonth[30]).toBe("2026-08-31");
  });
  Buntest.test("a February that ends on a Sunday still gets six rows", () => {
    let february = MonthGrid.weeks(2026, 2, undefined);
    Buntest.expect(february.length).toBe(6);
    Buntest.expect(february.flat().length).toBe(42);
  });
});

Buntest.describe("MonthGrid.monthOf and dayOf", () => {
  Buntest.test("reads the written fields, not a parsed instant", () => {
    Buntest.expect(MonthGrid.monthOf("2026-08-11")).toEqual([
      2026,
      8
    ]);
    Buntest.expect(MonthGrid.dayOf("2026-08-11")).toEqual("2026-08-11");
  });
  Buntest.test("a timestamp lands on the day it was written in", () => {
    Buntest.expect(MonthGrid.dayOf("2026-08-11T00:30:00.000Z")).toEqual("2026-08-11");
    Buntest.expect(MonthGrid.monthOf("2026-08-11T00:30:00.000Z")).toEqual([
      2026,
      8
    ]);
  });
  Buntest.test("what is not a date is not a day", () => {
    Buntest.expect(MonthGrid.dayOf("next tuesday")).toEqual(undefined);
    Buntest.expect(MonthGrid.monthOf("")).toEqual(undefined);
  });
});

Buntest.describe("MonthGrid.covers", () => {
  Buntest.test("a span covers its ends and everything between", () => {
    Buntest.expect(MonthGrid.covers("2026-08-09", "2026-08-10", "2026-08-12")).toBe(false);
    Buntest.expect(MonthGrid.covers("2026-08-10", "2026-08-10", "2026-08-12")).toBe(true);
    Buntest.expect(MonthGrid.covers("2026-08-11", "2026-08-10", "2026-08-12")).toBe(true);
    Buntest.expect(MonthGrid.covers("2026-08-12", "2026-08-10", "2026-08-12")).toBe(true);
    Buntest.expect(MonthGrid.covers("2026-08-13", "2026-08-10", "2026-08-12")).toBe(false);
  });
  Buntest.test("crossing a month, and a year, is the same comparison", () => {
    Buntest.expect(MonthGrid.covers("2026-09-01", "2026-08-28", "2026-09-03")).toBe(true);
    Buntest.expect(MonthGrid.covers("2027-01-02", "2026-12-30", "2027-01-04")).toBe(true);
  });
  Buntest.test("no end is one day", () => {
    Buntest.expect(MonthGrid.covers("2026-08-10", "2026-08-10", "")).toBe(true);
    Buntest.expect(MonthGrid.covers("2026-08-11", "2026-08-10", "")).toBe(false);
  });
  Buntest.test("an end before its start covers the start alone", () => {
    Buntest.expect(MonthGrid.covers("2026-08-10", "2026-08-10", "2026-08-01")).toBe(true);
    Buntest.expect(MonthGrid.covers("2026-08-05", "2026-08-10", "2026-08-01")).toBe(false);
  });
});

Buntest.describe("MonthGrid day arithmetic", () => {
  Buntest.test("shiftDays crosses months and years without a Date anywhere", () => {
    Buntest.expect(MonthGrid.shiftDays("2026-08-31", 1)).toBe("2026-09-01");
    Buntest.expect(MonthGrid.shiftDays("2026-01-01", -1)).toBe("2025-12-31");
    Buntest.expect(MonthGrid.shiftDays("2024-02-28", 1)).toBe("2024-02-29");
    Buntest.expect(MonthGrid.shiftDays("2026-08-12", 7)).toBe("2026-08-19");
  });
  Buntest.test("weekDays returns the Monday-first week the anchor falls in", () => {
    let days = MonthGrid.weekDays("2026-08-12", undefined);
    Buntest.expect(days.map(day => day.date).at(0)).toEqual("2026-08-10");
    Buntest.expect(days.length).toBe(7);
    Buntest.expect(days.map(day => day.date).at(6)).toEqual("2026-08-16");
  });
  Buntest.test("weekDays honours Sunday starts", () => {
    let days = MonthGrid.weekDays("2026-08-12", false);
    Buntest.expect(days.map(day => day.date).at(0)).toEqual("2026-08-09");
  });
});

/*  Not a pure module */
