// Generated by ReScript, PLEASE EDIT WITH CARE

import * as DateValue from "./DateValue.res.mjs";
import * as Stdlib_Int from "@rescript/runtime/lib/es6/Stdlib_Int.js";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

function isLeap(year) {
  if (year % 4 === 0) {
    if (year % 100 !== 0) {
      return true;
    } else {
      return year % 400 === 0;
    }
  } else {
    return false;
  }
}

function daysInMonth(year, month) {
  switch (month) {
    case 2 :
      if (isLeap(year)) {
        return 29;
      } else {
        return 28;
      }
    case 4 :
    case 6 :
    case 9 :
    case 11 :
      return 30;
    case 1 :
    case 3 :
    case 5 :
    case 7 :
    case 8 :
    case 10 :
    case 12 :
      return 31;
    default:
      return 0;
  }
}

let weekdayTable = [
  0,
  3,
  2,
  5,
  0,
  3,
  5,
  1,
  4,
  6,
  2,
  4
];

function weekday(year, month, day) {
  let y = month < 3 ? year - 1 | 0 : year;
  let shift = Stdlib_Option.getOr(weekdayTable[month - 1 | 0], 0);
  return (((((y + (y / 4 | 0) | 0) - (y / 100 | 0) | 0) + (y / 400 | 0) | 0) + shift | 0) + day | 0) % 7;
}

function pad(value) {
  if (value < 10) {
    return "0" + value.toString();
  } else {
    return value.toString();
  }
}

function iso(year, month, day) {
  return year.toString() + "-" + pad(month) + "-" + pad(day);
}

function shift(year, month, by) {
  let total = ((year * 12 | 0) + (month - 1 | 0) | 0) + by | 0;
  let wrapped = total % 12;
  let normalised = wrapped < 0 ? wrapped + 12 | 0 : wrapped;
  return [
    (total - normalised | 0) / 12 | 0,
    normalised + 1 | 0
  ];
}

function weeks(year, month, startsMondayOpt) {
  let startsMonday = startsMondayOpt !== undefined ? startsMondayOpt : true;
  let first = weekday(year, month, 1);
  let lead = startsMonday ? (first + 6 | 0) % 7 : first;
  let match = shift(year, month, -1);
  let previousMonth = match[1];
  let previousYear = match[0];
  let match$1 = shift(year, month, 1);
  let nextMonth = match$1[1];
  let nextYear = match$1[0];
  let inThis = daysInMonth(year, month);
  let inPrevious = daysInMonth(previousYear, previousMonth);
  return Stdlib_Array.make(6, 0).map((param, week) => Stdlib_Array.make(7, 0).map((param, index) => {
    let offset = ((week * 7 | 0) + index | 0) - lead | 0;
    if (offset < 0) {
      let number = (inPrevious + offset | 0) + 1 | 0;
      return {
        date: iso(previousYear, previousMonth, number),
        number: number,
        inMonth: false
      };
    }
    if (offset < inThis) {
      let number$1 = offset + 1 | 0;
      return {
        date: iso(year, month, number$1),
        number: number$1,
        inMonth: true
      };
    }
    let number$2 = (offset - inThis | 0) + 1 | 0;
    return {
      date: iso(nextYear, nextMonth, number$2),
      number: number$2,
      inMonth: false
    };
  }));
}

function monthOf(value) {
  let match = DateValue.classify(value);
  if (match === undefined) {
    return;
  }
  let match$1 = Stdlib_Int.fromString(value.slice(0, 4), undefined);
  let match$2 = Stdlib_Int.fromString(value.slice(5, 7), undefined);
  if (match$1 !== undefined && match$2 !== undefined) {
    return [
      match$1,
      match$2
    ];
  }
}

function dayOf(value) {
  let match = DateValue.classify(value);
  if (match !== undefined) {
    return value.slice(0, 10);
  }
}

function covers(day, from, until) {
  if (until === "" || until < from) {
    return day === from;
  } else if (from <= day) {
    return day <= until;
  } else {
    return false;
  }
}

function serialOf(date) {
  let written = dayOf(date);
  if (written === undefined) {
    return;
  }
  let year = Stdlib_Option.getOr(Stdlib_Int.fromString(written.slice(0, 4), undefined), 0);
  let month = Stdlib_Option.getOr(Stdlib_Int.fromString(written.slice(5, 7), undefined), 1);
  let d = Stdlib_Option.getOr(Stdlib_Int.fromString(written.slice(8, 10), undefined), 1);
  let y = month <= 2 ? year - 1 | 0 : year;
  let era = (
    y >= 0 ? y : y - 399 | 0
  ) / 400 | 0;
  let yoe = y - (era * 400 | 0) | 0;
  let doy = ((((153 * (month + (
    month > 2 ? -3 : 9
  ) | 0) | 0) + 2 | 0) / 5 | 0) + d | 0) - 1 | 0;
  let doe = (((yoe * 365 | 0) + (yoe / 4 | 0) | 0) - (yoe / 100 | 0) | 0) + doy | 0;
  return ((era * 146097 | 0) + doe | 0) - 719468 | 0;
}

function dateOf(serial) {
  let shifted = serial + 719468 | 0;
  let era = (
    shifted >= 0 ? shifted : shifted - 146096 | 0
  ) / 146097 | 0;
  let doe = shifted - (era * 146097 | 0) | 0;
  let yoe = (((doe - (doe / 1460 | 0) | 0) + (doe / 36524 | 0) | 0) - (doe / 146096 | 0) | 0) / 365 | 0;
  let y = yoe + (era * 400 | 0) | 0;
  let doy = doe - (((365 * yoe | 0) + (yoe / 4 | 0) | 0) - (yoe / 100 | 0) | 0) | 0;
  let mp = ((5 * doy | 0) + 2 | 0) / 153 | 0;
  let d = (doy - (((153 * mp | 0) + 2 | 0) / 5 | 0) | 0) + 1 | 0;
  let m = mp + (
    mp < 10 ? 3 : -9
  ) | 0;
  let year = m <= 2 ? y + 1 | 0 : y;
  return iso(year, m, d);
}

function shiftDays(day, by) {
  let serial = serialOf(day);
  if (serial !== undefined) {
    return dateOf(serial + by | 0);
  } else {
    return day;
  }
}

function weekDays(anchor, startsMondayOpt) {
  let startsMonday = startsMondayOpt !== undefined ? startsMondayOpt : true;
  let serial = serialOf(anchor);
  if (serial === undefined) {
    return [];
  }
  let weekdayOf = s => ((s + 4 | 0) % 7 + 7 | 0) % 7;
  let start = startsMonday ? serial - (weekdayOf(serial) + 6 | 0) % 7 | 0 : serial - weekdayOf(serial) | 0;
  return Stdlib_Array.fromInitializer(7, offset => {
    let date = dateOf(start + offset | 0);
    return {
      date: date,
      number: Stdlib_Option.getOr(Stdlib_Int.fromString(date.slice(8, 10), undefined), 1),
      inMonth: true
    };
  });
}

export {
  isLeap,
  daysInMonth,
  weekday,
  shift,
  weeks,
  monthOf,
  dayOf,
  covers,
  shiftDays,
  weekDays,
}
/* No side effect */
