// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Numeric from "./Numeric.res.mjs";
import * as Buntest from "bun:test";

Buntest.describe("Numeric.parse", () => {
  Buntest.test("reads a value that is a number all the way through", () => {
    Buntest.expect(Numeric.parse("42")).toEqual(42.0);
    Buntest.expect(Numeric.parse("  2.50 ")).toEqual(2.5);
    Buntest.expect(Numeric.parse("-0.5")).toEqual(-0.5);
    Buntest.expect(Numeric.parse("+3")).toEqual(3.0);
    Buntest.expect(Numeric.parse(".5")).toEqual(0.5);
    Buntest.expect(Numeric.parse("7.")).toEqual(7.0);
    Buntest.expect(Numeric.parse("1e3")).toEqual(1000.0);
  });
  Buntest.test("a numeric prefix is not a number", () => {
    Buntest.expect(Numeric.parse("2026-08-10T17:50:45.880Z")).toEqual(undefined);
    Buntest.expect(Numeric.parse("2026-08-10")).toEqual(undefined);
    Buntest.expect(Numeric.parse("10 items")).toEqual(undefined);
    Buntest.expect(Numeric.parse("3, please")).toEqual(undefined);
    Buntest.expect(Numeric.parse("12:30")).toEqual(undefined);
  });
  Buntest.test("refuses what nobody types into a form", () => {
    Buntest.expect(Numeric.parse("")).toEqual(undefined);
    Buntest.expect(Numeric.parse("   ")).toEqual(undefined);
    Buntest.expect(Numeric.parse("Infinity")).toEqual(undefined);
    Buntest.expect(Numeric.parse("NaN")).toEqual(undefined);
    Buntest.expect(Numeric.parse("0x10")).toEqual(undefined);
    Buntest.expect(Numeric.parse("1,5")).toEqual(undefined);
  });
  Buntest.test("isNumber answers what parse would", () => {
    Buntest.expect(Numeric.isNumber("7")).toBe(true);
    Buntest.expect(Numeric.isNumber("7 days")).toBe(false);
  });
});

/*  Not a pure module */
