// Generated by ReScript, PLEASE EDIT WITH CARE


let references = (function (sql) {
  const seen = [];
  const pattern = /'\{#([A-Za-z0-9_.]+)\}'|\{#([A-Za-z0-9_.]+)\}/g;
  let found;
  while ((found = pattern.exec(sql))) {
    const key = found[1] || found[2];
    if (key && !seen.includes(key)) seen.push(key);
  }
  return seen;
});

let bind = (function (sql, lookup) {
  const params = [];
  const bound = sql.replace(
    /'\{#([A-Za-z0-9_.]+)\}'|\{#([A-Za-z0-9_.]+)\}/g,
    (_, quoted, bare) => {
      const value = lookup(quoted || bare);
      params.push(value === undefined ? "" : value);
      return "?";
    },
  );
  return [bound, params];
});

export {
  references,
  bind,
}
/* No side effect */
