// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Buntest from "bun:test";
import * as RecoveryCode from "./RecoveryCode.res.mjs";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

Buntest.describe("RecoveryCode", () => {
  let bytes = Stdlib_Array.fromInitializer(20, i => ((i * 37 | 0) + 5 | 0) % 256);
  Buntest.test("formats twenty bytes as eight groups of four", () => {
    let code = RecoveryCode.format(bytes);
    if (code !== undefined) {
      Buntest.expect(code.length).toBe(39);
      Buntest.expect(code.split("-").length).toBe(8);
      Buntest.expect(code.split("-").every(g => g.length === 4)).toBe(true);
    } else {
      Buntest.expect(true).toBe(false);
    }
  });
  Buntest.test("round-trips through parse", () => {
    let code = Stdlib_Option.getOr(RecoveryCode.format(bytes), "");
    Buntest.expect(RecoveryCode.parse(code)).toEqual(bytes);
  });
  Buntest.test("forgives case, spacing and lookalikes", () => {
    let code = Stdlib_Option.getOr(RecoveryCode.format(bytes), "");
    let sloppy = code.toLowerCase().replaceAll("-", " ").replaceAll("0", "O").replaceAll("1", "l");
    Buntest.expect(RecoveryCode.parse(sloppy)).toEqual(bytes);
  });
  Buntest.test("refuses what is not a code", () => {
    Buntest.expect(RecoveryCode.parse("")).toEqual(undefined);
    Buntest.expect(RecoveryCode.parse("ABCD-EFGH")).toEqual(undefined);
    Buntest.expect(RecoveryCode.format([
      1,
      2,
      3
    ])).toEqual(undefined);
    Buntest.expect(RecoveryCode.format(Stdlib_Array.fromInitializer(20, param => 999))).toEqual(undefined);
  });
  Buntest.test("all-zero and all-max bytes both survive", () => {
    let zeros = Stdlib_Array.fromInitializer(20, param => 0);
    let maxed = Stdlib_Array.fromInitializer(20, param => 255);
    Buntest.expect(Stdlib_Option.flatMap(RecoveryCode.format(zeros), RecoveryCode.parse)).toEqual(zeros);
    Buntest.expect(Stdlib_Option.flatMap(RecoveryCode.format(maxed), RecoveryCode.parse)).toEqual(maxed);
  });
});

/*  Not a pure module */
