// Generated by ReScript, PLEASE EDIT WITH CARE


let alphabet = "0123456789ABCDEFGHJKMNPQRSTVWXYZ";

function format(bytes) {
  if (bytes.length !== 20 || bytes.some(b => {
      if (b < 0) {
        return true;
      } else {
        return b > 255;
      }
    })) {
    return;
  }
  let chars = [];
  let buffer = {
    contents: 0
  };
  let bits = {
    contents: 0
  };
  bytes.forEach(byte => {
    buffer.contents = (buffer.contents << 8) | byte;
    bits.contents = bits.contents + 8 | 0;
    while (bits.contents >= 5) {
      bits.contents = bits.contents - 5 | 0;
      let index = (buffer.contents >> bits.contents) & 31;
      chars.push(alphabet.charAt(index));
    };
  });
  let joined = chars.join("");
  let groups = [];
  for (let group = 0; group <= 7; ++group) {
    groups.push(joined.slice((group << 2), (group << 2) + 4 | 0));
  }
  return groups.join("-");
}

function parse(text) {
  let cleaned = text.toUpperCase().replaceAll("O", "0").replaceAll("I", "1").replaceAll("L", "1").split("").filter(char => alphabet.includes(char)).join("");
  if (cleaned.length !== 32) {
    return;
  }
  let bytes = [];
  let buffer = {
    contents: 0
  };
  let bits = {
    contents: 0
  };
  cleaned.split("").forEach(char => {
    buffer.contents = (buffer.contents << 5) | alphabet.indexOf(char);
    bits.contents = bits.contents + 5 | 0;
    if (bits.contents >= 8) {
      bits.contents = bits.contents - 8 | 0;
      bytes.push((buffer.contents >> bits.contents) & 255);
      return;
    }
  });
  return bytes;
}

let byteLength = 20;

export {
  byteLength,
  format,
  parse,
}
/* No side effect */
