// Generated by ReScript, PLEASE EDIT WITH CARE

import * as AppId from "./AppId.res.mjs";
import * as ShareLink from "./ShareLink.res.mjs";
import * as SpaceLink from "./SpaceLink.res.mjs";
import * as CatalogLink from "./CatalogLink.res.mjs";

let editSuffix = "edit";

let appSegment = "a";

function segments(path) {
  return path.replace("#", "").split("?")[0].split("/").filter(segment => segment !== "");
}

function parse(path) {
  let match = segments(path);
  let len = match.length;
  if (len >= 4) {
    return "Gallery";
  }
  switch (len) {
    case 0 :
      return "Gallery";
    case 1 :
      let only = match[0];
      if (only === ShareLink.segment) {
        return {
          TAG: "Shared",
          _0: undefined
        };
      } else {
        return "Gallery";
      }
    case 2 :
      let first = match[0];
      let id = match[1];
      if (first === ShareLink.segment && ShareLink.isShortId(id)) {
        return {
          TAG: "Shared",
          _0: id
        };
      } else if (first === SpaceLink.segment && SpaceLink.isInviteId(id)) {
        return {
          TAG: "Join",
          _0: id
        };
      } else if (first === CatalogLink.segment && AppId.isValid(id)) {
        return {
          TAG: "Catalog",
          _0: id
        };
      } else if (first === appSegment && AppId.isValid(id)) {
        return {
          TAG: "View",
          _0: id
        };
      } else {
        return "Gallery";
      }
    case 3 :
      let segment = match[0];
      let id$1 = match[1];
      let suffix = match[2];
      if (segment === appSegment && suffix === editSuffix && AppId.isValid(id$1)) {
        return {
          TAG: "Edit",
          _0: id$1
        };
      } else {
        return "Gallery";
      }
  }
}

function toPath(route) {
  if (typeof route !== "object") {
    return "/";
  }
  switch (route.TAG) {
    case "View" :
      return "/" + appSegment + "/" + route._0;
    case "Edit" :
      return "/" + appSegment + "/" + route._0 + "/" + editSuffix;
    case "Shared" :
      let id = route._0;
      if (id !== undefined) {
        return ShareLink.path + "/" + id;
      } else {
        return ShareLink.path;
      }
    case "Join" :
      return SpaceLink.path + "/" + route._0;
    case "Catalog" :
      return "/" + CatalogLink.segment + "/" + route._0;
  }
}

function appId(route) {
  if (typeof route !== "object") {
    return;
  }
  switch (route.TAG) {
    case "View" :
    case "Edit" :
      return route._0;
    default:
      return;
  }
}

function isEditing(route) {
  if (typeof route !== "object") {
    return false;
  } else {
    return route.TAG === "Edit";
  }
}

export {
  parse,
  toPath,
  appId,
  isEditing,
}
/* ShareLink Not a pure module */
