// Generated by ReScript, PLEASE EDIT WITH CARE

import * as RowExpr from "./RowExpr.res.mjs";
import * as Buntest from "bun:test";
import * as Aggregate from "./Aggregate.res.mjs";
import * as RowTemplate from "./RowTemplate.res.mjs";

function row(key) {
  switch (key) {
    case "prezzo" :
      return "2.50";
    case "qta" :
      return "3";
    case "vuoto" :
      return "";
    default:
      return;
  }
}

Buntest.describe("RowExpr", () => {
  Buntest.test("multiplies the row's own fields", () => {
    Buntest.expect(RowExpr.evaluate("qta*prezzo", row)).toEqual(7.5);
  });
  Buntest.test("a missing field is zero", () => {
    Buntest.expect(RowExpr.evaluate("qta + manca", row)).toEqual(3.0);
  });
  Buntest.test("constants mix in", () => {
    Buntest.expect(RowExpr.evaluate("qta*prezzo*1.22", row)).toEqual(9.15);
  });
  Buntest.test("a-b is a field name, not a subtraction", () => {
    Buntest.expect(RowExpr.looksLike("qta-prezzo")).toBe(false);
    Buntest.expect(RowExpr.looksLike("qta - prezzo")).toBe(true);
    Buntest.expect(RowExpr.evaluate("qta - prezzo", row)).toEqual(0.5);
  });
  Buntest.test("prose with braces does not parse", () => {
    Buntest.expect(RowExpr.parses("display: block")).toBe(false);
    Buntest.expect(RowExpr.parses("qta*prezzo")).toBe(true);
  });
});

Buntest.describe("RowTemplate row arithmetic", () => {
  let record_fields = [
    {
      name: "voce",
      value: "Viti"
    },
    {
      name: "qta",
      value: "4"
    },
    {
      name: "prezzo",
      value: "1.50"
    }
  ];
  let record = {
    id: "r1",
    fields: record_fields
  };
  Buntest.test("computes per row, two decimals", () => {
    Buntest.expect(RowTemplate.fill("{voce}: {qta*prezzo}", record, undefined, undefined)).toBe("Viti: 6.00");
  });
  Buntest.test("what is not arithmetic stays as written", () => {
    Buntest.expect(RowTemplate.fill("{a b c} testo", record, undefined, undefined)).toBe("{a b c} testo");
  });
});

Buntest.describe("Aggregate over an expression field", () => {
  let collection = {
    records: [
      {
        id: "a",
        fields: [
          {
            name: "qta",
            value: "2"
          },
          {
            name: "prezzo",
            value: "10"
          }
        ]
      },
      {
        id: "b",
        fields: [
          {
            name: "qta",
            value: "3"
          },
          {
            name: "prezzo",
            value: "5"
          }
        ]
      },
      {
        id: "c",
        fields: [{
            name: "qta",
            value: "1"
          }]
      }
    ]
  };
  Buntest.test("sums qta*prezzo across the rows", () => {
    Buntest.expect(Aggregate.compute("Sum", collection, "qta*prezzo", undefined)).toEqual("35");
  });
  Buntest.test("a plain field still behaves as before", () => {
    Buntest.expect(Aggregate.compute("Sum", collection, "qta", undefined)).toEqual("6");
  });
});

export {
  row,
}
/*  Not a pure module */
