// Generated by ReScript, PLEASE EDIT WITH CARE

import * as RowView from "./RowView.res.mjs";
import * as Buntest from "bun:test";

function row(id, fields) {
  return {
    id: id,
    fields: fields.map(param => ({
      name: param[0],
      value: param[1]
    }))
  };
}

let rows = [
  row("1", [
    [
      "who",
      "Ada"
    ],
    [
      "price",
      "9"
    ],
    [
      "what",
      "Cavo USB"
    ]
  ]),
  row("2", [
    [
      "who",
      "Bo"
    ],
    [
      "price",
      "10"
    ],
    [
      "what",
      "Tastiera"
    ]
  ]),
  row("3", [
    [
      "who",
      "Ada"
    ],
    [
      "price",
      "2"
    ],
    [
      "what",
      "Cavo HDMI"
    ]
  ])
];

function names(found) {
  return found.map(r => r.id).join(",");
}

Buntest.describe("RowView.sort", () => {
  Buntest.test("orders numbers as numbers", () => {
    Buntest.expect(names(RowView.sort(rows, "price", "Ascending"))).toBe("3,1,2");
    Buntest.expect(names(RowView.sort(rows, "price", "Descending"))).toBe("2,1,3");
  });
  Buntest.test("orders text as text, case-insensitively", () => {
    Buntest.expect(names(RowView.sort(rows, "what", "Ascending"))).toBe("3,1,2");
  });
  Buntest.test("rows that tie keep the order they were stored in", () => {
    Buntest.expect(names(RowView.sort(rows, "who", "Ascending"))).toBe("1,3,2");
  });
  Buntest.test("orders timestamps as text, not as the year they start with", () => {
    let stamped = [
      row("1", [[
          "createdAt",
          "2026-08-10T17:50:45.880Z"
        ]]),
      row("2", [[
          "createdAt",
          "2026-08-10T17:50:46.264Z"
        ]]),
      row("3", [[
          "createdAt",
          "2026-08-10T17:50:46.664Z"
        ]])
    ];
    Buntest.expect(names(RowView.sort(stamped, "createdAt", "Descending"))).toBe("3,2,1");
  });
  Buntest.test("numbers sort before text, whatever the order of comparison", () => {
    let mixed = [
      row("1", [[
          "v",
          "abc"
        ]]),
      row("2", [[
          "v",
          "10"
        ]]),
      row("3", [[
          "v",
          "5"
        ]]),
      row("4", [[
          "v",
          "zz"
        ]])
    ];
    Buntest.expect(names(RowView.sort(mixed, "v", "Ascending"))).toBe("3,2,1,4");
  });
  Buntest.test("no field means no reordering", () => {
    Buntest.expect(names(RowView.sort(rows, "", "Descending"))).toBe("1,2,3");
  });
});

Buntest.describe("RowView.search", () => {
  let over = query => names(RowView.search(rows, query, [
    "who",
    "what"
  ]));
  Buntest.test("matches from the middle of a value", () => {
    Buntest.expect(over("dmi")).toBe("3");
  });
  Buntest.test("every word must match, so a second word narrows", () => {
    Buntest.expect(over("cavo")).toBe("1,3");
    Buntest.expect(over("cavo hdmi")).toBe("3");
  });
  Buntest.test("only the fields it was given", () => {
    Buntest.expect(names(RowView.search(rows, "9", [
      "who",
      "what"
    ]))).toBe("");
  });
  Buntest.test("an empty query is not a filter", () => {
    Buntest.expect(over("   ")).toBe("1,2,3");
  });
});

Buntest.describe("RowView.filter", () => {
  Buntest.test("matches one field exactly, ignoring case", () => {
    Buntest.expect(names(RowView.filter(rows, "who=ada"))).toBe("1,3");
  });
  Buntest.test("a partial value does not match", () => {
    Buntest.expect(names(RowView.filter(rows, "who=Ad"))).toBe("");
  });
  Buntest.test("something that is not field=value filters nothing", () => {
    Buntest.expect(names(RowView.filter(rows, "who"))).toBe("1,2,3");
    Buntest.expect(names(RowView.filter(rows, "=Ada"))).toBe("1,2,3");
  });
});

Buntest.describe("RowView.filterAll and values", () => {
  Buntest.test("two filters narrow to the rows that satisfy both", () => {
    Buntest.expect(names(RowView.filterAll(rows, [
      "who=ada",
      "price=2"
    ]))).toBe("3");
  });
  Buntest.test("an empty filter narrows nothing", () => {
    Buntest.expect(names(RowView.filterAll(rows, [
      "",
      "who=ada"
    ]))).toBe("1,3");
    Buntest.expect(names(RowView.filterAll(rows, []))).toBe("1,2,3");
  });
  Buntest.test("the values offered are the distinct ones, ordered", () => {
    Buntest.expect(RowView.values(rows, "who").join(",")).toBe("Ada,Bo");
    Buntest.expect(RowView.values(rows, "price").join(",")).toBe("2,9,10");
  });
  Buntest.test("a blank is not something to choose", () => {
    let withBlank = rows.concat([row("4", [[
          "who",
          ""
        ]])]);
    Buntest.expect(RowView.values(withBlank, "who").join(",")).toBe("Ada,Bo");
  });
});

Buntest.describe("RowView.limit and page", () => {
  Buntest.test("limit takes the first rows, and zero means all", () => {
    Buntest.expect(names(RowView.limit(rows, 2))).toBe("1,2");
    Buntest.expect(names(RowView.limit(rows, 0))).toBe("1,2,3");
  });
  Buntest.test("pages are counted with the remainder", () => {
    Buntest.expect(RowView.pageCount(3, 2)).toBe(2);
    Buntest.expect(RowView.pageCount(4, 2)).toBe(2);
  });
  Buntest.test("there is always at least one page", () => {
    Buntest.expect(RowView.pageCount(0, 10)).toBe(1);
  });
  Buntest.test("a page beyond the end lands on the last one", () => {
    Buntest.expect(names(RowView.page(rows, 2, 9))).toBe("3");
    Buntest.expect(names(RowView.page(rows, 2, -4))).toBe("1,2");
  });
  Buntest.test("no page size means no paging", () => {
    Buntest.expect(names(RowView.page(rows, 0, 3))).toBe("1,2,3");
  });
});

Buntest.describe("RowView.groups", () => {
  Buntest.test("gathers by a field, in first-appearance order", () => {
    let gathered = RowView.groups(rows, "who").map(param => param[0] + ":" + names(param[1]));
    Buntest.expect(gathered.join(" | ")).toBe("Ada:1,3 | Bo:2");
  });
  Buntest.test("rows with no such field gather under the empty name", () => {
    let gathered = RowView.groups(rows, "missing").map(param => param[0]);
    Buntest.expect(gathered.join(",")).toBe("");
  });
  Buntest.test("no field is one group of everything", () => {
    Buntest.expect(RowView.groups(rows, "").length).toBe(1);
  });
});

export {
  row,
  rows,
  names,
}
/* rows Not a pure module */
