// Generated by ReScript, PLEASE EDIT WITH CARE

import * as SafeUrl from "./SafeUrl.res.mjs";
import * as Buntest from "bun:test";

function render(result) {
  if (result.TAG === "Ok") {
    return "ok:" + SafeUrl.toString(result._0);
  } else {
    return "rejected:" + SafeUrl.errorToString(result._0);
  }
}

function parse(raw) {
  return render(SafeUrl.parse(raw));
}

Buntest.describe("SafeUrl.parse — accepts", () => {
  Buntest.test("https URLs", () => {
    Buntest.expect(render(SafeUrl.parse("https://example.com/a?b=1#c"))).toBe("ok:https://example.com/a?b=1#c");
  });
  Buntest.test("http URLs", () => {
    Buntest.expect(render(SafeUrl.parse("http://example.com"))).toBe("ok:http://example.com");
  });
  Buntest.test("mailto links", () => {
    Buntest.expect(render(SafeUrl.parse("mailto:someone@example.com"))).toBe("ok:mailto:someone@example.com");
  });
  Buntest.test("site-relative paths", () => {
    Buntest.expect(render(SafeUrl.parse("/about"))).toBe("ok:/about");
  });
  Buntest.test("fragments and queries", () => {
    Buntest.expect(render(SafeUrl.parse("#section"))).toBe("ok:#section");
    Buntest.expect(render(SafeUrl.parse("?page=2"))).toBe("ok:?page=2");
  });
  Buntest.test("a path containing a colon, which is not a scheme", () => {
    Buntest.expect(render(SafeUrl.parse("/notes/10:30"))).toBe("ok:/notes/10:30");
  });
  Buntest.test("uppercase schemes, matched case-insensitively", () => {
    Buntest.expect(render(SafeUrl.parse("HTTPS://example.com"))).toBe("ok:HTTPS://example.com");
  });
});

Buntest.describe("SafeUrl.parse — rejects", () => {
  Buntest.test("javascript: URLs", () => {
    Buntest.expect(render(SafeUrl.parse("javascript:alert(1)"))).toBe(`rejected:The "javascript:" scheme is not allowed.`);
  });
  Buntest.test("javascript: disguised by case", () => {
    Buntest.expect(render(SafeUrl.parse("JaVaScRiPt:alert(1)"))).toBe(`rejected:The "javascript:" scheme is not allowed.`);
  });
  Buntest.test("javascript: disguised by leading whitespace", () => {
    Buntest.expect(render(SafeUrl.parse("   javascript:alert(1)"))).toBe(`rejected:The "javascript:" scheme is not allowed.`);
  });
  Buntest.test("javascript: split by a tab", () => {
    Buntest.expect(render(SafeUrl.parse("java\tscript:alert(1)"))).toBe(`rejected:The "javascript:" scheme is not allowed.`);
  });
  Buntest.test("javascript: split by a newline", () => {
    Buntest.expect(render(SafeUrl.parse("java\nscript:alert(1)"))).toBe(`rejected:The "javascript:" scheme is not allowed.`);
  });
  Buntest.test("javascript: split by a NUL byte", () => {
    let nul = String.fromCharCode(0);
    Buntest.expect(render(SafeUrl.parse("java" + nul + "script:alert(1)"))).toBe(`rejected:The "javascript:" scheme is not allowed.`);
  });
  Buntest.test("data: URLs", () => {
    Buntest.expect(render(SafeUrl.parse("data:text/html,<script>alert(1)</script>"))).toBe(`rejected:The "data:" scheme is not allowed.`);
  });
  Buntest.test("vbscript: URLs", () => {
    Buntest.expect(render(SafeUrl.parse("vbscript:msgbox(1)"))).toBe(`rejected:The "vbscript:" scheme is not allowed.`);
  });
  Buntest.test("protocol-relative URLs, which leave the origin silently", () => {
    Buntest.expect(render(SafeUrl.parse("//evil.example/path"))).toBe("rejected:Protocol-relative links are not allowed.");
  });
  Buntest.test("the empty string", () => {
    Buntest.expect(render(SafeUrl.parse(""))).toBe("rejected:The link is empty.");
    Buntest.expect(render(SafeUrl.parse("   "))).toBe("rejected:The link is empty.");
  });
});

Buntest.describe("SafeUrl.toString", () => {
  Buntest.test("returns the normalised href, not the raw input", () => {
    Buntest.expect(render(SafeUrl.parse("  https://example.com  "))).toBe("ok:https://example.com");
  });
});

export {
  render,
  parse,
}
/*  Not a pure module */
