// Generated by ReScript, PLEASE EDIT WITH CARE


let allowedSchemes = [
  "http",
  "https",
  "mailto"
];

let controlCharacters = new RegExp("[\\u0000-\\u001f\\u007f]", "g");

function normalise(raw) {
  return raw.replace(controlCharacters, "").trim();
}

function schemeAt(input, _index) {
  while (true) {
    let index = _index;
    if (index >= input.length) {
      return;
    }
    let match = input.charAt(index);
    switch (match) {
      case ":" :
        return input.slice(0, index).toLowerCase();
      case "#" :
      case "/" :
      case "?" :
        return;
      default:
        _index = index + 1 | 0;
        continue;
    }
  };
}

function parse(raw) {
  let input = normalise(raw);
  if (input === "") {
    return {
      TAG: "Error",
      _0: "Empty"
    };
  }
  if (input.startsWith("//")) {
    return {
      TAG: "Error",
      _0: "ProtocolRelative"
    };
  }
  let scheme = schemeAt(input, 0);
  if (scheme !== undefined && !allowedSchemes.includes(scheme)) {
    return {
      TAG: "Error",
      _0: {
        TAG: "DisallowedScheme",
        _0: scheme
      }
    };
  } else {
    return {
      TAG: "Ok",
      _0: {
        TAG: "Safe",
        _0: input
      }
    };
  }
}

function toString(value) {
  return value._0;
}

function errorToString(error) {
  if (typeof error !== "object") {
    if (error === "Empty") {
      return "The link is empty.";
    } else {
      return "Protocol-relative links are not allowed.";
    }
  } else {
    return `The "` + error._0 + `:" scheme is not allowed.`;
  }
}

export {
  allowedSchemes,
  parse,
  toString,
  errorToString,
}
/* controlCharacters Not a pure module */
