// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Buntest from "bun:test";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

let readFile = (function (path) { return require("node:fs").readFileSync(path, "utf8"); });

function configDirectives() {
  let source = readFile("vite.config.js");
  let block = Stdlib_Option.getOr(Stdlib_Option.flatMap(Stdlib_Option.flatMap(Primitive_option.fromNullable(new RegExp("const CSP_DIRECTIVES = \\[([\\s\\S]*?)\\];").exec(source)), result => result.slice(1).at(0)), value => value), "");
  return block.split("\n").filter(line => !line.trim().startsWith("//")).map(line => {
    let found = [];
    let pattern = new RegExp("\"([^\"]+)\"", "g");
    let walk = () => {
      while (true) {
        let result = pattern.exec(line);
        if (result == null) {
          return;
        }
        let directive = Stdlib_Option.flatMap(result.slice(1).at(0), v => v);
        if (directive === undefined) {
          return;
        }
        found.push(directive);
        continue;
      };
    };
    walk();
    return found;
  }).flat();
}

function headerPolicy() {
  let file = readFile("public/_headers");
  return Stdlib_Option.getOr(Stdlib_Option.map(file.split("\n").find(line => line.trim().startsWith("Content-Security-Policy:")), line => line.trim().slice("Content-Security-Policy:".length).trim()), "");
}

function caddyPolicy() {
  let file = readFile("Caddyfile");
  return Stdlib_Option.getOr(Stdlib_Option.flatMap(file.split("\n").find(line => line.trim().startsWith("Content-Security-Policy ")), line => Stdlib_Option.flatMap(Stdlib_Option.flatMap(Primitive_option.fromNullable(new RegExp("\"([^\"]+)\"").exec(line)), result => result.slice(1).at(0)), value => value)), "");
}

Buntest.describe("the three copies of the security policy", () => {
  Buntest.test("public/_headers carries exactly the policy vite.config.js defines", () => {
    Buntest.expect(headerPolicy()).toBe(configDirectives().join("; "));
  });
  Buntest.test("the Caddyfile carries exactly the policy vite.config.js defines", () => {
    Buntest.expect(caddyPolicy()).toBe(configDirectives().join("; "));
  });
  Buntest.test("the analytics script has an origin to load from in every copy", () => {
    Buntest.expect(headerPolicy().includes("https://api.pirsch.io")).toBe(true);
    Buntest.expect(caddyPolicy().includes("https://api.pirsch.io")).toBe(true);
  });
  Buntest.test("the tokens ::python depends on are in both", () => {
    let policy = headerPolicy();
    Buntest.expect(policy.includes("'wasm-unsafe-eval'")).toBe(true);
    Buntest.expect(policy.includes("connect-src 'self' https:")).toBe(true);
    Buntest.expect(policy.includes("worker-src 'self' blob:")).toBe(true);
  });
  Buntest.test("the grants ::map and ::api-query depend on are in both", () => {
    let policy = headerPolicy();
    Buntest.expect(policy.includes("img-src 'self' data: https:")).toBe(true);
  });
});

export {
  readFile,
  configDirectives,
  headerPolicy,
  caddyPolicy,
}
/*  Not a pure module */
