// Generated by ReScript, PLEASE EDIT WITH CARE


let segment = "s";

let marker = "1";

let path = "/" + segment;

function of_(origin, payload) {
  return origin + path + "#" + marker + payload;
}

function payloadOf(fragment) {
  let value = fragment.startsWith("#") ? fragment.slice(1) : fragment;
  if (value.startsWith(marker) && value.length > marker.length) {
    return value.slice(marker.length);
  }
}

function fits(payload) {
  return payload.length <= 8000;
}

function message(title, invitation) {
  if (title === "") {
    return invitation;
  } else {
    return title + " — " + invitation;
  }
}

function fitsStored(payload) {
  return payload.length <= 140000;
}

let shortIdPattern = new RegExp("^[A-Za-z0-9_-]{8,40}$");

function isShortId(candidate) {
  return shortIdPattern.test(candidate);
}

let keyMarker = "k";

function shortOf(origin, id, key) {
  return origin + path + "/" + id + "#" + keyMarker + key;
}

function keyOf(fragment) {
  let value = fragment.startsWith("#") ? fragment.slice(1) : fragment;
  if (value.startsWith(keyMarker) && value.length > keyMarker.length) {
    return value.slice(keyMarker.length);
  }
}

let ceiling = 8000;

let storedCeiling = 140000;

export {
  path,
  segment,
  ceiling,
  of_,
  payloadOf,
  fits,
  message,
  storedCeiling,
  fitsStored,
  isShortId,
  shortOf,
  keyOf,
}
/* shortIdPattern Not a pure module */
