// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Sheet from "./Sheet.res.mjs";
import * as Buntest from "bun:test";
import * as Collection from "./Collection.res.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

let collection = {
  records: [
    {
      id: "a1",
      fields: [
        {
          name: "voce",
          value: "Pane"
        },
        {
          name: "importo",
          value: "2"
        }
      ]
    },
    {
      id: "b2",
      fields: [
        {
          name: "voce",
          value: "Latte"
        },
        {
          name: "note",
          value: "bio"
        }
      ]
    }
  ]
};

Buntest.describe("Sheet.encode", () => {
  Buntest.test("header is id plus the union of fields, rows are rectangular", () => {
    let grid = Sheet.encode(collection);
    Buntest.expect(grid[0]).toEqual([
      "id",
      "voce",
      "importo",
      "note"
    ]);
    Buntest.expect(grid[1]).toEqual([
      "a1",
      "Pane",
      "2",
      ""
    ]);
    Buntest.expect(grid[2]).toEqual([
      "b2",
      "Latte",
      "",
      "bio"
    ]);
  });
});

Buntest.describe("Sheet.decode", () => {
  let mint = used => "new-" + used.length.toString();
  Buntest.test("round-trips, ids and all", () => {
    let records = Sheet.decode(Sheet.encode(collection), mint);
    Buntest.expect(records.map(r => r.id)).toEqual([
      "a1",
      "b2"
    ]);
    Buntest.expect(Collection.field(records[1], "note")).toEqual("bio");
  });
  Buntest.test("a file without ids gets fresh ones", () => {
    let records = Sheet.decode([
      ["voce"],
      ["Pane"],
      ["Latte"]
    ], mint);
    Buntest.expect(records.map(r => r.id)).toEqual([
      "new-0",
      "new-1"
    ]);
  });
  Buntest.test("blank rows and blank cells are skipped", () => {
    let records = Sheet.decode([
      [
        "voce",
        "note"
      ],
      [
        "",
        ""
      ],
      [
        "Pane",
        ""
      ]
    ], mint);
    Buntest.expect(records.length).toBe(1);
    Buntest.expect(Stdlib_Option.isNone(Collection.field(records[0], "note"))).toBe(true);
  });
  Buntest.test("a duplicated id in the file does not collide with itself", () => {
    let records = Sheet.decode([
      [
        "id",
        "voce"
      ],
      [
        "x",
        "Pane"
      ],
      [
        "x",
        "Latte"
      ]
    ], mint);
    Buntest.expect(records[0].id).toBe("x");
    Buntest.expect(records[1].id).toBe("new-1");
  });
});

export {
  collection,
}
/*  Not a pure module */
