// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

let idColumn = "id";

function encode(collection) {
  let header = [idColumn];
  collection.records.forEach(record => {
    record.fields.forEach(field => {
      if (!header.includes(field.name)) {
        header.push(field.name);
        return;
      }
    });
  });
  let rows = collection.records.map(record => header.map(name => {
    if (name === idColumn) {
      return record.id;
    } else {
      return Stdlib_Option.getOr(Stdlib_Option.map(record.fields.find(field => field.name === name), field => field.value), "");
    }
  }));
  return [header].concat(rows);
}

function decode(grid, makeId) {
  let header = grid.at(0);
  if (header === undefined) {
    return [];
  }
  let used = [];
  return Stdlib_Array.filterMap(grid.slice(1), cells => {
    let fields = [];
    let id = {
      contents: ""
    };
    header.forEach((name, index) => {
      let cell = Stdlib_Option.getOr(cells.at(index), "").trim();
      if (name === idColumn) {
        id.contents = cell;
        return;
      } else if (name.trim() !== "" && cell !== "") {
        fields.push({
          name: name.trim(),
          value: cell
        });
        return;
      } else {
        return;
      }
    });
    if (fields.length === 0 && id.contents === "") {
      return;
    }
    let final = id.contents === "" || used.includes(id.contents) ? makeId(used) : id.contents;
    used.push(final);
    return {
      id: final,
      fields: fields
    };
  });
}

export {
  encode,
  decode,
}
/* No side effect */
