// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Buntest from "bun:test";
import * as SpaceLink from "./SpaceLink.res.mjs";

Buntest.describe("SpaceLink", () => {
  Buntest.test("builds and reads an invitation", () => {
    let link = SpaceLink.of_("https://apps.example", "a1b2c3d4e5f6g7h", "KEY");
    Buntest.expect(link).toBe("https://apps.example/j/a1b2c3d4e5f6g7h#kKEY");
    let fragment = link.slice(link.indexOf("#"));
    Buntest.expect(SpaceLink.keyOf(fragment)).toEqual("KEY");
  });
  Buntest.test("accepts a fragment with or without its hash", () => {
    Buntest.expect(SpaceLink.keyOf("#kXYZ")).toEqual("XYZ");
    Buntest.expect(SpaceLink.keyOf("kXYZ")).toEqual("XYZ");
  });
  Buntest.test("refuses a fragment that is not an invitation", () => {
    Buntest.expect(SpaceLink.keyOf("")).toEqual(undefined);
    Buntest.expect(SpaceLink.keyOf("#")).toEqual(undefined);
    Buntest.expect(SpaceLink.keyOf("#k")).toEqual(undefined);
    Buntest.expect(SpaceLink.keyOf("#1payload")).toEqual(undefined);
  });
  Buntest.test("recognises what can be an invite id", () => {
    Buntest.expect(SpaceLink.isInviteId("a1b2c3d4e5f6g7h")).toBe(true);
    Buntest.expect(SpaceLink.isInviteId("short")).toBe(false);
    Buntest.expect(SpaceLink.isInviteId("has/slash-in-it")).toBe(false);
    Buntest.expect(SpaceLink.isInviteId("")).toBe(false);
  });
});

/*  Not a pure module */
