// Generated by ReScript, PLEASE EDIT WITH CARE


function toggle(theme) {
  if (theme === "Light") {
    return "Dark";
  } else {
    return "Light";
  }
}

function toSpectrumColor(theme) {
  if (theme === "Light") {
    return "light";
  } else {
    return "dark";
  }
}

function isDark(theme) {
  return theme === "Dark";
}

function parse(value) {
  switch (value) {
    case "dark" :
      return "Dark";
    case "light" :
      return "Light";
    default:
      return;
  }
}

function fromPrefersDark(prefersDark) {
  if (prefersDark) {
    return "Dark";
  } else {
    return "Light";
  }
}

let toTag = toSpectrumColor;

export {
  toggle,
  toSpectrumColor,
  isDark,
  toTag,
  parse,
  fromPrefersDark,
}
/* No side effect */
