// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Numeric from "./Numeric.res.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

function seconds(given) {
  let text = given.trim().toLowerCase();
  let size = text.length;
  if (size === 0) {
    return;
  }
  let unit = text.slice(size - 1 | 0, size);
  let match;
  switch (unit) {
    case "d" :
      match = [
        text.slice(0, size - 1 | 0),
        86400
      ];
      break;
    case "h" :
      match = [
        text.slice(0, size - 1 | 0),
        3600
      ];
      break;
    case "m" :
      match = [
        text.slice(0, size - 1 | 0),
        60
      ];
      break;
    case "s" :
      match = [
        text.slice(0, size - 1 | 0),
        1
      ];
      break;
    default:
      match = [
        text,
        1
      ];
  }
  let value = Numeric.parse(match[0].trim());
  if (value === undefined) {
    return;
  }
  if (value <= 0.0) {
    return;
  }
  let asked = value * match[1];
  if (asked > 31536000.0) {
    return;
  } else {
    return Math.max(60, asked | 0);
  }
}

function minuteOfDay(given) {
  let text = given.trim();
  let match = text.split(":");
  if (match.length !== 2) {
    return;
  }
  let hours = match[0];
  let minutes = match[1];
  let whole = value => {
    if (value.length === 2 || value.length === 1) {
      return Stdlib_Option.flatMap(Numeric.parse(value), number => {
        if (number >= 0.0 && Math.trunc(number) === number) {
          return number | 0;
        }
      });
    }
  };
  let match$1 = whole(hours);
  let match$2 = whole(minutes);
  if (match$1 !== undefined && match$2 !== undefined && match$1 < 24 && match$2 < 60) {
    return (match$1 * 60 | 0) + match$2 | 0;
  }
}

function events(given) {
  return given.split(",").map(prim => prim.trim()).filter(entry => entry !== "");
}

function prefixed(given, prefix) {
  return events(given).filter(entry => entry.startsWith(prefix)).map(entry => entry.slice(prefix.length, entry.length).trim()).filter(entry => entry !== "");
}

function saves(given) {
  return prefixed(given, "save:");
}

function changes(given) {
  return prefixed(given, "change:").map(key => {
    if (key.startsWith("#")) {
      return key.slice(1, key.length);
    } else {
      return key;
    }
  });
}

function opens(given) {
  return events(given).some(entry => entry === "open");
}

function dueEvery(last, now, seconds) {
  if (last <= 0.0 || now < last) {
    return true;
  } else {
    return now - last >= seconds * 1000.0;
  }
}

function remainingEvery(last, now, seconds) {
  let elapsed = (now - last) / 1000.0;
  let left = seconds - elapsed;
  if (last <= 0.0 || now < last || left <= 0.0) {
    return 0;
  } else {
    return Math.ceil(left) | 0;
  }
}

function dueAt(lastDay, today, nowMinutes, atMinutes, catchup) {
  if (lastDay === today || nowMinutes < atMinutes) {
    return false;
  } else if (catchup) {
    return true;
  } else {
    return (nowMinutes - atMinutes | 0) <= 60;
  }
}

function remainingAt(ranToday, nowMinutes, atMinutes) {
  if (!ranToday && nowMinutes < atMinutes) {
    return atMinutes - nowMinutes | 0;
  } else {
    return (1440 - nowMinutes | 0) + atMinutes | 0;
  }
}

let floor = 60;

export {
  floor,
  seconds,
  minuteOfDay,
  events,
  saves,
  changes,
  opens,
  dueEvery,
  remainingEvery,
  dueAt,
  remainingAt,
}
/* Numeric Not a pure module */
