// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Buntest from "bun:test";
import * as WorkflowTrigger from "./WorkflowTrigger.res.mjs";

Buntest.describe("WorkflowTrigger.seconds", () => {
  Buntest.test("the units an author writes", () => {
    Buntest.expect(WorkflowTrigger.seconds("15m")).toEqual(900);
    Buntest.expect(WorkflowTrigger.seconds("2h")).toEqual(7200);
    Buntest.expect(WorkflowTrigger.seconds("1d")).toEqual(86400);
    Buntest.expect(WorkflowTrigger.seconds("90s")).toEqual(90);
  });
  Buntest.test("bare digits are seconds", () => {
    Buntest.expect(WorkflowTrigger.seconds("300")).toEqual(300);
  });
  Buntest.test("anything under a minute is raised to one", () => {
    Buntest.expect(WorkflowTrigger.seconds("10s")).toEqual(60);
    Buntest.expect(WorkflowTrigger.seconds("1")).toEqual(60);
  });
  Buntest.test("what is not a schedule is refused rather than guessed at", () => {
    Buntest.expect(WorkflowTrigger.seconds("")).toEqual(undefined);
    Buntest.expect(WorkflowTrigger.seconds("presto")).toEqual(undefined);
    Buntest.expect(WorkflowTrigger.seconds("0")).toEqual(undefined);
    Buntest.expect(WorkflowTrigger.seconds("-5m")).toEqual(undefined);
    Buntest.expect(WorkflowTrigger.seconds("100y")).toEqual(undefined);
  });
  Buntest.test("spacing and case do not change the answer", () => {
    Buntest.expect(WorkflowTrigger.seconds("  15M ")).toEqual(900);
  });
});

Buntest.describe("WorkflowTrigger.minuteOfDay", () => {
  Buntest.test("a written time as minutes since local midnight", () => {
    Buntest.expect(WorkflowTrigger.minuteOfDay("18:00")).toEqual(1080);
    Buntest.expect(WorkflowTrigger.minuteOfDay("00:00")).toEqual(0);
    Buntest.expect(WorkflowTrigger.minuteOfDay("8:05")).toEqual(485);
  });
  Buntest.test("what is nearly a time is not one", () => {
    Buntest.expect(WorkflowTrigger.minuteOfDay("18")).toEqual(undefined);
    Buntest.expect(WorkflowTrigger.minuteOfDay("6pm")).toEqual(undefined);
    Buntest.expect(WorkflowTrigger.minuteOfDay("18:00:00")).toEqual(undefined);
    Buntest.expect(WorkflowTrigger.minuteOfDay("24:00")).toEqual(undefined);
    Buntest.expect(WorkflowTrigger.minuteOfDay("18:60")).toEqual(undefined);
    Buntest.expect(WorkflowTrigger.minuteOfDay("")).toEqual(undefined);
  });
});

Buntest.describe("WorkflowTrigger events", () => {
  Buntest.test("the collections a save starts it from", () => {
    Buntest.expect(WorkflowTrigger.saves("save:spese, save:fatture").join(",")).toBe("spese,fatture");
  });
  Buntest.test("a key is bare whether or not it was written with its hash", () => {
    Buntest.expect(WorkflowTrigger.changes("change:#regione, change:anno").join(",")).toBe("regione,anno");
  });
  Buntest.test("open is its own event", () => {
    Buntest.expect(WorkflowTrigger.opens("open")).toBe(true);
    Buntest.expect(WorkflowTrigger.opens("save:spese")).toBe(false);
  });
  Buntest.test("events of one kind do not answer for another", () => {
    Buntest.expect(WorkflowTrigger.saves("change:#regione").length).toBe(0);
  });
});

Buntest.describe("WorkflowTrigger.dueEvery", () => {
  Buntest.test("never run is due", () => {
    Buntest.expect(WorkflowTrigger.dueEvery(0.0, 1000.0, 900)).toBe(true);
  });
  Buntest.test("due once the interval has passed", () => {
    Buntest.expect(WorkflowTrigger.dueEvery(1000000.0, 1000000.0 + 14.0 * 60000.0, 900)).toBe(false);
    Buntest.expect(WorkflowTrigger.dueEvery(1000000.0, 1000000.0 + 15.0 * 60000.0, 900)).toBe(true);
  });
  Buntest.test("a clock that moved backwards is due rather than stuck", () => {
    Buntest.expect(WorkflowTrigger.dueEvery(1000000.0, 500000.0, 900)).toBe(true);
  });
});

Buntest.describe("WorkflowTrigger.remainingEvery", () => {
  Buntest.test("what is left of the interval", () => {
    Buntest.expect(WorkflowTrigger.remainingEvery(1000000.0, 1000000.0 + 5.0 * 60000.0, 900)).toBe(600);
  });
  Buntest.test("nothing left when it is due", () => {
    Buntest.expect(WorkflowTrigger.remainingEvery(0.0, 1000.0, 900)).toBe(0);
  });
});

Buntest.describe("WorkflowTrigger.dueAt", () => {
  let today = "2026-08-17";
  Buntest.test("due at its time on a day it has not run", () => {
    Buntest.expect(WorkflowTrigger.dueAt("2026-08-16", today, 1080, 1080, false)).toBe(true);
  });
  Buntest.test("not before its time", () => {
    Buntest.expect(WorkflowTrigger.dueAt("2026-08-16", today, 1079, 1080, false)).toBe(false);
  });
  Buntest.test("not twice in one day", () => {
    Buntest.expect(WorkflowTrigger.dueAt(today, today, 1200, 1080, false)).toBe(false);
  });
  Buntest.test("without catchup the window closes after an hour", () => {
    let late = catchup => WorkflowTrigger.dueAt("2026-08-16", today, 1380, 1080, catchup);
    Buntest.expect(late(false)).toBe(false);
    Buntest.expect(late(true)).toBe(true);
  });
});

Buntest.describe("WorkflowTrigger.remainingAt", () => {
  Buntest.test("today's, when it has not passed", () => {
    Buntest.expect(WorkflowTrigger.remainingAt(false, 1000, 1080)).toBe(80);
  });
  Buntest.test("tomorrow's, once it has run", () => {
    Buntest.expect(WorkflowTrigger.remainingAt(true, 1100, 1080)).toBe(1420);
  });
  Buntest.test("tomorrow's, once the time has passed", () => {
    Buntest.expect(WorkflowTrigger.remainingAt(false, 1200, 1080)).toBe(1320);
  });
});

let minute = 60000.0;

export {
  minute,
}
/*  Not a pure module */
