// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Session from "./shell/Session.res.mjs";
import * as Spectrum from "./spectrum/Spectrum.res.mjs";
import * as Clipboard from "./shell/Clipboard.res.mjs";
import * as KeyBundle from "./core/KeyBundle.res.mjs";
import * as NativeDialog from "./shell/NativeDialog.res.mjs";
import * as RecoveryCode from "./core/RecoveryCode.res.mjs";
import * as Translations from "./core/Translations.res.mjs";
import * as AccountCrypto from "./shell/AccountCrypto.res.mjs";
import * as AccountServer from "./shell/AccountServer.res.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as JsxRuntime from "react/jsx-runtime";

let usernamePattern = new RegExp("^[a-z0-9][a-z0-9-]{2,31}$");

function AccountDialog(props) {
  let onSignOut = props.onSignOut;
  let onSignedIn = props.onSignedIn;
  let onClose = props.onClose;
  let session = props.session;
  let locale = props.locale;
  let open_ = props.open_;
  let dialog = React.useRef(null);
  let match = React.useState(() => "Credentials");
  let setView = match[1];
  let view = match[0];
  let match$1 = React.useState(() => "");
  let setUsername = match$1[1];
  let username = match$1[0];
  let match$2 = React.useState(() => "");
  let setPassword = match$2[1];
  let password = match$2[0];
  let match$3 = React.useState(() => {});
  let setError = match$3[1];
  let error = match$3[0];
  let match$4 = React.useState(() => false);
  let setBusy = match$4[1];
  let busy = match$4[0];
  let match$5 = React.useState(() => false);
  let setCodeCopied = match$5[1];
  React.useEffect(() => {
    let element = dialog.current;
    if (!(element == null)) {
      return NativeDialog.follow(element, open_, () => onClose());
    }
  }, [open_]);
  React.useEffect(() => {
    if (!open_) {
      setView(param => "Credentials");
      setPassword(param => "");
      setError(param => {});
      setBusy(param => false);
      setCodeCopied(param => false);
    }
  }, [open_]);
  let finishSignIn = (answer, priv, pub) => ({
    token: answer.token,
    userId: answer.userId,
    username: answer.username,
    pub: pub,
    priv: priv
  });
  let submitSignIn = () => {
    setBusy(param => true);
    setError(param => {});
    let run = async () => {
      let answer = await AccountServer.signIn(username, password);
      if (answer !== undefined) {
        let bundle = KeyBundle.decode(answer.keyBundle);
        if (bundle !== undefined) {
          let priv = await AccountCrypto.unwrapWithSecret(password, bundle.salt, bundle.iterations, bundle.vault);
          if (priv !== undefined) {
            let session = finishSignIn(answer, priv, bundle.pub);
            await Session.save(session);
            onSignedIn(session);
          } else {
            setError(param => "AccountFailed");
          }
        } else {
          setError(param => "AccountFailed");
        }
      } else {
        setError(param => "AccountFailed");
      }
      return setBusy(param => false);
    };
    run();
  };
  let submitRegister = () => {
    if (!usernamePattern.test(username)) {
      return setError(param => "UsernameHint");
    }
    if (password.length < 8) {
      return setError(param => "PasswordHint");
    }
    setBusy(param => true);
    setError(param => {});
    let run = async () => {
      let identity = await AccountCrypto.generateIdentity();
      let salt = AccountCrypto.newSalt();
      let vault = await AccountCrypto.wrapWithSecret(password, salt, AccountCrypto.iterations, identity.priv);
      let code = RecoveryCode.format(AccountCrypto.randomBytes(RecoveryCode.byteLength));
      if (code !== undefined) {
        let recoveryVault = await AccountCrypto.wrapWithSecret(code, AccountCrypto.recoverySalt, AccountCrypto.iterations, identity.priv);
        let bundle = KeyBundle.encode({
          pub: identity.pub,
          salt: salt,
          iterations: AccountCrypto.iterations,
          vault: vault,
          recoveryVault: recoveryVault
        });
        let outcome = await AccountServer.register(username, password, bundle);
        if (outcome.taken) {
          setError(param => "UsernameTaken");
        } else if (outcome.ok) {
          let answer = await AccountServer.signIn(username, password);
          if (answer !== undefined) {
            setView(param => ({
              TAG: "Recovery",
              _0: code,
              _1: finishSignIn(answer, identity.priv, identity.pub)
            }));
          } else {
            setError(param => "AccountFailed");
          }
        } else {
          setError(param => "AccountFailed");
        }
      } else {
        setError(param => "AccountFailed");
      }
      return setBusy(param => false);
    };
    run();
  };
  let tmp;
  if (typeof view !== "object") {
    tmp = session !== undefined ? JsxRuntime.jsxs(JsxRuntime.Fragment, {
        children: [
          JsxRuntime.jsxs("p", {
            children: [
              Translations.translate(locale, "SignedInAs") + " ",
              JsxRuntime.jsx("strong", {
                children: session.username
              })
            ],
            className: "rn-dialog-message"
          }),
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx(Spectrum.Button.make, {
                variant: "secondary",
                onClick: param => onSignOut(),
                children: Translations.translate(locale, "SignOutAction")
              }),
              JsxRuntime.jsx(Spectrum.Button.make, {
                variant: "accent",
                onClick: param => onClose(),
                children: Translations.translate(locale, "CancelAction")
              })
            ],
            className: "rn-dialog-actions"
          })
        ]
      }) : JsxRuntime.jsxs(JsxRuntime.Fragment, {
        children: [
          JsxRuntime.jsx("p", {
            children: Translations.translate(locale, "AccountIntro"),
            className: "rn-dialog-message rn-muted"
          }),
          JsxRuntime.jsxs("label", {
            children: [
              Translations.translate(locale, "UsernameLabel"),
              JsxRuntime.jsx("input", {
                className: "rn-account-field",
                autoComplete: "username",
                disabled: busy,
                type: "text",
                value: username,
                onInput: event => setUsername(param => event.target.value.toLowerCase())
              })
            ],
            className: "rn-account-label"
          }),
          JsxRuntime.jsx("p", {
            children: Translations.translate(locale, "UsernameHint"),
            className: "rn-share-note rn-muted"
          }),
          JsxRuntime.jsxs("label", {
            children: [
              Translations.translate(locale, "PasswordLabel"),
              JsxRuntime.jsx("input", {
                className: "rn-account-field",
                autoComplete: "current-password",
                disabled: busy,
                type: "password",
                value: password,
                onKeyDown: event => {
                  if (event.key === "Enter") {
                    return submitSignIn();
                  }
                },
                onInput: event => setPassword(param => event.target.value)
              })
            ],
            className: "rn-account-label"
          }),
          JsxRuntime.jsx("p", {
            children: Translations.translate(locale, "PasswordHint"),
            className: "rn-share-note rn-muted"
          }),
          error !== undefined ? JsxRuntime.jsx("p", {
              children: Translations.translate(locale, error),
              className: "rn-error rn-dialog-message"
            }) : null,
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx(Spectrum.Button.make, {
                variant: "secondary",
                disabled: busy,
                onClick: param => onClose(),
                children: Translations.translate(locale, "CancelAction")
              }),
              JsxRuntime.jsx(Spectrum.Button.make, {
                variant: "secondary",
                disabled: busy,
                onClick: param => submitRegister(),
                children: Translations.translate(locale, "CreateAccountAction")
              }),
              JsxRuntime.jsx(Spectrum.Button.make, {
                variant: "accent",
                disabled: busy,
                onClick: param => submitSignIn(),
                children: Translations.translate(locale, "SignInAction")
              })
            ],
            className: "rn-dialog-actions"
          })
        ]
      });
  } else {
    let pending = view._1;
    let code = view._0;
    tmp = JsxRuntime.jsxs(JsxRuntime.Fragment, {
      children: [
        JsxRuntime.jsx("h3", {
          children: Translations.translate(locale, "RecoveryCodeTitle"),
          className: "rn-account-subtitle"
        }),
        JsxRuntime.jsx("p", {
          children: Translations.translate(locale, "RecoveryCodeInfo"),
          className: "rn-dialog-message"
        }),
        JsxRuntime.jsxs("div", {
          children: [
            JsxRuntime.jsx("output", {
              children: code,
              className: "rn-recovery-code"
            }),
            JsxRuntime.jsx(Spectrum.Button.make, {
              variant: "secondary",
              onClick: param => {
                Clipboard.copy(code).then(done => setCodeCopied(param => done));
              },
              children: match$5[0] ? Translations.translate(locale, "LinkCopied") : Translations.translate(locale, "CopyAction")
            })
          ],
          className: "rn-share-row"
        }),
        JsxRuntime.jsx("div", {
          children: JsxRuntime.jsx(Spectrum.Button.make, {
            variant: "accent",
            onClick: param => {
              let run = async () => {
                await Session.save(pending);
                return onSignedIn(pending);
              };
              run();
            },
            children: Translations.translate(locale, "RecoveryCodeDone")
          }),
          className: "rn-dialog-actions"
        })
      ]
    });
  }
  return JsxRuntime.jsxs("dialog", {
    children: [
      JsxRuntime.jsx("h2", {
        children: Translations.translate(locale, "AccountLabel"),
        className: "rn-dialog-title",
        id: "rn-account-title"
      }),
      tmp
    ],
    ref: Primitive_option.some(dialog),
    "aria-labelledby": "rn-account-title",
    className: "rn-dialog rn-surface"
  });
}

let make = AccountDialog;

export {
  make,
}
/* usernamePattern Not a pure module */
