// Generated by ReScript, PLEASE EDIT WITH CARE

import * as AppId from "./core/AppId.res.mjs";
import * as Clock from "./shell/Clock.res.mjs";
import * as Icons from "./Icons.res.mjs";
import * as Route from "./core/Route.res.mjs";
import * as Theme from "./core/Theme.res.mjs";
import * as React from "react";
import * as Digest from "./core/Digest.res.mjs";
import * as Editor from "./Editor.res.mjs";
import * as Footer from "./Footer.res.mjs";
import * as Locale from "./core/Locale.res.mjs";
import * as Navbar from "./Navbar.res.mjs";
import * as Render from "./Render.res.mjs";
import * as Router from "./shell/Router.res.mjs";
import * as AiPanel from "./AiPanel.res.mjs";
import * as AppFile from "./core/AppFile.res.mjs";
import * as Gallery from "./Gallery.res.mjs";
import * as Palette from "./core/Palette.res.mjs";
import * as Session from "./shell/Session.res.mjs";
import * as Spectrum from "./spectrum/Spectrum.res.mjs";
import * as Viewport from "./shell/Viewport.res.mjs";
import * as ChatPanel from "./ChatPanel.res.mjs";
import * as Clipboard from "./shell/Clipboard.res.mjs";
import * as DataPanel from "./DataPanel.res.mjs";
import * as ShareLink from "./core/ShareLink.res.mjs";
import * as SpaceLink from "./core/SpaceLink.res.mjs";
import * as SpaceSync from "./shell/SpaceSync.res.mjs";
import * as EditorMode from "./core/EditorMode.res.mjs";
import * as SpaceStore from "./shell/SpaceStore.res.mjs";
import * as SyncDialog from "./SyncDialog.res.mjs";
import * as AppDocument from "./core/AppDocument.res.mjs";
import * as BlockEditor from "./BlockEditor.res.mjs";
import * as Frontmatter from "./core/Frontmatter.res.mjs";
import * as PaneToolbar from "./PaneToolbar.res.mjs";
import * as ShareCrypto from "./shell/ShareCrypto.res.mjs";
import * as ShareDialog from "./ShareDialog.res.mjs";
import * as ShareServer from "./shell/ShareServer.res.mjs";
import * as WelcomeSeed from "./shell/WelcomeSeed.res.mjs";
import * as DerivedPaths from "./shell/DerivedPaths.res.mjs";
import * as DocumentInfo from "./DocumentInfo.res.mjs";
import * as FileTransfer from "./shell/FileTransfer.res.mjs";
import * as SharePayload from "./shell/SharePayload.res.mjs";
import * as ThemeStorage from "./shell/ThemeStorage.res.mjs";
import * as Translations from "./core/Translations.res.mjs";
import * as AccountDialog from "./AccountDialog.res.mjs";
import * as AccountServer from "./shell/AccountServer.res.mjs";
import * as CatalogServer from "./shell/CatalogServer.res.mjs";
import * as ConfirmDialog from "./ConfirmDialog.res.mjs";
import * as DocumentStore from "./shell/DocumentStore.res.mjs";
import * as LocaleStorage from "./shell/LocaleStorage.res.mjs";
import * as ReactiveStore from "./shell/ReactiveStore.res.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as PaletteStorage from "./shell/PaletteStorage.res.mjs";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  let match = React.useState(ThemeStorage.systemPreference);
  let setTheme = match[1];
  let theme = match[0];
  let match$1 = React.useState(() => Palette.fallback);
  let setPalette = match$1[1];
  let palette = match$1[0];
  let match$2 = React.useState(LocaleStorage.browserPreference);
  let setLocale = match$2[1];
  let locale = match$2[0];
  let match$3 = React.useState(() => EditorMode.initial);
  let setMode = match$3[1];
  let mode = match$3[0];
  let match$4 = React.useState(() => false);
  let setInfoOpen = match$4[1];
  let infoOpen = match$4[0];
  let match$5 = React.useState(() => false);
  let setChatOpen = match$5[1];
  let chatOpen = match$5[0];
  let match$6 = React.useState(Router.current);
  let setRoute = match$6[1];
  let route = match$6[0];
  let match$7 = React.useState(() => []);
  let setApps = match$7[1];
  let match$8 = React.useState(() => "");
  let setSource = match$8[1];
  let source = match$8[0];
  let match$9 = React.useState(() => "");
  let setRendered = match$9[1];
  let rendered = match$9[0];
  let match$10 = React.useState(() => {});
  let setCopiedId = match$10[1];
  let copiedId = match$10[0];
  let match$11 = React.useState(() => {});
  let setNotice = match$11[1];
  let match$12 = React.useState(Viewport.canEdit);
  let setCanEdit = match$12[1];
  let canEdit = match$12[0];
  let match$13 = React.useState(() => false);
  let setSeeded = match$13[1];
  let seeded = match$13[0];
  let match$14 = React.useState(() => {});
  let setSession = match$14[1];
  let session = match$14[0];
  let match$15 = React.useState(() => false);
  let setAccountOpen = match$15[1];
  let match$16 = React.useState(() => false);
  let setAssistantOpen = match$16[1];
  let assistantOpen = match$16[0];
  let match$17 = React.useState(() => {});
  let setAssistantQuestion = match$17[1];
  let match$18 = React.useState(() => 0);
  let setDocEpoch = match$18[1];
  React.useEffect(() => {
    let hydrate = async () => {
      let stored = await Session.load();
      if (stored === undefined) {
        return;
      }
      setSession(param => stored);
      let answer = await AccountServer.refresh(stored.token);
      if (answer.denied) {
        await Session.clear();
        return setSession(param => {});
      }
      let traded = answer.fresh;
      if (traded === undefined) {
        return;
      }
      let updated_token = traded.token;
      let updated_userId = stored.userId;
      let updated_username = stored.username;
      let updated_pub = stored.pub;
      let updated_priv = stored.priv;
      let updated = {
        token: updated_token,
        userId: updated_userId,
        username: updated_username,
        pub: updated_pub,
        priv: updated_priv
      };
      await Session.save(updated);
      return setSession(param => updated);
    };
    hydrate();
  }, []);
  let signOut = () => {
    Session.clear();
    setSession(param => {});
    setAccountOpen(param => false);
  };
  let match$19 = React.useState(() => false);
  let setSyncOpen = match$19[1];
  let match$20 = React.useState(() => 0);
  let setSyncEpoch = match$20[1];
  let match$21 = React.useState(() => {});
  let setJoinPending = match$21[1];
  let joinPending = match$21[0];
  let handledJoin = React.useRef(undefined);
  let routeRef = React.useRef(route);
  routeRef.current = route;
  let openedId = React.useRef(undefined);
  let refreshApps = () => {
    DocumentStore.list().then(found => setApps(param => found));
  };
  React.useEffect(() => Router.subscribe(next => setRoute(param => next)), []);
  React.useEffect(() => Viewport.subscribe(wide => setCanEdit(param => wide)), []);
  let handledShare = React.useRef(undefined);
  let receive = (arriveOpt, text) => {
    let arrive = arriveOpt !== undefined ? arriveOpt : Router.navigate;
    return DocumentStore.ids().then(taken => {
      let id = AppFile.idFor(text, taken, Translations.translate(locale, "Untitled"));
      let source = AppDocument.withId(text, id);
      return DocumentStore.save(id, source).then(() => {
        setNotice(param => {
          if (AppFile.isCopy(text, id)) {
            return Translations.translate(locale, "ImportedAsCopy");
          }
        });
        refreshApps();
        arrive({
          TAG: "View",
          _0: id
        });
      });
    });
  };
  React.useEffect(() => {
    if (!canEdit && typeof route === "object" && route.TAG === "Edit") {
      Router.navigate({
        TAG: "View",
        _0: route._0
      });
    }
  }, [
    canEdit,
    Route.toPath(route)
  ]);
  let tmp;
  tmp = typeof route !== "object" || route.TAG !== "Shared" ? "" : Router.fragment();
  React.useEffect(() => {
    if (seeded) {
      let exit = 0;
      if (typeof route !== "object") {
        openedId.current = undefined;
        refreshApps();
      } else {
        switch (route.TAG) {
          case "View" :
          case "Edit" :
            exit = 1;
            break;
          case "Shared" :
            let short = route._0;
            let mark = Route.toPath(route) + Router.fragment();
            let file = decoded => {
              if (decoded !== undefined && Stdlib_Option.isSome(Frontmatter.parse(decoded).meta)) {
                return receive(Router.replace, decoded);
              }
              setNotice(param => Translations.translate(locale, "BrokenShareLink"));
              Router.replace("Gallery");
              return Promise.resolve();
            };
            if (!Primitive_object.equal(handledShare.current, mark)) {
              handledShare.current = mark;
              if (short !== undefined) {
                let key = ShareLink.keyOf(Router.fragment());
                if (key !== undefined) {
                  ShareServer.fetchPayload(short).then(stored => {
                    if (stored !== undefined) {
                      return ShareCrypto.decrypt(key, stored).then(opened => {
                        if (opened !== undefined) {
                          return SharePayload.decode(opened).then(file);
                        } else {
                          return file(undefined);
                        }
                      });
                    } else {
                      setNotice(param => Translations.translate(locale, "ShareExpired"));
                      Router.replace("Gallery");
                      return Promise.resolve();
                    }
                  });
                } else {
                  setNotice(param => Translations.translate(locale, "BrokenShareLink"));
                  Router.replace("Gallery");
                }
              } else {
                let carried = ShareLink.payloadOf(Router.fragment());
                if (carried !== undefined) {
                  SharePayload.decode(carried).then(file);
                } else {
                  Router.replace("Gallery");
                }
              }
            }
            break;
          case "Join" :
            break;
          case "Catalog" :
            let mark$1 = Route.toPath(route);
            if (Primitive_object.equal(handledShare.current, mark$1)) {
              
            } else {
              handledShare.current = mark$1;
              CatalogServer.fetchDocument(route._0).then(answer => {
                let text = answer.text;
                if (text !== undefined && Stdlib_Option.isSome(Frontmatter.parse(text).meta)) {
                  return receive(Router.replace, text);
                }
                setNotice(param => Translations.translate(locale, answer.missing ? "CatalogMissing" : "CatalogUnreachable"));
                Router.replace("Gallery");
                return Promise.resolve();
              });
            }
            break;
        }
      }
      if (exit === 1) {
        let id = route._0;
        if (Primitive_object.notequal(openedId.current, id)) {
          DocumentStore.load(id).then(stored => {
            if (stored !== undefined) {
              ReactiveStore.reset();
              openedId.current = id;
              setSource(param => stored);
              return setRendered(param => stored);
            } else {
              return Router.navigate("Gallery");
            }
          });
        }
      }
    }
    setMode(current => EditorMode.showEditor(current, Route.isEditing(route)));
  }, [
    seeded,
    Route.toPath(route) + tmp
  ]);
  let tmp$1;
  tmp$1 = typeof route !== "object" || route.TAG !== "Join" ? "" : Router.fragment();
  React.useEffect(() => {
    if (typeof route === "object" && route.TAG === "Join" && seeded) {
      let inviteId = route._0;
      if (session !== undefined) {
        let mark = Route.toPath(route) + Router.fragment();
        if (Primitive_object.notequal(handledJoin.current, mark)) {
          handledJoin.current = mark;
          let key = SpaceLink.keyOf(Router.fragment());
          if (key !== undefined) {
            setJoinPending(param => [
              inviteId,
              key
            ]);
          } else {
            setNotice(param => Translations.translate(locale, "BrokenShareLink"));
            Router.replace("Gallery");
          }
        }
      } else {
        setAccountOpen(param => true);
      }
    }
  }, [
    seeded,
    Route.toPath(route) + tmp$1,
    Stdlib_Option.isSome(session)
  ]);
  let confirmJoin = () => {
    if (joinPending === undefined) {
      return;
    }
    if (session === undefined) {
      return;
    }
    let key = joinPending[1];
    let inviteId = joinPending[0];
    setJoinPending(param => {});
    DocumentStore.ids().then(taken => SpaceSync.join(inviteId, key, session, taken, Translations.translate(locale, "Untitled"))).then(result => {
      if (result !== undefined) {
        refreshApps();
        setSyncEpoch(count => count + 1 | 0);
        return Router.replace({
          TAG: "View",
          _0: result
        });
      } else {
        setNotice(param => Translations.translate(locale, "InviteInvalid"));
        return Router.replace("Gallery");
      }
    });
  };
  let cancelJoin = () => {
    setJoinPending(param => {});
    Router.replace("Gallery");
  };
  React.useEffect(() => {
    let match = Route.appId(route);
    if (match !== undefined && session !== undefined && seeded) {
      SpaceSync.start(match, session, text => {
        if (!Route.isEditing(routeRef.current)) {
          setSource(param => text);
          return setRendered(param => text);
        }
      });
      return () => SpaceSync.stop(match);
    }
  }, [
    Stdlib_Option.getOr(Route.appId(route), ""),
    Stdlib_Option.getOr(Stdlib_Option.map(session, signed => signed.token), ""),
    seeded,
    match$20[0]
  ]);
  React.useEffect(() => {
    let current = AppDocument.welcome(locale, Clock.timestamp().slice(0, 10));
    let write = () => DocumentStore.save(AppDocument.welcomeId, current).then(() => WelcomeSeed.record(Digest.of_(current)));
    Promise.all([
      DocumentStore.load(AppDocument.welcomeId),
      WelcomeSeed.read()
    ]).then(param => {
      let existing = param[0];
      if (existing !== undefined && !(existing !== current && Digest.matches(existing, param[1]))) {
        return Promise.resolve();
      } else {
        return write();
      }
    }).then(() => {
      refreshApps();
      setSeeded(param => true);
    });
  }, []);
  let parsedDocument = Frontmatter.parse(rendered);
  let declaredLanguage = Stdlib_Option.flatMap(parsedDocument.meta, meta => Frontmatter.get(meta, "lang"));
  let documentLocale = Stdlib_Option.flatMap(declaredLanguage, Locale.parse);
  let documentLocaleRef = React.useRef(documentLocale);
  documentLocaleRef.current = documentLocale;
  React.useEffect(() => {
    PaletteStorage.load().then(stored => {
      if (stored !== undefined) {
        return setPalette(param => stored);
      }
    });
    ThemeStorage.load().then(stored => {
      if (stored !== undefined) {
        return setTheme(param => stored);
      }
    });
    LocaleStorage.load().then(stored => {
      let match = documentLocaleRef.current;
      if (match !== undefined || stored === undefined) {
        return;
      } else {
        return setLocale(param => stored);
      }
    });
  }, []);
  React.useEffect(() => {
    let timeout = setTimeout(() => setRendered(param => source), 250);
    return () => {
      clearTimeout(timeout);
    };
  }, [source]);
  React.useEffect(() => {
    let match = Route.appId(route);
    if (match === undefined) {
      return;
    }
    if (source === "") {
      return;
    }
    let timeout = setTimeout(() => {
      let declared = AppDocument.declaredId(source);
      if (declared !== undefined && declared !== match) {
        openedId.current = declared;
        DocumentStore.rename(match, declared, source).then(() => SpaceStore.rename(match, declared)).then(() => DerivedPaths.rename(match, declared)).then(() => {
          Router.navigate(Route.isEditing(route) ? ({
              TAG: "Edit",
              _0: declared
            }) : ({
              TAG: "View",
              _0: declared
            }));
          refreshApps();
        });
        return;
      }
      DocumentStore.save(match, source).then(() => {
        refreshApps();
        SpaceSync.localChanged(match);
      });
    }, 700);
    return () => {
      clearTimeout(timeout);
    };
  }, [
    source,
    Route.toPath(route)
  ]);
  React.useEffect(() => {
    if (documentLocale !== undefined) {
      setLocale(current => {
        if (current === documentLocale) {
          return current;
        } else {
          return documentLocale;
        }
      });
    }
  }, [Stdlib_Option.getOr(declaredLanguage, "")]);
  let toggleTheme = () => setTheme(current => {
    let next = Theme.toggle(current);
    ThemeStorage.save(next);
    return next;
  });
  let selectPalette = next => {
    PaletteStorage.save(next);
    setPalette(param => next);
  };
  let selectLocale = next => {
    LocaleStorage.save(next);
    setLocale(param => next);
  };
  let createApp = () => {
    DocumentStore.ids().then(taken => {
      let title = Translations.translate(locale, "Untitled");
      let id = AppId.unique(title, taken);
      let document = AppDocument.blank(id, title, Clock.timestamp().slice(0, 10), locale);
      return DocumentStore.save(id, document).then(() => id);
    }).then(id => {
      refreshApps();
      Router.navigate({
        TAG: "Edit",
        _0: id
      });
    });
  };
  let deleteApp = id => {
    if (session !== undefined) {
      SpaceSync.leave(id, session);
    } else {
      SpaceStore.clear(id);
    }
    DocumentStore.remove(id).then(() => refreshApps());
  };
  let updateApp = id => {
    CatalogServer.fetchDocument(id).then(answer => {
      let text = answer.text;
      if (text !== undefined && Stdlib_Option.isSome(Frontmatter.parse(text).meta)) {
        return DocumentStore.save(id, AppDocument.withId(text, id)).then(() => {
          setNotice(param => Translations.translate(locale, "UpdateDone"));
          setDocEpoch(epoch => epoch + 1 | 0);
          refreshApps();
        });
      }
      setNotice(param => Translations.translate(locale, "UpdateFailed"));
      return Promise.resolve();
    });
  };
  let duplicateApp = id => {
    DocumentStore.duplicate(id).then(copy => {
      if (copy !== undefined) {
        refreshApps();
        return Router.navigate(canEdit ? ({
            TAG: "Edit",
            _0: copy
          }) : ({
            TAG: "View",
            _0: copy
          }));
      }
    });
  };
  let importApp = () => {
    FileTransfer.readDocument().then(chosen => {
      if (chosen !== undefined) {
        if (AppFile.isDocument(chosen[0])) {
          return receive(undefined, chosen[1]);
        } else {
          setNotice(param => Translations.translate(locale, "NotADocument"));
          return Promise.resolve();
        }
      } else {
        return Promise.resolve();
      }
    });
  };
  let match$22 = React.useState(() => {});
  let setSharing = match$22[1];
  let sharing = match$22[0];
  let copyLink = id => {
    Clipboard.copy(Clipboard.absolute({
      TAG: "View",
      _0: id
    })).then(copied => setCopiedId(param => {
      if (copied) {
        return id;
      }
    }));
  };
  let appId = Stdlib_Option.flatMap(parsedDocument.meta, meta => Frontmatter.get(meta, "appId"));
  let id = Route.appId(route);
  let openedCard = id !== undefined ? AppDocument.summary(id, rendered) : undefined;
  let chatEnabled = Stdlib_Option.getOr(Stdlib_Option.map(openedCard, card => card.chat), false);
  let rightPaneTitle = Route.isEditing(route) ? Translations.translate(locale, "PreviewPane") : (
      openedCard !== undefined && openedCard.title !== "" ? openedCard.title : Translations.translate(locale, "AppPane")
    );
  let rightPaneIcon = Route.isEditing(route) ? undefined : Stdlib_Option.map(openedCard, card => card.icon);
  let editingButton = (editing, icon) => {
    let tmp;
    tmp = editing === "Markdown" ? "MarkdownEditor" : "BlockEditor";
    return JsxRuntime.jsx(Spectrum.ActionButton.make, {
      label: Translations.translate(locale, tmp),
      selected: mode.editing === editing,
      onClick: param => setMode(current => EditorMode.useEditing(current, editing)),
      children: icon
    });
  };
  let tmp$2;
  let exit = 0;
  if (typeof route !== "object") {
    exit = 1;
  } else {
    switch (route.TAG) {
      case "View" :
      case "Edit" :
        exit = 2;
        break;
      default:
        exit = 1;
    }
  }
  switch (exit) {
    case 1 :
      tmp$2 = JsxRuntime.jsx("main", {
        children: JsxRuntime.jsx(Gallery.make, {
          apps: match$7[0],
          locale: locale,
          onCreate: createApp,
          onDelete: deleteApp,
          onDuplicate: duplicateApp,
          onUpdate: updateApp,
          onCopyLink: copyLink,
          copiedId: copiedId,
          canEdit: canEdit,
          notice: match$11[0],
          onAsk: question => {
            setAssistantQuestion(param => question);
            setAssistantOpen(param => true);
          }
        }),
        className: "min-h-0 flex-1 overflow-auto"
      });
      break;
    case 2 :
      tmp$2 = JsxRuntime.jsxs("main", {
        children: [
          mode.editorVisible ? JsxRuntime.jsxs("section", {
              children: [
                JsxRuntime.jsx(PaneToolbar.make, {
                  title: Translations.translate(locale, "EditorPane"),
                  children: JsxRuntime.jsxs(JsxRuntime.Fragment, {
                    children: [
                      editingButton("Markdown", Icons.markdown),
                      editingButton("Blocks", Icons.blocks)
                    ]
                  })
                }),
                JsxRuntime.jsx("div", {
                  children: EditorMode.showsMarkdownEditor(mode) ? JsxRuntime.jsx(Editor.make, {
                      initialValue: source,
                      onChange: text => setSource(param => text)
                    }, Stdlib_Option.getOr(Route.appId(route), "") + (
                      Primitive_object.equal(openedId.current, Route.appId(route)) ? "" : "-loading"
                    )) : BlockEditor.element(source, text => setSource(param => text), Theme.isDark(theme), locale),
                  className: "min-h-0 flex-1"
                }, "editor-" + match$18[0].toString())
              ],
              "aria-label": Translations.translate(locale, "EditorPane"),
              className: "rn-divider flex min-h-0 flex-col border-r"
            }) : null,
          JsxRuntime.jsxs("section", {
            children: [
              JsxRuntime.jsx(PaneToolbar.make, {
                title: rightPaneTitle,
                icon: rightPaneIcon,
                children: JsxRuntime.jsxs(JsxRuntime.Fragment, {
                  children: [
                    JsxRuntime.jsx(Spectrum.ActionButton.make, {
                      label: Translations.translate(locale, "DocumentInfo"),
                      selected: infoOpen,
                      onClick: param => setInfoOpen(shown => !shown),
                      children: Icons.info
                    }),
                    JsxRuntime.jsx(Spectrum.ActionButton.make, {
                      label: Translations.translate(locale, "DataPanel"),
                      selected: mode.dataVisible,
                      onClick: param => setMode(EditorMode.toggleData),
                      children: Icons.data
                    }),
                    chatEnabled ? JsxRuntime.jsx(Spectrum.ActionButton.make, {
                        label: Translations.translate(locale, "ChatPanel"),
                        selected: chatOpen,
                        onClick: param => setChatOpen(shown => !shown),
                        children: Icons.chat
                      }) : null,
                    Route.isEditing(route) ? JsxRuntime.jsx(Spectrum.ActionButton.make, {
                        label: EditorMode.previewIsPhone(mode) ? Translations.translate(locale, "FullWidth") : Translations.translate(locale, "PhoneWidth"),
                        selected: EditorMode.previewIsPhone(mode),
                        onClick: param => setMode(EditorMode.togglePreviewWidth),
                        children: EditorMode.previewIsPhone(mode) ? Icons.desktop : Icons.phone
                      }) : null
                  ]
                })
              }),
              infoOpen ? JsxRuntime.jsx(DocumentInfo.make, {
                  meta: parsedDocument.meta,
                  locale: locale
                }) : null,
              mode.dataVisible ? JsxRuntime.jsx(DataPanel.make, {
                  app: appId,
                  locale: locale,
                  clock: Clock.timestamp
                }) : null,
              chatEnabled && chatOpen ? JsxRuntime.jsx(ChatPanel.make, {
                  app: appId,
                  locale: locale,
                  author: Stdlib_Option.map(session, signed => signed.username),
                  clock: Clock.timestamp
                }) : null,
              JsxRuntime.jsx("div", {
                children: EditorMode.previewIsPhone(mode) ? JsxRuntime.jsx("div", {
                    children: JsxRuntime.jsx(Render.make, {
                      source: parsedDocument.body,
                      theme: theme,
                      locale: locale,
                      app: appId
                    }),
                    className: "rn-phone-frame"
                  }) : JsxRuntime.jsx(Render.make, {
                    source: parsedDocument.body,
                    theme: theme,
                    locale: locale,
                    app: appId
                  }),
                className: "rn-preview min-h-0 flex-1 overflow-auto"
              })
            ],
            "aria-label": rightPaneTitle,
            className: "flex min-h-0 flex-col"
          })
        ],
        className: "grid min-h-0 flex-1 " + (
          EditorMode.previewIsFullWidth(mode) ? "grid-cols-1" : "grid-cols-1 md:grid-cols-2"
        )
      });
      break;
  }
  let tmp$3;
  tmp$3 = sharing !== undefined && sharing[1] === "" ? sharing[2] === "" : false;
  return JsxRuntime.jsxs(Spectrum.Theme.make, {
    system: "spectrum-two",
    color: Theme.toSpectrumColor(theme),
    className: "rn-palette-" + Palette.toTag(palette) + " rn-page flex h-screen flex-col overflow-hidden",
    children: [
      JsxRuntime.jsx(Navbar.make, {
        locale: locale,
        route: route,
        canEdit: canEdit,
        copied: copiedId !== undefined && Primitive_object.equal(copiedId, Route.appId(route)),
        onToggleEditing: () => {
          let id = Route.appId(route);
          if (id !== undefined) {
            return Router.navigate(Route.isEditing(route) ? ({
                TAG: "View",
                _0: id
              }) : ({
                TAG: "Edit",
                _0: id
              }));
          }
        },
        onHome: () => Router.navigate("Gallery"),
        onCopyLink: () => {
          let id = Route.appId(route);
          if (id !== undefined) {
            return copyLink(id);
          }
        },
        onShare: () => {
          let id = Route.appId(route);
          if (id !== undefined) {
            DocumentStore.load(id).then(stored => {
              if (stored !== undefined) {
                return SharePayload.encode(stored).then(payload => {
                  let card = AppDocument.summary(id, stored);
                  let longLink = ShareLink.fits(payload) ? ShareLink.of_(Clipboard.origin, payload) : "";
                  return ShareCrypto.generateKey().then(key => ShareCrypto.encrypt(key, payload).then(sealed => {
                    if (ShareLink.fitsStored(sealed)) {
                      return ShareServer.create(sealed).then(made => {
                        if (made !== undefined) {
                          return ShareLink.shortOf(Clipboard.origin, made, key);
                        } else {
                          return "";
                        }
                      });
                    } else {
                      return Promise.resolve("");
                    }
                  })).then(shortLink => setSharing(param => [
                    card.title,
                    longLink,
                    shortLink
                  ]));
                });
              } else {
                return Promise.resolve();
              }
            });
            return;
          }
        },
        onSync: () => setSyncOpen(param => true),
        onExport: () => {
          let id = Route.appId(route);
          if (id !== undefined) {
            DocumentStore.load(id).then(stored => {
              if (stored !== undefined) {
                return FileTransfer.download(AppFile.name(id), stored);
              }
            });
            return;
          }
        },
        onImport: importApp,
        assistantOpen: assistantOpen,
        onAssistant: () => setAssistantOpen(shown => !shown)
      }),
      JsxRuntime.jsxs("div", {
        children: [
          tmp$2,
          assistantOpen ? JsxRuntime.jsx(AiPanel.make, {
              locale: locale,
              app: Route.appId(route),
              question: match$17[0],
              onQuestionTaken: () => setAssistantQuestion(param => {}),
              onCreated: param => refreshApps(),
              onOpen: id => Router.navigate(canEdit ? ({
                  TAG: "Edit",
                  _0: id
                }) : ({
                  TAG: "View",
                  _0: id
                })),
              onApply: (id, text) => {
                if (Primitive_object.equal(Route.appId(route), id)) {
                  setSource(param => text);
                  return setDocEpoch(count => count + 1 | 0);
                } else {
                  DocumentStore.save(id, text).then(() => refreshApps());
                  return;
                }
              },
              onClose: () => setAssistantOpen(param => false)
            }) : null
        ],
        className: "rn-panes flex min-h-0 flex-1 overflow-hidden"
      }),
      JsxRuntime.jsx(ShareDialog.make, {
        open_: Stdlib_Option.isSome(sharing),
        locale: locale,
        title: sharing !== undefined ? sharing[0] : "",
        link: sharing !== undefined ? sharing[1] : "",
        shortLink: sharing !== undefined ? sharing[2] : "",
        tooBig: tmp$3,
        onClose: () => setSharing(param => {})
      }),
      JsxRuntime.jsx(AccountDialog.make, {
        open_: match$15[0],
        locale: locale,
        session: session,
        onClose: () => setAccountOpen(param => false),
        onSignedIn: signed => {
          setSession(param => signed);
          setAccountOpen(param => false);
        },
        onSignOut: signOut
      }),
      JsxRuntime.jsx(SyncDialog.make, {
        open_: match$19[0],
        locale: locale,
        app: Route.appId(route),
        session: session,
        onClose: () => setSyncOpen(param => false),
        onOpenAccount: () => {
          setSyncOpen(param => false);
          setAccountOpen(param => true);
        },
        onChanged: () => setSyncEpoch(count => count + 1 | 0)
      }),
      JsxRuntime.jsx(ConfirmDialog.make, {
        open_: Stdlib_Option.isSome(joinPending),
        title: Translations.translate(locale, "SyncPanel"),
        message: Translations.translate(locale, "JoinQuestion"),
        confirmLabel: Translations.translate(locale, "JoinAction"),
        cancelLabel: Translations.translate(locale, "CancelAction"),
        onConfirm: confirmJoin,
        onCancel: cancelJoin
      }),
      JsxRuntime.jsx(Footer.make, {
        theme: theme,
        palette: palette,
        locale: locale,
        accountName: session !== undefined ? session.username : undefined,
        onAccount: () => setAccountOpen(param => true),
        onToggleTheme: toggleTheme,
        onSelectPalette: selectPalette,
        onSelectLocale: selectLocale
      })
    ]
  });
}

let make = App;

export {
  make,
}
/* Icons Not a pure module */
