// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as AppDocument from "./core/AppDocument.res.mjs";
import * as IconDrawings from "./shell/IconDrawings.res.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as JsxRuntime from "react/jsx-runtime";

function AppIcon(props) {
  let __className = props.className;
  let name = props.name;
  let __className_value = __className !== undefined ? __className : "rn-app-card-icon";
  let host = React.useRef(null);
  React.useEffect(() => {
    let element = host.current;
    if (!(element == null)) {
      IconDrawings.draw(element, name === "" ? AppDocument.defaultIcon : name);
    }
  }, [name]);
  return JsxRuntime.jsx("span", {
    ref: Primitive_option.some(host),
    "aria-hidden": true,
    className: __className_value
  });
}

let make = AppIcon;

export {
  make,
}
/* react Not a pure module */
