// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Brand(props) {
  let __className = props.className;
  let __className_value = __className !== undefined ? __className : "h-7 w-7";
  return JsxRuntime.jsxs("svg", {
    children: [
      JsxRuntime.jsx("rect", {
        height: "512",
        width: "512",
        fill: "#dcdce2",
        rx: "112"
      }),
      JsxRuntime.jsxs("g", {
        children: [
          JsxRuntime.jsx("ellipse", {
            cx: "256",
            cy: "256",
            opacity: "0.62",
            rx: "186",
            ry: "72",
            transform: "rotate(-45 256 256)"
          }),
          JsxRuntime.jsx("ellipse", {
            cx: "256",
            cy: "256",
            rx: "186",
            ry: "72",
            transform: "rotate(45 256 256)"
          })
        ],
        fill: "none",
        stroke: "var(--color-brand)",
        strokeWidth: "20"
      }),
      JsxRuntime.jsx("circle", {
        cx: "256",
        cy: "256",
        fill: "var(--color-brand)",
        r: "60"
      })
    ],
    "aria-hidden": true,
    className: __className_value,
    focusable: "false",
    viewBox: "0 0 512 512"
  });
}

let make = Brand;

export {
  make,
}
/* react/jsx-runtime Not a pure module */
