// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as CodeMirror from "./shell/CodeMirror.res.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as DirectiveRegistry from "./core/DirectiveRegistry.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as DirectiveCompletion from "./core/DirectiveCompletion.res.mjs";

function Editor(props) {
  let onChange = props.onChange;
  let initialValue = props.initialValue;
  let container = React.useRef(null);
  let latestOnChange = React.useRef(onChange);
  latestOnChange.current = onChange;
  React.useEffect(() => {
    let element = container.current;
    if (element == null) {
      return;
    }
    let view = CodeMirror.create(element, initialValue, text => latestOnChange.current(text), line => DirectiveCompletion.completions(DirectiveCompletion.analyse(line), DirectiveRegistry.all));
    return () => CodeMirror.destroy(view);
  }, []);
  return JsxRuntime.jsx("div", {
    ref: Primitive_option.some(container),
    className: "rn-editor h-full overflow-auto"
  });
}

let make = Editor;

export {
  make,
}
/* react Not a pure module */
