// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Icons from "./Icons.res.mjs";
import * as Theme from "./core/Theme.res.mjs";
import * as Locale from "./core/Locale.res.mjs";
import * as Palette from "./core/Palette.res.mjs";
import * as Spectrum from "./spectrum/Spectrum.res.mjs";
import * as BuildInfo from "./shell/BuildInfo.res.mjs";
import * as Translations from "./core/Translations.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function Footer(props) {
  let onSelectLocale = props.onSelectLocale;
  let onSelectPalette = props.onSelectPalette;
  let onToggleTheme = props.onToggleTheme;
  let onAccount = props.onAccount;
  let accountName = props.accountName;
  let locale = props.locale;
  let palette = props.palette;
  let tmp;
  tmp = locale === "It" ? "https://reactivenet.ai/note-legali/" : "https://reactivenet.ai/en/note-legali/";
  return JsxRuntime.jsxs("footer", {
    children: [
      JsxRuntime.jsxs("span", {
        children: [
          JsxRuntime.jsxs("span", {
            children: [
              "ReactiveNET",
              JsxRuntime.jsx("span", {
                children: "v" + BuildInfo.version,
                className: "rn-muted font-mono"
              })
            ],
            className: "rn-footer-brand flex items-center gap-2"
          }),
          JsxRuntime.jsx("a", {
            children: Translations.translate(locale, "LegalNotices"),
            className: "rn-muted underline",
            href: tmp,
            rel: "noopener noreferrer",
            target: "_blank"
          })
        ],
        className: "mr-auto flex items-center gap-2"
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx(Spectrum.Picker.make, {
            value: Locale.toTag(locale),
            label: Translations.translate(locale, "Language"),
            size: "s",
            onChange: event => {
              let next = Locale.parse(event.target.value);
              if (next !== undefined && next !== locale) {
                return onSelectLocale(next);
              }
            },
            children: Locale.all.map(option => JsxRuntime.jsx(Spectrum.MenuItem.make, {
              value: Locale.toTag(option),
              selected: option === locale,
              children: Locale.nativeName(option)
            }, Locale.toTag(option)))
          }),
          JsxRuntime.jsx(Spectrum.Picker.make, {
            value: Palette.toTag(palette),
            label: Translations.translate(locale, "PaletteLabel"),
            size: "s",
            onChange: event => {
              let next = Palette.parse(event.target.value);
              if (next !== undefined && next !== palette) {
                return onSelectPalette(next);
              }
            },
            children: Palette.all.map(option => JsxRuntime.jsx(Spectrum.MenuItem.make, {
              value: Palette.toTag(option),
              selected: option === palette,
              children: Palette.label(option)
            }, Palette.toTag(option)))
          }),
          JsxRuntime.jsx(Spectrum.Switch.make, {
            checked: Theme.isDark(props.theme),
            size: "s",
            ariaLabel: Translations.translate(locale, "DarkMode"),
            onChange: param => onToggleTheme()
          }),
          JsxRuntime.jsx(Spectrum.ActionButton.make, {
            label: accountName !== undefined ? Translations.translate(locale, "SignedInAs") + " " + accountName : Translations.translate(locale, "AccountLabel"),
            quiet: true,
            onClick: param => onAccount(),
            children: Icons.person
          })
        ],
        className: "flex items-center gap-2"
      })
    ],
    className: "rn-footer rn-surface flex shrink-0 flex-wrap items-center justify-end gap-x-3 gap-y-0.5 border-t px-4 py-0.5 text-xs"
  });
}

let make = Footer;

export {
  make,
}
/* Icons Not a pure module */
