// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Locale from "./core/Locale.res.mjs";
import * as Sanitizer from "./shell/Sanitizer.res.mjs";
import * as SafeMarkup from "./shell/SafeMarkup.res.mjs";
import * as Translations from "./core/Translations.res.mjs";
import * as MessageMarkdown from "./shell/MessageMarkdown.res.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as JsxRuntime from "react/jsx-runtime";

function MessageText(props) {
  let __className = props.className;
  let locale = props.locale;
  let text = props.text;
  let __className_value = __className !== undefined ? __className : "";
  let container = React.useRef(null);
  React.useEffect(() => {
    let element = container.current;
    if (!(element == null)) {
      Sanitizer.setInnerHtml(element, Sanitizer.toTrustedHtml(MessageMarkdown.toHtml(text)));
      SafeMarkup.harden(element, Translations.translate(locale, "LinkRemoved"));
      SafeMarkup.wrapWideTables(element, Translations.translate(locale, "ScrollableTable"));
    }
  }, [
    text,
    Locale.toTag(locale)
  ]);
  return JsxRuntime.jsx("div", {
    ref: Primitive_option.some(container),
    className: "rn-md" + (
      __className_value === "" ? "" : " " + __className_value
    )
  });
}

let make = MessageText;

export {
  make,
}
/* react Not a pure module */
