// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Brand from "./Brand.res.mjs";
import * as Icons from "./Icons.res.mjs";
import * as Route from "./core/Route.res.mjs";
import * as React from "react";
import * as Spectrum from "./spectrum/Spectrum.res.mjs";
import * as BarMetrics from "./shell/BarMetrics.res.mjs";
import * as Translations from "./core/Translations.res.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as JsxRuntime from "react/jsx-runtime";

function Navbar(props) {
  let onAssistant = props.onAssistant;
  let onImport = props.onImport;
  let onExport = props.onExport;
  let onSync = props.onSync;
  let onShare = props.onShare;
  let onCopyLink = props.onCopyLink;
  let onHome = props.onHome;
  let onToggleEditing = props.onToggleEditing;
  let copied = props.copied;
  let route = props.route;
  let locale = props.locale;
  let onApp = route !== "Gallery";
  let barRef = React.useRef(null);
  React.useEffect(() => {
    let node = barRef.current;
    if (!(node == null)) {
      return BarMetrics.track(node, "--rn-navbar-height");
    }
  }, []);
  return JsxRuntime.jsxs("nav", {
    children: [
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx(Brand.make, {}),
          JsxRuntime.jsxs("span", {
            children: [
              "Reactive",
              JsxRuntime.jsx("span", {
                children: "NET",
                className: "text-brand"
              })
            ],
            className: "text-base font-semibold tracking-tight"
          }),
          onApp ? JsxRuntime.jsx(Spectrum.ActionButton.make, {
              label: Translations.translate(locale, "BackToGallery"),
              onClick: param => onHome(),
              children: Icons.gallery
            }) : null
        ],
        className: "flex items-center gap-3"
      }),
      JsxRuntime.jsxs("div", {
        children: [
          onApp ? JsxRuntime.jsxs(JsxRuntime.Fragment, {
              children: [
                JsxRuntime.jsx(Spectrum.ActionButton.make, {
                  label: copied ? Translations.translate(locale, "LinkCopied") : Translations.translate(locale, "CopyLink"),
                  selected: copied,
                  onClick: param => onCopyLink(),
                  children: Icons.link
                }),
                JsxRuntime.jsx(Spectrum.ActionButton.make, {
                  label: Translations.translate(locale, "ShareApp"),
                  onClick: param => onShare(),
                  children: Icons.share
                }),
                JsxRuntime.jsx(Spectrum.ActionButton.make, {
                  label: Translations.translate(locale, "SyncPanel"),
                  onClick: param => onSync(),
                  children: Icons.sync
                }),
                JsxRuntime.jsx(Spectrum.ActionButton.make, {
                  label: Translations.translate(locale, "ExportApp"),
                  onClick: param => onExport(),
                  children: Icons.download
                }),
                props.canEdit ? JsxRuntime.jsx(Spectrum.ActionButton.make, {
                    label: Route.isEditing(route) ? Translations.translate(locale, "ViewApp") : Translations.translate(locale, "EditApp"),
                    onClick: param => onToggleEditing(),
                    children: Route.isEditing(route) ? Icons.eye : Icons.pencil
                  }) : null
              ]
            }) : JsxRuntime.jsx(Spectrum.ActionButton.make, {
              label: Translations.translate(locale, "ImportApp"),
              onClick: param => onImport(),
              children: Icons.upload
            }),
          JsxRuntime.jsx(Spectrum.ActionButton.make, {
            label: Translations.translate(locale, "AiPanel"),
            selected: props.assistantOpen,
            onClick: param => onAssistant(),
            children: Icons.sparkle
          })
        ],
        className: "flex items-center gap-1"
      })
    ],
    ref: Primitive_option.some(barRef),
    className: "rn-navbar rn-surface flex shrink-0 flex-wrap items-center justify-between gap-x-4 gap-y-1 border-b px-4 py-1.5"
  });
}

let make = Navbar;

export {
  make,
}
/* Brand Not a pure module */
