// Generated by ReScript, PLEASE EDIT WITH CARE

import * as AppIcon from "./AppIcon.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function PaneToolbar(props) {
  let icon = props.icon;
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsxs("span", {
        children: [
          icon !== undefined ? JsxRuntime.jsx(AppIcon.make, {
              name: icon,
              className: "rn-pane-icon"
            }) : null,
          props.title
        ],
        className: "rn-muted flex items-center pl-1 text-xs font-medium tracking-wide uppercase"
      }),
      JsxRuntime.jsx("div", {
        children: props.children,
        className: "flex items-center gap-1"
      })
    ],
    className: "rn-pane-bar rn-surface flex h-9 shrink-0 items-center justify-between gap-2 border-b px-2"
  });
}

let make = PaneToolbar;

export {
  make,
}
/* AppIcon Not a pure module */
