// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Locale from "./core/Locale.res.mjs";
import * as Columns from "./shell/Columns.res.mjs";
import * as Mermaid from "./shell/Mermaid.res.mjs";
import * as PageNav from "./shell/PageNav.res.mjs";
import * as AiBinder from "./shell/AiBinder.res.mjs";
import * as MlBinder from "./shell/MlBinder.res.mjs";
import * as ApiBinder from "./shell/ApiBinder.res.mjs";
import * as Dashboard from "./shell/Dashboard.res.mjs";
import * as GeoBinder from "./shell/GeoBinder.res.mjs";
import * as MapBinder from "./shell/MapBinder.res.mjs";
import * as Sanitizer from "./shell/Sanitizer.res.mjs";
import * as SqlBinder from "./shell/SqlBinder.res.mjs";
import * as SafeMarkup from "./shell/SafeMarkup.res.mjs";
import * as ChartBinder from "./shell/ChartBinder.res.mjs";
import * as PrintBinder from "./shell/PrintBinder.res.mjs";
import * as PythonBinder from "./shell/PythonBinder.res.mjs";
import * as Translations from "./core/Translations.res.mjs";
import * as ConfirmDialog from "./ConfirmDialog.res.mjs";
import * as ExploreBinder from "./shell/ExploreBinder.res.mjs";
import * as GeocodeBinder from "./shell/GeocodeBinder.res.mjs";
import * as ReactiveStore from "./shell/ReactiveStore.res.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as OpenDataBinder from "./shell/OpenDataBinder.res.mjs";
import * as WorkflowBinder from "./shell/WorkflowBinder.res.mjs";
import * as FileFieldBinder from "./shell/FileFieldBinder.res.mjs";
import * as CollectionBinder from "./shell/CollectionBinder.res.mjs";
import * as MarkdownRenderer from "./shell/MarkdownRenderer.res.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as SpectrumElements from "./shell/SpectrumElements.res.mjs";
import * as DirectiveRegistry from "./core/DirectiveRegistry.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

let spectrumSelector = DirectiveRegistry.all.map(component => component.tag).filter(tag => {
  if (tag.startsWith("sp-")) {
    return true;
  } else {
    return tag.includes("-");
  }
}).join(",");

let usesSpectrumComponents = (function (container, selector) { return container.querySelector(selector) !== null; });

function Render(props) {
  let app = props.app;
  let locale = props.locale;
  let theme = props.theme;
  let source = props.source;
  let container = React.useRef(null);
  let match = React.useState(() => {});
  let setPending = match[1];
  let pending = match[0];
  let confirmDelete = React.useCallback(row => new Promise((resolve, param) => setPending(param => ({
    row: row,
    answer: agreed => resolve(agreed)
  }))), []);
  let settle = agreed => (() => {
    if (pending !== undefined) {
      pending.answer(agreed);
    }
    setPending(param => {});
  });
  React.useEffect(() => {
    let element = container.current;
    if (!(element == null)) {
      let html = Sanitizer.toTrustedHtml(MarkdownRenderer.toHtml(source));
      Sanitizer.setInnerHtml(element, html);
      SafeMarkup.harden(element, Translations.translate(locale, "LinkRemoved"));
      if (usesSpectrumComponents(element, spectrumSelector)) {
        SpectrumElements.ensureLoaded();
      }
      SafeMarkup.wrapWideTables(element, Translations.translate(locale, "ScrollableTable"));
      Columns.bind(element);
      PageNav.bind(element, {
        pages: Translations.translate(locale, "Pages")
      });
      ReactiveStore.bind(element);
      if (app !== undefined) {
        CollectionBinder.bind(element, app, {
          deleteRow: Translations.translate(locale, "DeleteRow"),
          editRow: Translations.translate(locale, "EditRow"),
          searchRows: Translations.translate(locale, "SearchRows"),
          previousPage: Translations.translate(locale, "PreviousPage"),
          nextPage: Translations.translate(locale, "NextPage"),
          sortedAscending: Translations.translate(locale, "SortedAscending"),
          sortedDescending: Translations.translate(locale, "SortedDescending"),
          allValues: Translations.translate(locale, "AllValues"),
          previousMonth: Translations.translate(locale, "PreviousMonth"),
          nextMonth: Translations.translate(locale, "NextMonth"),
          previousWeek: Translations.translate(locale, "PreviousWeek"),
          nextWeek: Translations.translate(locale, "NextWeek"),
          today: Translations.translate(locale, "TodayAction"),
          blockedCell: Translations.translate(locale, "CellBlocked"),
          pinnedRow: Translations.translate(locale, "PinnedRow")
        }, Locale.toTag(locale), confirmDelete);
      }
      if (app !== undefined) {
        OpenDataBinder.bind(element, app, {
          loading: Translations.translate(locale, "OdLoading"),
          rows: Translations.translate(locale, "OdRows"),
          stale: Translations.translate(locale, "OdStale"),
          unreachable: Translations.translate(locale, "OdUnreachable"),
          refused: Translations.translate(locale, "OdRefused"),
          search: Translations.translate(locale, "OdSearchAction")
        });
      }
      if (app !== undefined) {
        ChartBinder.bind(element, app);
        MapBinder.bind(element, app);
        ExploreBinder.bind(element, app);
      }
      GeoBinder.bind(element);
      PrintBinder.bind(element, Stdlib_Option.getOr(app, ""), {
        print: Translations.translate(locale, "PrintAction"),
        printEach: Translations.translate(locale, "PrintEach")
      });
      if (app !== undefined) {
        FileFieldBinder.bind(element, app, {
          tooBig: Translations.translate(locale, "FileTooBig")
        });
      }
      Dashboard.bind(element, {
        removeFilter: Translations.translate(locale, "RemoveFilter")
      });
      if (app !== undefined) {
        GeocodeBinder.bind(element, app, {
          loading: Translations.translate(locale, "OdLoading"),
          rows: Translations.translate(locale, "OdRows"),
          stale: Translations.translate(locale, "OdStale"),
          unreachable: Translations.translate(locale, "OdUnreachable"),
          refused: Translations.translate(locale, "OdRefused"),
          search: Translations.translate(locale, "OdSearchAction")
        });
        ApiBinder.bind(element, app, {
          loading: Translations.translate(locale, "OdLoading"),
          rows: Translations.translate(locale, "OdRows"),
          stale: Translations.translate(locale, "OdStale"),
          unreachable: Translations.translate(locale, "OdUnreachable"),
          refused: Translations.translate(locale, "OdRefused"),
          refresh: Translations.translate(locale, "ApiRefresh")
        });
      }
      if (app !== undefined) {
        MlBinder.bind(element, app, {
          run: Translations.translate(locale, "RunAction"),
          loading: Translations.translate(locale, "OdLoading"),
          rows: Translations.translate(locale, "OdRows"),
          refused: Translations.translate(locale, "OdRefused"),
          engine: Translations.translate(locale, "MlEngineNeeded")
        });
        SqlBinder.bind(element, app, {
          run: Translations.translate(locale, "RunAction"),
          loading: Translations.translate(locale, "OdLoading"),
          rows: Translations.translate(locale, "OdRows"),
          refused: Translations.translate(locale, "OdRefused")
        });
      }
      if (app !== undefined) {
        AiBinder.bind(element, app, {
          notConfigured: Translations.translate(locale, "AiNotConfigured"),
          thinking: Translations.translate(locale, "AiThinking"),
          ask: Translations.translate(locale, "AiAsk"),
          send: Translations.translate(locale, "AiSend"),
          run: Translations.translate(locale, "RunAction"),
          refresh: Translations.translate(locale, "ApiRefresh"),
          rows: Translations.translate(locale, "OdRows"),
          refused: Translations.translate(locale, "OdRefused"),
          confirm: Translations.translate(locale, "AiConfirm"),
          noAnswer: Translations.translate(locale, "AiNoAnswer"),
          indexing: Translations.translate(locale, "AiIndexing")
        });
      }
      if (app !== undefined) {
        PythonBinder.bind(element, app, {
          showCode: Translations.translate(locale, "ShowCode"),
          hideCode: Translations.translate(locale, "HideCode"),
          running: Translations.translate(locale, "PythonRunning"),
          loading: Translations.translate(locale, "PythonLoading"),
          run: Translations.translate(locale, "RunAction"),
          stop: Translations.translate(locale, "StopAction"),
          progress: Translations.translate(locale, "InProgress")
        });
      }
      if (app !== undefined) {
        WorkflowBinder.bind(element, app, {
          run: Translations.translate(locale, "WorkflowRunNow"),
          stop: Translations.translate(locale, "StopAction"),
          steps: Translations.translate(locale, "WorkflowSteps"),
          waiting: Translations.translate(locale, "WorkflowWaiting"),
          running: Translations.translate(locale, "InProgress"),
          skipped: Translations.translate(locale, "WorkflowSkipped"),
          failed: Translations.translate(locale, "WorkflowFailed"),
          last: Translations.translate(locale, "WorkflowLastRun"),
          next: Translations.translate(locale, "WorkflowNextRun"),
          never: Translations.translate(locale, "WorkflowNever"),
          cycle: Translations.translate(locale, "WorkflowCycle"),
          looped: Translations.translate(locale, "WorkflowLooped"),
          empty: Translations.translate(locale, "WorkflowNoSteps"),
          whileOpen: Translations.translate(locale, "WorkflowWhileOpen")
        }, Locale.toTag(locale));
      }
      Mermaid.run(element, theme);
    }
  }, [
    source,
    theme,
    locale,
    Stdlib_Option.getOr(app, "")
  ]);
  let tmp;
  if (pending !== undefined) {
    let row = pending.row;
    tmp = row !== "" ? row + " — " + Translations.translate(locale, "DeleteRowWarning") : Translations.translate(locale, "DeleteRowWarning");
  } else {
    tmp = Translations.translate(locale, "DeleteRowWarning");
  }
  return JsxRuntime.jsxs(JsxRuntime.Fragment, {
    children: [
      JsxRuntime.jsx("div", {
        ref: Primitive_option.some(container),
        className: "rn-markdown px-6 py-4"
      }),
      JsxRuntime.jsx(ConfirmDialog.make, {
        open_: Stdlib_Option.isSome(pending),
        title: Translations.translate(locale, "DeleteRowQuestion"),
        message: tmp,
        confirmLabel: Translations.translate(locale, "DeleteRow"),
        cancelLabel: Translations.translate(locale, "CancelAction"),
        onConfirm: settle(true),
        onCancel: settle(false)
      })
    ]
  });
}

let make = Render;

export {
  make,
}
/* spectrumSelector Not a pure module */
